### ISSUE TITLE
Feedback on 18F’s Style guide for open source project documentation

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#1052]
We recently [published]() a style guide for open source project documentation.

We would love your feedback to make it even better. What are we missing? Let us know.

**Comment by esgoodman** [comment]
I'd like a bit talking about the various ways we might describe the users
of our products. Not all members of the public are citizens, for example.
And I know that  many agencies actually like to refer to the people they
serve as "customers". Some rules of thumb would be helpful!

**Comment by melodykramer** [comment]
This would make a good blog post / discussion / fodder for the Content Guide. Pinging @emileighoutlaw and @kategarklavs.
