### ISSUE TITLE
create a Code of Conduct document

### ISSUE THREAD

**Issue by ultrasaurus** [18F/18f.gsa.gov#111]
It is becoming common for open source projects and there are people who won't participate in events unless there is one.

Where will this be used?  if human, then this applies 
* events, slack, mailing lists, github issues
* applies to everyone (18F team, GSA, other feds, private sector people who interact with us or in our communities)

This should be published on the website for easy access.

I'd like the follow the Bridge Foundry model where the Code of Conduct is more than an anti-harrassment policy (which is what most conferences do) and instead describe a higher bar of acceptable conduct.  

Examples:
- [Bridge Foundry Code of Conduct](http://bridgefoundry.org/code-of-conduct/) used for RailsBridge, and other related workshops and opens source projects
- https://openhatch.org/wiki/Project_codes_of_conduct
- http://yesandyesyes.com/code-of-conduct
- http://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/
- http://geekfeminism.wikia.com/wiki/Code_of_conduct
- http://www.pyladies.com/CodeOfConduct/
- https://www.hackerschool.com/manual#sec-environment

More links added: 
- http://geekfeminism.org/about/code-of-conduct/
- https://www.python.org/psf/codeofconduct/

## Proposed Outline
* Diversity Statement 
* Our values?
* What does it mean to be welcoming (examples?)
* Links to other stuff (anti-harrassment, ethics?, open source policy)

### Diversity Statement 
18F welcomes and encourages participation by everyone.  We work for the America people, and welcome participation from anyone in the world with a desire to improve our projects.

No matter how you identify yourself or how others perceive you: we welcome you. We welcome contributions from everyone as long as they interact constructively with our community.  

We are responsible for technical implementation, but most of our work is not technical in nature.   We value and encourage contributions from those with expertise in policy, private sector or public service, writing, design, usability, as well as code, and welcome them into our community.

**Comment by ultrasaurus** [comment]
this moved to its own repo here:  https://github.com/18F/code-of-conduct

**Comment by ultrasaurus** [comment]
@gboone wanted to leave this open, since he's considering that it may be appropropriate to be displayed as a page on 18F site in the future

**Comment by gboone** [comment]
Wondering if we've made any in-roads to approval from the appropriate parties on this? If I'm remembering correctly, this is all that's blocking us from publishing:
- [ ] HR approval
- [ ] General Counsel approval

**Comment by elainekamlley** [comment]
Shipped May 12, 2015 with all approvals: 

- Blog post: https://18f.gsa.gov/2015/05/12/on-culture-change-a-code-of-conduct/
- GitHub: https://github.com/18F/code-of-conduct
