### ISSUE TITLE
Prettier links

### ISSUE THREAD

**Issue by maya** [18F/18f.gsa.gov#1128]
What do you think about implementing some prettier links? 

Something like this:

![](https://s3.amazonaws.com/f.cl.ly/items/2V1p0P1i3I1t41220Y2W/Screen%20Recording%202015-08-28%20at%2005.28%20PM.gif)

**Comment by gboone** [comment]
Sure! Looks good to me!

**Comment by elainekamlley** [comment]
Awesome! Send over a PR!
