### ISSUE TITLE
Remove comma from posts with 2 authors

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1246]
The byline format for post with two authors is `by First Last, and First Last`. Here's a [live example](https://18f.gsa.gov/2015/10/07/digital-economy-practice/). 

Can we remove the comma after the first name? It should only appear if there are three or more names.

**Comment by gboone** [comment]
Great catch, @awfrancisco this will be resolved with #1247

**Comment by awfrancisco** [comment]
Awesome. Thanks for the quick response.
