### ISSUE TITLE
SyntaxError if Ruby < 2.2

### ISSUE THREAD

**Issue by catherinedevlin** [18F/18f.gsa.gov#1291]
If Ruby < 2.2 is used, `./go serve` gives a very confusing error.  Since many repositories only have older versions of Ruby, the README.md should warn about that.

    $ ./go serve
    /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require': /var/lib/gems/2.1.0/gems/jekyll_frontmatter_tests-0.0.5/lib/jekyll_frontmatter_tests.rb:11: syntax error, unexpected ':', expecting => (SyntaxError)
    ...'frontmatter_tests'] = {'path': File.join("deploy", "tests",...
    ...                               ^
    /var/lib/gems/2.1.0/gems/jekyll_frontmatter_tests-0.0.5/lib/jekyll_frontmatter_tests.rb:11: syntax error, unexpected '}', expecting keyword_end
    /var/lib/gems/2.1.0/gems/jekyll_frontmatter_tests-0.0.5/lib/jekyll_frontmatter_tests.rb:213: syntax error, unexpected end-of-input, expecting keyword_end
    	from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    	from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
    	from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
    	from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    	from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    	from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:39:in `require_from_bundler'
    	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/bin/jekyll:13:in `<top (required)>'
    	from /usr/local/bin/jekyll:23:in `load'
    	from /usr/local/bin/jekyll:23:in `<main>'

**Comment by gboone** [comment]
Good idea, @catherinedevlin, looks like it's time to up the [minimum version](https://github.com/18F/18f.gsa.gov/blob/staging/go#L31) in the go script, too.
