### ISSUE TITLE
redirects for 18f.gsa.gov/join and/or 18f.gsa.gov/apply ?

### ISSUE THREAD

**Issue by aaronsnow** [18F/18f.gsa.gov#1323]
Now that we're open for business again, it'd be great to get https://18f.gsa.gov/join and/or https://18f.gsa.gov/apply redirected to the main recruiting page, https://pages.18f.gov/joining-18f/ , which is a mouthful and harder to remember when people ask. :)

**Comment by gboone** [comment]
We now have `join` which has some content on it and directs people to the joining-18f page for more information. I'll add a redirect from `/apply/`, too.
