### ISSUE TITLE
Accessing directories without indexes should result in a 404, not 403

### ISSUE THREAD

**Issue by benbalter** [18F/18f.gsa.gov#1334]
https://18f.gsa.gov/2015/ exists, because https://18f.gsa.gov/2015/02/25/we-are-hiring/ does. 

However, since directory listing is disabled, trying to access https://18f.gsa.gov/2015/, results in a 403 error (forbidden), not a 404 as I'd expect (not found). 

I'm not expecting every directory traversal URL to work, but I suspect the 403 response code isn't intentional and most users would expect a 404, not a 403.

**Comment by konklone** [comment]
It seems like the issue could be addressed with a minor nginx tweak:

https://serverfault.com/questions/610305/nginx-404-instead-of-403-for-empty-directory

**Comment by gboone** [comment]
I've also considered creating date archives now that our blog is somewhat large. That could be easier and wouldn't require anything to change in NGINX.
