### ISSUE TITLE
Some profile sass may be redundant

### ISSUE THREAD

**Issue by openbrian** [18F/18f.gsa.gov#1382]
So I was looking at the team page and wondering how the bios were offset every other row in a honeycomb pattern -- while at the same time falling into a square pattern at lower screen widths.  That's cool, but that's not the issue.

The issue is, this defintion is repeated on lines 1651 and 1514 of the compiled stylesheet:

#team .bio:nth-child(10n+6) {
    margin-left: 65px;
}

So I was curious about why that happened.  And I think I found the cause.  It looks like _team.scss and _profile.scss have the same content.  I'm guessing one of those is not needed.

**Comment by openbrian** [comment]
The math geek in me is suggesting for April Fool's you try the newly discovered Type 15 pentagonal tiling https://en.wikipedia.org/wiki/Pentagonal_tiling#Mann.2FMcLoud.2FVon_Derau_.282015.29_Type_15

**Comment by gboone** [comment]
Interesting find, @openbrian. I'll look into the duplication. I know @elainekamlley and @msecret were cleaning up some of the CSS monsters I created in here with #1301, maybe the found the same thing.

Also, we might have to add that to our April Fools plans for this year.

**Comment by neilmartis** [comment]
Is it possible to have a pop up option on the picture which would be give some additional information about the person and a short summary of the work they do at 18F or a circular grid for the same.

**Comment by neilmartis** [comment]
or a hover option over the pictures which gives a short bio and if they require any additional information they can click on more thereby reducing the clicks on the page and they get a general idea of who the person is and what they do at 18F this will help reduce the space reduction or something based on the profile intro which is used by Code For America 
![codeforamerica](https://cloud.githubusercontent.com/assets/10228512/12955228/1c6a2f34-cff0-11e5-9594-0937b388d194.PNG)

**Comment by gboone** [comment]
That's definitely something we've considered as that page has grown. I really like how CFA has done that, and it might give people enough information without having to click further into the page. Thanks for keeping this thread alive, @openbrian. :)

**Comment by neilmartis** [comment]
I can do that for you.no problem

**Comment by neilmartis** [comment]
Hi Greg

I can do it no problem.I am glad to help.

Thanks,
Neil

**Comment by neilmartis** [comment]
Hi Greg 
I sent you an email regarding a problem with My USCIS.gov I didn't know who to contact hence sent it over as there is a problem with it

**Comment by neilmartis** [comment]
Hi Greg As i don't have a mac and ruby installed on my machine here is some part of the code which can be used  

  </div>
                                    
                                </li>
                                                            
                                <li class="member">
                                    <div class="member-image">
                                        <a class="fancybox" href="#DrNasserAbukhdeir-bio">
                                            <img src="http://ecocar3.org/wp-content/uploads/2014/10/Abukhdier_Nasser-223x149.jpg" alt="" height="130"/>
                                        </a>
                                    </div>
                                    

                                    <div class="member-content">
                                        <a class="fancybox" href="#DrNasserAbukhdeir-bio">
                                            <h3>Dr Nasser Abukhdeir</h3>
                                            <h4>Faculty Advisor</h4>
                                        </a>

                                        <div id="DrNasserAbukhdeir-bio" style="display:none;">
                                            <img src="http://ecocar3.org/wp-content/uploads/2014/10/Abukhdier_Nasser-223x149.jpg" alt="" height="130"/>

                                            <h2>Dr Nasser Abukhdeir</h2>

                                            <h3>Faculty Advisor</h3>
                                            <br/>
                                            Education: BSc (Chemical Engineering, Carnegie Mellon University), BSc (Computer Science, Carnegie Mellon University), MChE (Carnegie Mellon University), PhD (McGill University)

<hr />

Research Interests: External Field-Driven Dynamics of Liquid Crystal Domains, Phase Transformations of Crystalline and Liquid Crystal Materials, Hydrodynamics of Complex Fluids and Multiphase Flows, Computational Methods in Engineering

<hr />

<a href="https://uwaterloo.ca/institute-nanotechnology/people-profiles/nasser-m-abukhdeir">https://uwaterloo.ca/institute-nanotechnology/people-profiles/nasser-m-abukhdeir</a>

&nbsp;                                        </div>

                                    </div>
                                    
                                </li>
                                                            
                                <li class="member">
                                    <div class="member-image">
                                        <a class="fancybox" href="#PatrickEllsworth-bio">
                                            <img src="http://ecocar3.org/wp-content/uploads/2014/10/Pat-223x149.jpg" alt="" height="130"/>
                                        </a>
                                    </div>
                                    

                                    <div class="member-content">
                                        <a class="fancybox" href="#PatrickEllsworth-bio">
                                            <h3>Patrick Ellsworth</h3>
                                            <h4>Engineering Manager</h4>
                                        </a>

                                        <div id="PatrickEllsworth-bio" style="display:none;">
                                            <img src="http://ecocar3.org/wp-content/uploads/2014/10/Pat-223x149.jpg" alt="" height="130"/>

                                            <h2>Patrick Ellsworth</h2>

                                            <h3>Engineering Manager</h3>
                                            <br/>
                                            Currently Studying: Master's of Applied Science, Mechanical Engineering

<hr />

The output will be something like this http://ecocar3.org/waterloo/team-members/
