### ISSUE TITLE
RSS title URL is incorrect

### ISSUE THREAD

**Issue by szieglerICF** [18F/18f.gsa.gov#1497]
I just noticed that the title link in the RSS feed is incorrect. It contains a double reference to the domain name. 

```
<title>Tips for capturing the best data from user interviews</title>
<link href="https://18f.gsa.govhttps://18f.gsa.gov/2016/02/09/tips-for-capturing-the-best-data-from-user-interviews/" rel="alternate" type="text/html" title="Tips for capturing the best data from user interviews" />
```
PS. RSS is not dead! :)

**Comment by konklone** [comment]
Hmm, we use [`jekyll-feed`](https://github.com/jekyll/jekyll-feed), and I can't see why this would happen, but you are [absolutely right](view-source:https://18f.gsa.gov/feed/).

I guess it must be using our `url` field in `_config.yml`, which is a relative URL, and treating it as a path prefix instead? That doesn't seem likely or correct, but I'm not sure why else this would happen. Any ideas?

**Comment by gboone** [comment]
I bet we can just kill that `url` field and use `baseurl` where we're currently using `url`. I'll see if that does it.

**Comment by gboone** [comment]
I've verified this is closed on my end, does it look good to you, @szieglerICF?

**Comment by szieglerICF** [comment]
It works. Thanks!
