### ISSUE TITLE
Print stylesheet

### ISSUE THREAD

**Issue by andrewmaier** [18F/18f.gsa.gov#1606]
We should provide a stylesheet that leverages [best](https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/) [practices](http://alistapart.com/article/goingtoprint) and helps people print our blog posts :)

**Comment by benguhin** [comment]
Def check out the work from @huetingj and @cfarm at the CFPB:
https://github.com/cfpb/design-manual/issues/281#issuecomment-163691016

**Comment by awayken** [comment]
@andrewmaier Do you have an example of a blog post that incorporates a lot of the elements that a print stylesheet would need to address? Outsiders might not have a clear or expansive picture of what all is possible in a blog post.

Is ["Making more consistent decisions with design principles: A new 18F guide"](https://18f.gsa.gov/2016/04/08/making-more-consistent-decisions-with-design-principles-a-new-18f-guide/) a good example?

**Comment by awfrancisco** [comment]
Closing since it was addressed in #1632
