### ISSUE TITLE
Newsletter signup email input should be type 'email'

### ISSUE THREAD

**Issue by patrickcate** [18F/18f.gsa.gov#1608]
I just signed up for the 18f newsletter at the bottom of: https://18f.gsa.gov in iOS Safari. I noticed for the email field the type is set to `text`. Changing this to `type="email"` would greatly improve usability, particularly on mobile devices where it brings up the email specific keyboard.

**Comment by gboone** [comment]
I think you fixed this in #1612, right? Thanks for the contribution and feel free to re-open if that doesn't full address it.
