### ISSUE TITLE
Business development page for agencies

### ISSUE THREAD

**Issue by aaronsnow** [18F/18f.gsa.gov#163]
We need a page (`/working-with-18f` ?) that describes/FAQs how we do business with agencies -- i.e., the IAA process. It should probably also have a short contact form for agency reps.

**Comment by elainekamlley** [comment]
This issue will be partly addressed in this content sprint. The main deliverable at the end of this sprint is to have a working draft of a '/delivery' sub page and a 150 word intro for the home page that explains the services we provide and how to work with 18F. What you all address is a bit more granular, but we can begin with a more big picture of what we offer. That would eventually lead to more of the specifics like IIAs and process oriented items. @gboone will be reaching out to @aaronsnow and @wslack to develop this content.

**Comment by wslack** [comment]
Good news on this one - I have a working draft of a Client Playbook in Google docs that covers some of this, but hasn't been prioritized. Happy to help develop the more general content as well; I've got a whole spiel down on the different lines of business.

**Comment by elainekamlley** [comment]
Criteria: 
- [ ] What we do 
- [ ] What we do not do
- [ ] team 
- [ ] services 
- [ ] inquires call to action
- [ ] points to the playbook

**Comment by elainekamlley** [comment]
The start of a `/delivery` page was created in #936 and has a section of what we do and how we work along with some blog post of some of our products and partnerships. This page currently does not address the need for deeper client information like the IIA process. We will eventually link to the playbook when it is finalized. This will have more detailed information about the full process of working with 18F.
