### ISSUE TITLE
Add subpage for 'what we deliver'

### ISSUE THREAD

**Issue by meiqimichelle** [18F/18f.gsa.gov#1652]
It should be based on the subpage layout of the current [consulting page](https://18f.gsa.gov/consulting/)

![screenshot 2016-04-20 14 27 30](https://cloud.githubusercontent.com/assets/4827522/14691058/08346048-0704-11e6-8f63-9b5fced63dc3.png)

The content for this new page will probably have examples of our work. We can link out to that, and/or provide images of our work as well. If we want images, we have these collected, but we would need to adapt the design in an elegant way to accommodate them.

Priority #1: Update content without images.
If there is time/energy, see about getting those lovely screenshots up and running. They should not be a blocker to updating the content.

**Comment by awfrancisco** [comment]
[Done](https://18f.gsa.gov/what-we-deliver/)
