### ISSUE TITLE
Add 'Join Us' subpage

### ISSUE THREAD

**Issue by meiqimichelle** [18F/18f.gsa.gov#1654]
This page should be based on the layout of the current [consulting subpage](https://18f.gsa.gov/consulting/). If there is time, it would be great to have:

1. IMAGE: map of locations, date it so we don’t have to update it every time someone joins

1. INFOGRAPHIC: where folks came from

The images should not be blockers to updating the content.

**Comment by awfrancisco** [comment]
Done. https://18f.gsa.gov/join/

Next step is incorporating join.18f.gov into the site.
