### ISSUE TITLE
Remove Consulting page/link from homepage

### ISSUE THREAD

**Issue by adelevie** [18F/18f.gsa.gov#1658]
I think our re-org has made this obsolete.

**Comment by awfrancisco** [comment]
Yup. Site team is on it. Issues #1648 through #1655 will soon be changing a number of things on the site, including getting rid of the consulting page.

**Comment by adelevie** [comment]
:thumbsup:

**Comment by meiqimichelle** [comment]
💥 
![screenshot 2016-05-02 13 15 03](https://cloud.githubusercontent.com/assets/4827522/14966548/e8ac8dc8-1067-11e6-9d8f-10fa2301ecb5.png)

**Comment by meiqimichelle** [comment]
@adelevie That was fairly poor form -- I should have let you close this issue. I WAS JUST SO EXCITED :D 💃 💃 💃
