### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#1669]
From a member of the public, via email, we have a couple of broken links on this page:
https://18f.gsa.gov/2016/03/23/how-to-integrate-the-draft-us-web-design-standards-into-existing-projects/

eg https://playbook.cio.gov/designstandards/sidenav/

and https://playbook.cio.gov/designstandards/form-templates/

The correct links for those are https://standards.usa.gov/sidenav/ and https://standards.usa.gov/form-templates/

We should check the post for any other links to the playbook.cio.gov domain to make sure they're working properly.

**Comment by toolness** [comment]
I was about to take this on, but it seems @melodykramer fixed it in a2be01829246cf9aac1e6025624fc57213017632?

**Comment by gboone** [comment]
Yes, it looks like @melodykramer did indeed, if quietly, fix this.
