### ISSUE TITLE
Add Link to Agile BPA pages site

### ISSUE THREAD

**Issue by jposi** [18F/18f.gsa.gov#1671]
We get asked enough about the AgileBPA it would be good to have a link on the main 18F page to it, somewhere.

Here's the page for agencies: https://pages.18f.gov/ads-bpa/buyers/

**Comment by awfrancisco** [comment]
We linked to it in the new content. https://18f.gsa.gov/what-we-deliver/

Do you think it'd be better if it went directly to the buyer's page?
