### ISSUE TITLE
Add instructions for installing rvm and/or ruby 2.2.3

### ISSUE THREAD

**Issue by toolness** [18F/18f.gsa.gov#1690]
It seems `./go init` raises an error on a default OS X box telling users that they don't have Ruby 2.2.3, which is specified by the `Gemfile` (currently OS X El Capitan uses Ruby 2.0). Should the README point the user to installing [rvm](https://rvm.io/) or a similar tool?

**Comment by gboone** [comment]
We have been working under the assumption that users will have run the 18F/laptop script to set up their dev environment, which I think instals `rvm`. Perhaps this is not a great assumption, but if we include the Docker file (#1688) and update the docs to serve the site that way, it's less of an issue, right?

**Comment by toolness** [comment]
Ah, good point!  That makes sense, I will close this issue now.
