### ISSUE TITLE
Aidan Feldman's team entry ends with a weird quote

### ISSUE THREAD

**Issue by toolness** [18F/18f.gsa.gov#1693]
I wanted to fix this as part of #1692 but I wasn't sure how:

> Aidan says he joined 18F because he was looking for an organization that is as passionate about open source as he is. "I can’t think of many opportunities with as enormous of potential impact as "changing how the federal government does technology," he says.

There seems to be an extra double quote mark in there... But aside from that, the phrase "as enormous of potential impact" is confusing to me. Also not sure if it's appropriate to change it--if that's literally what he said, perhaps it's best to keep it in there?

**Comment by awfrancisco** [comment]
@elainekamlley @gboone Do you remember if that was an actual quote?

**Comment by elainekamlley** [comment]
Hmm, I don't. @afeld can we get a new quote from you? Not sure what happened to the original.

**Comment by afeld** [comment]
Yeesh, really struggling with how to word this. Trying to convey the following:

* 18F has a unique value proposition
* 18F has potential to change how government does technology
* That potential for change is much larger than most other jobs I can think of

Thoughts?

**Comment by elainekamlley** [comment]
Hmm, how about? 

Aidan joined 18F because of the opportunity to change how the government does technology. He goes on to say, "This potential is much larger than most jobs I can think of".

**Comment by gboone** [comment]
This will be addressed with the deprecation (and eventual re-thinking) of how we display our team. Thanks @toolness
