### ISSUE TITLE
Team Page giving a 404 error when calling from the page footer

### ISSUE THREAD

**Issue by neilmartis** [18F/18f.gsa.gov#1705]
When I clicked on the page footer of the team page I am getting a 404 error
https://18f.gsa.gov/site/18F/18f.gsa.gov/team/
![18fteam](https://cloud.githubusercontent.com/assets/10228512/15181594/15db91e6-1756-11e6-9eef-eb3db0c24561.png)

**Comment by brendansudol** [comment]
thank you!

fixed via https://github.com/18F/18f.gsa.gov/pull/1706
