### ISSUE TITLE
"Stages" Page on Project Dashboard is a 404

### ISSUE THREAD

**Issue by cew821** [18F/18f.gsa.gov#1725]
This page (in staging): https://staging.18f.gov/dashboard/stages/

Does not exist in production: https://18f.gsa.gov/dashboard/stages

This results in a 404 on a lot of 18F properties that link to the stages page to describe what "alpha" and "beta" mean. For example, the Web Design Standards, Federalist, and Cloud.gov all point to this page which is now a 404.

Here's the page on the old dashboard, for reference: https://github.com/18F/dashboard/blob/staging/stages.html

**Comment by gboone** [comment]
Thanks for bringing this to our attention @cew821, we recently migrated the website and merged the dashboard with the rest of the codebase and it looks like one or two pages missed the boat.
