### ISSUE TITLE
Insecure redirect: https://gsa.gov/tts

### ISSUE THREAD

**Issue by ungoldman** [18F/18f.gsa.gov#1728]
Looks like https://gsa.gov has a SSL cert problem. The link to TTS on the blog post about the shared auth platform causes a `NET::ERR_CERT_AUTHORITY_INVALID` error in latest Chrome.

## Steps to Reproduce

Go to https://18f.gsa.gov/2016/05/10/building-a-modern-shared-authentication-platform/.

Click the link to Technology Transformation Service (https://gsa.gov/tts).

## Expected Behavior

Link is cool.

## Observed Behavior

Link is not cool.

## Evidence

![screen shot 2016-05-17 at 12 08 15 pm](https://cloud.githubusercontent.com/assets/427322/15335646/1051c89a-1c28-11e6-903e-74e993cd938f.png)

## By the way

You're doing great work, 18F!

![](https://s-media-cache-ak0.pinimg.com/236x/ab/07/88/ab078839f1c7152f957bf03fd94f102d.jpg)

**Comment by konklone** [comment]
Thanks for reporting this! Unfortunately, since we don't have control over gsa.gov, all we can do is fix the link right now. I've filed https://github.com/18F/18f.gsa.gov/pull/1729 to do this.

**Comment by ungoldman** [comment]
Looks like the link is fixed, thanks @konklone!
