### ISSUE TITLE
Replace SSL cert

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#173]
I have an outstanding certificate request with DevOps, we're waiting on access to the validation email address we need for a new certificate. It'll be 4096-bits and use a full SHA-2 chain.

Old:

![18f-ssl-old](https://cloud.githubusercontent.com/assets/4592/4337172/f42cc4b0-400c-11e4-8d93-c4167b5092e9.png)

**Comment by gboone** [comment]
@konklone any update on this? I thought we got the new cert and all that a couple months back but the results here: https://www.ssllabs.com/ssltest/analyze.html?d=18f.gsa.gov are not the same as on the staging site. Let me know what you know.

**Comment by konklone** [comment]
Yeah, our cert is fine now, so we can close this. But we're still awaiting DNS delegation for 18f.gsa.gov so that we don't need to depend on others to issue our SSL cert for us in the future.
