### ISSUE TITLE
Switch contact form to use MailChimp or GovDelivery

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#175]
As @aaronsnow pointed out in https://github.com/18F/18f.gsa.gov/issues/157#issuecomment-55852589 we can use MailChimp now, so we can restore the removed contact form.

We'd need to:

- [x] Create our official account.
- [x] Restore the HTML and form fields we had before.
- [x] Point it to the right URL.
- [x] Ideally migrate our old Hydra list

**Comment by NoahKunin** [comment]
Oh shoot, never saw the mention here, sorry @konklone. Scheduling this now.

**Comment by gboone** [comment]
Pretty sure we did this a couple months ago!
