### ISSUE TITLE
Blog RSS feed link is broken

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1779]
From an email

>Just wanted to let you know that the link to subscribe via e-mail to your blog leads to an IFTTT recipe that doesn’t work. It looks like the Feed URL listed in the recipe is missing the ‘.xml’ extension, because when I include it, the recipe works:

**Comment by gboone** [comment]
This is a problem with the IFTTT recipe, not the blog. @konklone it looks like you own the IFTT recipe, would you be able to update it?

**Comment by konklone** [comment]
IFTTT recipe fixed: https://ifttt.com/recipes/214709-a-new-18f-blog-post-email-me-a-link-to-go-read-it-right-away
