### ISSUE TITLE
Accept-Encoding header is ignored

### ISSUE THREAD

**Issue by leppert** [18F/18f.gsa.gov#1796]
Each of the following will return gzip encoded content:

``` bash
curl -v https://18f.gsa.gov/
curl -v -H "Accept-Encoding: " https://18f.gsa.gov/
curl -v -H "Accept-Encoding: gzip;q=0" https://18f.gsa.gov/
curl -v -H "Accept-Encoding: identity" https://18f.gsa.gov/
```

Relevant spec is here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3

It'd be nice to get an uncompressed response when gzip is not explicitly requested. Example:

``` bash
curl -v https://www.google.com/
curl -v -H "Accept-Encoding: gzip" https://www.google.com/
```

**Comment by gboone** [comment]
Thanks @leppert we'll take a look at this!

**Comment by gemfarmer** [comment]
This is currently fixed!
