### ISSUE TITLE
Remove duplicate binary image assets if necessary

### ISSUE THREAD

**Issue by dogweather** [18F/18f.gsa.gov#1800]
We're optimizing the images, which may inflate the repo size. This task is to remove the older versions.

**Comment by gemfarmer** [comment]
Maybe we could consider adding a comment to the PR template that looks like:

- [ ] All images optimized **_*--> [learn more]() about how to optimize images* <--_**

With the link going to the style guide images section. I think this could be a lightweight way of reminding us to optimize images.

**Comment by elainekamlley** [comment]
@gboone lets chat about this further. Can this be something you and I pair on?

**Comment by elainekamlley** [comment]
This has been added to the styleguide
