### ISSUE TITLE
Broken previous link on blog

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1825]
From email:

> https://18f.gsa.gov/blog/page/2/
> Your script for previous page when on page 2 is broken.
> It links here https://18f.gsa.gov/blog// instead of https://18f.gsa.gov/blog/

**Comment by nkkl** [comment]
Looks like the issue is an extra / getting appended here: https://github.com/18F/18f.gsa.gov/blob/staging/blog/index.html#L60

**Comment by gboone** [comment]
That is indeed the problem. Looks like we just need to eliminate that trailing slash. I can't really tell how we're deviating from the docs on our implementation, I could be missing something. If you see room for improvement, though, let us know!

**Comment by nkkl** [comment]
Their docs have the slash embedded in the paginate_path:
`paginate_path: "/blog/page:num/"`

whereas we were calling it without the slash:
`paginate_path: "/blog/page:num"`

and then appending it on the page.

Thanks for committing a fix! 👍

**Comment by gboone** [comment]
Ahh, yes, I see it now. Good eyes! I'll add that to the commit.

**Comment by waldoj** [comment]
This issue has returned, just as described three years ago.

**Comment by Dahianna** [comment]
@apburnes can you take a look

**Comment by Dahianna** [comment]
Issue fixed thanks to @apburnes
