### ISSUE TITLE
Unicode error on homepage on Chrome for Android

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#1873]
![screenshot_20160901-200548](https://cloud.githubusercontent.com/assets/4592/18188385/b719ae80-707f-11e6-92e6-08e87b4229c2.png)

**Comment by konklone** [comment]
Another one lower down too:

![screenshot_20160901-200816](https://cloud.githubusercontent.com/assets/4592/18188393/d7ee5520-707f-11e6-910d-f03bc8c65518.png)

**Comment by gboone** [comment]
Apparently that is a `U+2028 : LINE SEPARATOR` and will be promptly removed.
