### ISSUE TITLE
Make a plan for updating the web design standards on a bi-monthly basis

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#1877]
From our CONTRIBUTING.md:

> Will update the WDS library when it publishes a change required by the site. Otherwise will update bi-monthly.

Though it probably isn't very difficult, we don't currently have a plan for actually doing it. Start the discussion here.

**Comment by coreycaitlin** [comment]
We did this in #2165, and I just added a reminder in Slack to do it again on March 1st. @gboone, does that seem like enough of a plan, or do you want to keep this issue open?

**Comment by coreycaitlin** [comment]
Closing this out — I think the Slack reminder is a good start here.
