### ISSUE TITLE
Automate JS linting

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#1879]
From our CONTRIBUTING.md:
> Should use the AirBnB linter configuration for JavaScript, if linting fails, it will also fail the tests, but not the build.

Like #1878 we'll want to do this as soon as we can but not without the appropriate staff to respond to errors that might get thrown by contributors.

**Comment by gemfarmer** [comment]
@gboone any objections to using [Hound](https://houndci.com)? I really like it for JS and CSS linting.

**Comment by gboone** [comment]
A bit late, but I'm pro-Hound and think it'd be great to get it integrated before we start shipping too much code. We've had it before and sorta started ignoring it because it'd flag problems we didn't create in that pull request and that we didn't have time to fix.

**Comment by gemfarmer** [comment]
Closed with #1905
