### ISSUE TITLE
Rotate frontpage hero image and content

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#1895]
On a regular basis, rotate the front page content to showcase a different product or initiative we are working on. 

We've talked about rotating every three weeks but we could rethinking that timing based on user needs or usability testing results.

**Comment by awfrancisco** [comment]
Potential projects and tag lines [here](https://docs.google.com/document/d/1_2sA8ybYlxUrJLF6aXLNlH0mUiXvHKpcDvDjilOjyow/edit).

**Comment by ericronne** [comment]
Added myself here! In a sense, i suppose this issue is blocked by further hypothesizing, to confirm that this unit does indeed seem promising.

**Comment by coreycaitlin** [comment]
Created issues #1952 and #1953 to break out next steps

**Comment by coreycaitlin** [comment]
Closing this out in favor of more detailed issues!
