### ISSUE TITLE
When saving the 18F site as a favorite (eg in iphone), the icon should be the 18F logo

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#1898]
Previously the new, black 18F logo appeared when saving the site as a favorite, at least on iphone. This was the correct behavior.

Now it's a pixel-art flag. Is this intentional? ....

![image](https://cloud.githubusercontent.com/assets/9259185/18557134/5293fa56-7b33-11e6-8596-c56f8e675196.png)

**Comment by gboone** [comment]
Huh. Something must be up with the favicons, that is not intentional.

**Comment by jeffhou** [comment]
This seems to require adding html tags like this:
`<link rel="apple-touch-icon" href="/custom_icon.png">`.

Relevant link: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Interesting and somewhat relevant note: There is a folder full of the flags icon labeled as favicons https://github.com/18F/18f.gsa.gov/tree/master/assets/img/favicons.

(Sorry if I'm posting incorrectly. First time trying to help an open source project outside of class.)

**Comment by gboone** [comment]
Thanks for the pointers, @jeffhou, this is good evidence. I think we'll have someone taking this on soon.

**Comment by coreycaitlin** [comment]
Closing this out, because YAY
