### ISSUE TITLE
Add visual examples to What We Deliver

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1907]
As someone who promotes example of 18F's work, I'd like the [What We Deliver page](https://18f.gsa.gov/what-we-deliver/) to have screenshots of some of our products. I believe this would give new visitors a better understanding of our work and help sell our services to potential federal partners. Definitely needs research. 

A (likely outdated) batch of product screenshots [lives here](https://drive.google.com/drive/folders/0Bwoee0Kd0n28bEpkNTZBNlBxMnM). Intake has some [here](https://pages.18f.gov/intake/past-work/)

**Comment by coreycaitlin** [comment]
Closing this out in favor of #2040, #2070, and project-tag pages. The `What We Deliver` page with links to project pages will eventually include a teaser image for each.
