### ISSUE TITLE
Refine workflow and associated documentation

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1914]
- [x] refine server and build scripts
  - Currently site developers are either using the following commands to serve the project locally:
    - `bundle exec jekyll serve`: this does the trick, but is long, and rebuilds the `jekyll-archives` entirely, instead of incrementally.
    - `./serve`: shorter, and removes the `jekyll-archives` gem to avoid building or rebuilding archives. This works great for development, but has the unfortunate side-effect of modifying the `Gemfile.lock`.
- [x] add/edit server and build script documentation. Even if there are multiple ways to run the site, there should only be one method documented.
- [x] add/refine contributing documentation

**Comment by gemfarmer** [comment]
After giving this a little more consideration, I think that jumpstarting the site differently in development vs CircleCI/production shouldn't be an issue as long as the documentation prevents us from overwriting the `Gemfile.lock` every PR.

@gboone @mugizico does that make sense to both of you?

**Comment by gemfarmer** [comment]
We discussed forking the PR [here](https://github.com/jekyll/jekyll-archives/pull/58) for incremental jekyll archives builds instead of continuing to modify the build script.

cc @gboone

**Comment by gemfarmer** [comment]
Started working on [18F version of Jekyll archives](https://github.com/18F/jekyll-archives/). So far it isn't speeding up regeneration.

**Comment by coreycaitlin** [comment]
Blocked: waiting for response from the plugin developer.

**Comment by gemfarmer** [comment]
See #1849 for more info on why this is blocked

**Comment by coreycaitlin** [comment]
Closing this out — it's in much better shape! 🎉
