### ISSUE TITLE
Research: Summarize recent findings

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1917]

**Comment by coreycaitlin** [comment]
[Here is the summary](https://github.com/18F/18f.gsa.gov/blob/research/research/0-sprint/0-sprint-research-synthesis.md) (written by @jamiealbrecht)

**Comment by awfrancisco** [comment]
I thought the "Who receives the email when I write to the inquiries box?" and "Could you add an org chart or a note from the Executive Director?" feedback were really interesting. We had some info on the intake team on the intake site, but haven't replicated it for AP. I know there are issues with publishing the org chart, but some basics about main contacts and a note from Aaron are both interesting ideas.
