### ISSUE TITLE
Update contributing documentation

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1934]
We just had a workflow meeting and were met with the following PR rules that should be reflected in the docs

Loose PR rules:
- Don’t merge your own pull requests
- Squash your merges if there are many typo-style commits (docs on how to squash)
- Don’t merge until linters pass, unless reviewer passes on exceptions

**Comment by gboone** [comment]
#1957 was all that was left for this issue, correct? Feel free to reopen if there's more here.
