### ISSUE TITLE
Make jekyll-archives support incremental regeneration

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1949]
This issue is in conjunction with #1914, the issue that outlines how to improve our workflow.

One of the major snares to solving this issue is that [jekyll archives is not playing nice](https://github.com/18F/18f.gsa.gov/issues/1914#issuecomment-253879709). Switch between `./serve` and `bundle exec jekyll serve` is annoying and potentially causes Gemfile conflicts. To avoid this, we would need to fix `jekyll-archives` incremental regeneration feature as [@mnot tries to do here](https://github.com/jekyll/jekyll-archives/pull/58).

What has already been done:
- I started a new repo, 18F/jekyll-archives, that is a fork of jekyll/jekyll-archives
- I started cherrypicking changes from [mnot's PR](https://github.com/jekyll/jekyll-archives/pull/58) and adding them to a new branch, [`incremental-regeneration`](https://github.com/18F/jekyll-archives/tree/incremental-regeneration)

What still needs to be done
- [ ] make incremental regeneration work on that branch
- [ ] This can be tested by adding it to the 18F/18f.gsa.gov repo as a gem. Something like below should work
- [ ] make PR to `jekyll/jekyll-archives`

`gem 'jekyll-archives', :git => 'https://github.com/18F/jekyll-archives.git'`

cc @mugizico

**Comment by gemfarmer** [comment]
There is [movement on the jekyll-archives page](https://github.com/jekyll/jekyll-archives/pull/58#issuecomment-254405585)! This issue is tabled as we wait for those changes to roll in!

**Comment by gemfarmer** [comment]
Blocked until we jekyll-archives is updated!

**Comment by coreycaitlin** [comment]
Someday we should switch back to the fully-supported version of jekyll-archives — leaving this open as a reminder to check in occasionally to see if they've merged our fork.

**Comment by coreycaitlin** [comment]
IT HAS BEEN MERGED! https://github.com/jekyll/jekyll-archives/pull/58

**Comment by coreycaitlin** [comment]
Next step: combine changes on their gem with the changes made on our gem, and make sure everything still works.

**Comment by gemfarmer** [comment]
Working on this now. It works pretty well with the new version. It might be worth using this as an opportunity to cull or refine our build scripts (and related documentation)

### What we need
- [ ] Basic build – builds and incrementally regenerates everything
- [ ] Build without blog – builds the entire site minus the blog and search index
- [ ] Build for accesslint – build script that builds only portions of the site that accesslint needs to check (would include some blog posts as well as the search index)
