### ISSUE TITLE
Research: /open page to post documents and promote transparency

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1951]
Since publishing more documents and policies is one of Dave's [6 priority projects](https://gsa-tts.slack.com/archives/18f-management/p1476711451000298), it might be good to focus some time on research/brainstorming what a page would look like to highlight these documents. 

Draft hypothesis for this page:

**We believe that…**
- publicly posting important documents about how we work, our agreements with partners, and other transparency-focused documents
- will build trust among stakeholders, change the narrative to 18F being an open and transparent organization, and provide people with a better idea of what we do and how we do it.

We will know we are right when…
- press use the materials to write about 18F
- stakeholders turn to these documents rather than ask 18F for them
- people will use 18F as an example of a transparent government organization

**Comment by coreycaitlin** [comment]
Next step: I'll review related materials and discuss with @awfrancisco

**Comment by coreycaitlin** [comment]
Closing for now, but [noted in the wiki here](https://github.com/18F/18f.gsa.gov/wiki/What-we-would-like-to-do-someday#transparency-page-or-section
