### ISSUE TITLE
Homepage hero: Visual design concepts

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1952]
For our next iteration of the homepage hero space, we're going to try highlighting a few other projects. The next step is to begin exploring how to visually represent a few of the following projects:
- [x] FEC
- [x] cloud.gov
- [ ] Data Act
- [x] EITI
- [ ] ~Digital analytics program~
- [ ] ~Web Design Standards~

**Comment by ericronne** [comment]
@coreycaitlin do we know the publishing order for these? We should probably prioritize their production accordingly.

**Comment by coreycaitlin** [comment]
Let's prioritize less-meta projects for now, just for the sake of clarity.

**Comment by ericronne** [comment]
cc @austinhernandez :)

**Comment by coreycaitlin** [comment]
Closing this out for now, as we've shifted to a non-project approach to the homepage hero.
