### ISSUE TITLE
Summarize marketing and agency partnerships research

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1955]
This issue is for creating a summary of Outreach research to feed back into the site project.

**Comment by awfrancisco** [comment]
To clarify, this is for research for marketing materials, as opposed to the separate research on audiences and mediums that Outreach is doing as part of their strategic planning.

**Comment by awfrancisco** [comment]
Here's the [summary of marketing materials research](https://docs.google.com/document/d/1ynXKiw09sK8Mwnn0w0PQCevbFV0g0ysoJ2_MLj7eQ3k/edit#)

Next steps: Romke is mapping out a rough customer journey for potential partners. Then he is going to match up the research findings with different points along the journey to guide us in a plan for creating materials and process improvement. After we validate that plan with users, there are a couple possible places where this work will overlap with the site team. 

- Site content to speak to customers before they contact 18F
- Hire Us page content about the process for working with us
- Linked materials from Hire Us that explain more about the process (1 pagers, slide deck, IAA template, etc)

These are all just hypothesis at this point. Current plan is to expand the 18F group working on this after we validate this plan with users. 

@coreycaitlin Let's add this to our agenda for Wednesday.

**Comment by coreycaitlin** [comment]
This is great! Thanks @awfrancisco — closing this out now.
