### ISSUE TITLE
Summarize user interviews from Sprint Karst-Caves

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1956]
Create a summary of findings from the last few weeks of user interviews.

**Comment by jamiealbrecht** [comment]
Working on this here: https://github.com/18F/18f.gsa.gov/blob/research/research/1-sprint-karstcaves/1-sprint-research-synthesis.md

**Comment by coreycaitlin** [comment]
Closing this out! I think it's done 🎉
