### ISSUE TITLE
Create content linter

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1960]
It would be great to have a CI tool that would lint content in the 18f site repo on a push or PR basis. Linting content would allow us to 
- flag incendiary or harmful language
- create consistency in language used throughout the repo
- unburden outreach. Blog contributors will be told what language is ill-advised before the outreach team needs to get involved
- a CI tool would enable this tool to be applied to other 18F repos, creating org-wide consistency
### Background

This was @coreycaitlin's idea, and she has already begun work on creating rules that can inform the node module [`retext`](https://github.com/18F/retext-18f). 
### Research

As it stands, `retext-18f` is very capable of scanning a repo and flagging unwanted language. The problem is that running the associated CLI commands before pushing is cumbersome, and won't be done consistently without significant oversight. For this reason, it we decided that a @houndci-bot like commenting engine is going to be the best way to enforce our rules.
### What has been done

I started a small rails app to test receiving and making sense of github push and PR notifications.
I have concluded that because Octokit and retext are both available as node modules, creating a simple node API is going to be the least-path-of-resistance for tackling this problem. If all goes well, the app could be given a front end and configured in a GUI fashion. For now though, let's just focus getting push and PR webhooks to trigger comments that flag lines with unwanted language!! 😁 
### This is done when
- [ ] a content linter has been added to this repo
- [ ] it leaves comments on a push or PR basis
- [ ] outdated comments are removed

**Comment by gemfarmer** [comment]
Follow this work at the following repos:
- [gemfarmer/github_webhook](https://github.com/gemfarmer/github_webhook/)
- [18f/retext-18f](https://github.com/18F/retext-18f/)
- [unpushed changes to 18f/content-linter](https://github.com/18F/content-linter/)

**Comment by awfrancisco** [comment]
I know there's already been a fair amount of work on this, but I wanted to flag the [Rorybot](https://github.com/Shopify/rorybot) from Shopify as a similar tool that we might be able to learn/steal from.

**Comment by lsgitter** [comment]
not a priority at the moment. Will come back when we have more resources. We should ask a developer how many resources this will take
