### ISSUE TITLE
Wireframe project-tag landing page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1963]
Create a wireframe for a lightweight "project page" that rolls up all blog posts associated with a given project.

**Comment by coreycaitlin** [comment]
@ericronne Here's my "sketch" of what kind of intro we'd need at the top of these pages. A few other notes on this:

- We could think about stripping back the blog-post snippets so there's isn't quite so much metadata competing for attention on this particular roll up page: we may not need all tags to show up in this context, we might be okay without author names here, and we could consider dropping date as well (though that's the one I feel most ambivalent about)
- We want this page to work even if there's only one or two blog posts about a project
- This content is very much placeholder-y, and we can play with the headers and the shape of the content as needed.

<img width="510" alt="screen shot 2016-10-20 at 11 23 08 am" src="https://cloud.githubusercontent.com/assets/1450354/19566308/ce9b53ca-96b7-11e6-9eae-0c0ed5da175c.png">

**Comment by ericronne** [comment]
At a glance, the only thought i have is to add the home-page hero image at the top. This should serve as a nice cognitive link between the home hero and this page.

![image](https://cloud.githubusercontent.com/assets/9259185/19605509/1027ef9c-9780-11e6-8f51-69f03497cd61.png)

**Comment by coreycaitlin** [comment]
What do you think about trying something that brings down the unreadably long line-length of that intro?
