### ISSUE TITLE
Homepage hero: Cloud.gov design

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#1966]
Part of epic #1952

**Comment by ericronne** [comment]
Text isn't yet written for this one, but here's a design based on Ryan Thurlwell's always-brilliant work, from when he was on the cloud.gov team (before @thisisdano took over). Please feel free to let us know if you think think this serves as a good teaser for this project, @rtwell / @thisisdano, and @coreycaitlin when you have text, i'll drop it in.

cc @gboone 

## Cloud.gov hero
![hero-cloud](https://cloud.githubusercontent.com/assets/9259185/19626926/a9f45890-9901-11e6-9b21-a73ea080ee39.png)

**Comment by awfrancisco** [comment]
cc @jameshupp @nickykrause for cloud.gov messaging/marketing.

**Comment by nickykrause** [comment]
hello! @awfrancisco Did you mean to mention me?

**Comment by awfrancisco** [comment]
Whoops, sorry! I meant @nikzei.

**Comment by jameshupp** [comment]
I talked to @coreycaitlin offline about content related to this last week. Lemme know if the notes from that are enough to produce a good line here. If not, we can work through those together to get to something.

**Comment by thisisdano** [comment]
I think this is good enough to move forward — and is acceptable as is. We're working on some tweaks to the overall aesthetic, but this still communicates the idea well.

My only design comment is that the red icon fade makes them feel a bit soft.  And maybe gives the icons an implied hierarchy of importance? What would it do to the composition if the red icons were all the same transparency?

**Comment by ericronne** [comment]
@thisisdano sure, that's a viable option. Here's how it looks with icon hex's at full alpha. I've reduced the brightness of the red, to minimize the vibration that rears its head when we have this much of that color in play...

![hero-cloud-no-ghost](https://cloud.githubusercontent.com/assets/9259185/19659843/1d2d5aa4-99f3-11e6-8ef8-11750483794f.png)

**Comment by thisisdano** [comment]
Ahh, the ol' vibration. It does look funny. Maybe we can switch to blue on white, make the icon strokes a bit fatter, and pump up the blue saturation for punch. (`#056DD4` is our current blue, but I don't think it _needs_ to match — whatever looks good!)

Thanks for your effort on this! I think it doesn't really need much, if any, more work. I'd be comfortable with anything you like. The first one you posted was acceptable as well :)

- - - 

![cg-page-sketch](https://cloud.githubusercontent.com/assets/11464021/19660588/4cd82f30-99e5-11e6-82ff-cac65ee0cc90.png)

**Comment by ericronne** [comment]
Yep, sigh. I think it should coordinate with whichever flavor of the look is live at the time we run it. Is the site scheduled to be updated with that new, flatter look @thisisdano?

**Comment by thisisdano** [comment]
It is — sometime in the next week or so — but I don't think it meeds to match exactly. Close is fine. Probably any new look will change, too, so just capturing the general themes is ok.

**Comment by ericronne** [comment]
Cool. This likely won't be posted for about a month. FEC is on deck, and will remain the sole hero tout for a month or so. thx

**Comment by ericronne** [comment]
Ok, i moved the "gov" icon into the next-to-largest position, increasing its opacity in the process. Here's the image, and a gif demo of its responsiveness. Also, it works great as an svg, weighing in at a feather-light 9k!

[### Here's the svg file.] (https://drive.google.com/open?id=0BwWYNZcEDfwaMGZFZGtfNlRKZXM)

![image](https://cloud.githubusercontent.com/assets/9259185/19740373/1d1f8e46-9b84-11e6-977e-4c8649e5b031.png)

![3yw1vw3rmo](https://cloud.githubusercontent.com/assets/9259185/19740397/2f01bc42-9b84-11e6-9b67-f72cc39f8698.gif)

**Comment by coreycaitlin** [comment]
Looks gorgeous! Moving this back to the backlog, since we're starting with FEC — but we'll need this in the hopper soon.

**Comment by coreycaitlin** [comment]
Closing this out, since we're moving away from featured projects in the hero space. Still relevant for #2068 though!
