### ISSUE TITLE
Create project-tag landing pages

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1968]
We'll need a way to have special tag-rollup pages for a few specific projects, probably starting with FEC and cloud.gov.

**Comment by coreycaitlin** [comment]
#1963 and #1967 are related

**Comment by coreycaitlin** [comment]
Notes:

- In some cases, the blog posts tagged with a project name are a little scattered — we may need an additional way to note in blog metadata whether the post should appear on project rollup pages
- We may also need to review some blog-post metadata to make these rollups make more sense

**Comment by coreycaitlin** [comment]
Design looks awesome! see #1975

**Comment by ericronne** [comment]
Note that all "Continue >" links on this page (and sitewide) should be **bold**. The design doesn't reflect that.

![image](https://cloud.githubusercontent.com/assets/9259185/19866832/a4278e0e-9f6f-11e6-81d2-b5d4c18cf5ac.png)

**Comment by coreycaitlin** [comment]
For our initial take on this page type, let's focus on the main posts — we'll need a little more taxonomy work to handle the lower "related posts" section, so we can break that out as a separate issue once we have the core of the page built.

**Comment by ericronne** [comment]
Like so? (from #1975 ;) ) ...
![image](https://cloud.githubusercontent.com/assets/9259185/19980535/6e8388ac-a1cc-11e6-898d-5e4f0ba9f517.png)

**Comment by coreycaitlin** [comment]
@ericronne Yes! Do you feel strongly about including the "latest news from 18F" mini-footer?

**Comment by ericronne** [comment]
Not at all. Kill it.
