### ISSUE TITLE
Visual design: project-tag landing page

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#1975]

**Comment by ericronne** [comment]
based on #1963

**Comment by ericronne** [comment]
Here's a design, along with an annotated with type specs and spacing. Comments welcome!

Note for @gemfarmer: don't sweat the annotations too much for the initial prototype. Instead use the current assigned values for spacing, font sizes &c. *Do* note the font color specs, though, if you would.

I'll create the header asset next. Thx!

## Project-tag landing page
![project](https://cloud.githubusercontent.com/assets/9259185/19703989/982b69e8-9acb-11e6-9e88-6c4df4a2329d.png)

## Style annotations
![project-spec d](https://cloud.githubusercontent.com/assets/9259185/19704021/b00e052a-9acb-11e6-8fc6-6f1f9f17b0d0.png)

**Comment by coreycaitlin** [comment]
Closing this out as we move into implementation!
