### ISSUE TITLE
Missing javascript file

### ISSUE THREAD

**Issue by hursey013** [18F/18f.gsa.gov#1979]
## Expected Behavior

To have all referenced assets load properly
## Actual Behavior

`https://18f.gsa.gov/assets/js/search-bundle.js` returns a 404 error on page load.
## Steps to reproduce the behavior
- Visit https://18f.gsa.gov/
- View console or network tab in browser developer tools to view error
## This is issue is done when:
- All assets are found, or removed if unnecessary.

**Comment by coreycaitlin** [comment]
This seems to have been resolved with a Federalist fix that also fixed search.
