### ISSUE TITLE
Typography: consider increasing paragraph size

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#1982]
Does the site body text feel small to you? What if we up-sized it a little (perhaps by only one pixel, to 1.8rem), and did some A/B testing? Here's a preview image, which also reflects the anti-aliasing change requested in issue #1981 (click image to view) …

![image](https://cloud.githubusercontent.com/assets/9259185/19746076/5901966e-9b9a-11e6-9dcb-35fa557d055e.png)

@awfrancisco @gemfarmer @coreycaitlin @elainekamlley @gboone @jamiealbrecht @mugizico

**Comment by coreycaitlin** [comment]
I fully support embiggening the text, and I kind of did it in #1985.
