### ISSUE TITLE
Add alums to site

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1987]
Extension of #1984
## Expected Behavior

Adding `alumni: true` to any markdown file in the _authors directory adds some sort of flag to the authors page
## Actual Behavior

This doesn't happen!
## Steps to reproduce the behavior
- [ ] Determine who is an alumni in our list of authors
- [ ] Add `alumni: true` to their md files
## This is issue is done when:
- [ ] All alumnis have an associated alumni attribute
- [ ] It flags alumni on the site
- [ ] All authors listed in `_data/authors.yml`  have an archive page properly marked with alumni status (Ideally, we can delete that file, too.)

@coreycaitlin @gboone @awfrancisco

**Comment by gboone** [comment]
Added a checkbox to the acceptance criteria.

**Comment by coreycaitlin** [comment]
See #2021 and #2018 for continuing work.
