### ISSUE TITLE
Revisit automated accessibility scanning

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1993]
## Expected Behavior

We would like an accessibility tool that runs on Circle on a build basis when a pull request is submitted.
## Actual Behavior

The accessibility linter that is currently in place runs well, but takes too long, and occasionally gets hung up checking URLs that aren't built.
## Things to watch/do
- [USWDS is looking into adding accesslint](https://github.com/18F/web-design-standards-docs/pull/45) to their site. I'm excited to see what they discover
- Consider modifying accessibility scanner to only check pages pertinent to a given PR
- Consider modifying accessibility scanner to leave github comments
- Look into [accesslint](https://github.com/accesslint/accesslint-ci)

**Comment by coreycaitlin** [comment]
This is done with #2134
