### ISSUE TITLE
Create a basic sketch style guide

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#2000]

**Comment by austinhernandez** [comment]
hey @gemfarmer here's a list of some issues I found while going through the site. (I'll keep adding to this list):
- active state on .usa-button-secondary (button in the hero section) is red and inheriting from USWDS (#981b1e)

**Comment by coreycaitlin** [comment]
Next step: @austinhernandez + @gemfarmer to meet and discuss.

**Comment by coreycaitlin** [comment]
After discussing, we've broken this out into #2088 and #2089.
