### ISSUE TITLE
Homepage hero: EITI design

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#2002]
Part of epic #1952

**Comment by ericronne** [comment]
Okay! Here's a draft for this sucker. Kept it simple, but hopefully interesting. Since geography and land ownership are so fundamental to EITI, i started with the ownership map as the base. (Also, maps are visually interesting :) I overlaid the oil icon to strongly hint at the general space this site deals with. Finally, the offshore area is featured. Users may well be unaware of what this represents, which will hopefully add to their curiosity.

## EITI hero
![hero-eiti-situ](https://cloud.githubusercontent.com/assets/9259185/19939547/807e2506-a0f7-11e6-8c20-a5949b2261ca.png)

## In action
![plcnq0rswe](https://cloud.githubusercontent.com/assets/9259185/19939554/8bd2f01c-a0f7-11e6-83e2-3c8b64916503.gif)

@coreycaitlin 

cc @gboone

**Comment by ericronne** [comment]
Scratched my head a little more. This version seems to communicate a little more clearly. It focuses on the gulf of mexico, which is frankly the most interesting region from an extractives standpoint. Also shows actual data....

## EITI hero alt
![hero-eiti](https://cloud.githubusercontent.com/assets/9259185/20064803/911b7d40-a4d1-11e6-8f37-6fd670420f2c.png)

## In action
![kvkpmnmqtz](https://cloud.githubusercontent.com/assets/9259185/20064831/a7737890-a4d1-11e6-9041-f30ec5b9f1bf.gif)

@coreycaitlin 
cc @gboone

**Comment by coreycaitlin** [comment]
Next step: design files!

**Comment by ericronne** [comment]
### [Converted to svg!](https://drive.google.com/open?id=0BwWYNZcEDfwaR2w1cy1RNVdsYk0)

@coreycaitlin @gemfarmer
