### ISSUE TITLE
Author links broken

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2009]
## Expected Behavior

From any blog post author list, clicking on an author's name should take the user to a URL like `https://18f.gsa.gov/author/christopher-goranson`

## Actual Behavior

Instead, that link is being redirected to a URL like `https://18f.gsa.gov/site/18F/18f.gsa.gov/author/christopher-goranson/`, which 404s.

## Steps to reproduce the behavior
- [ ] [Go here](https://18f.gsa.gov/2016/10/26/writing-for-web-easy-writing-for-users-not/)
- [ ] Click on an author's name

Note: these links work locally AND in Federalist previews for the dev branch, which is why we didn't catch this. I suspect this has to do with how we're handling the baseurl?

## This is issue is done when:
- [x] Author page links work

**Comment by mugizico** [comment]
I am trying to reproduce the behavior but the `Go here` link and clicking the author's name  is actually taking me to `https://18f.gsa.gov/author/christopher-goranson`

**Comment by coreycaitlin** [comment]
Yay! This seems to be fixed with #2010 — closing out the issue.

**Comment by coreycaitlin** [comment]
Reopening because this has recurred somehow 😕

**Comment by coreycaitlin** [comment]
As far as I can tell, this is fixed with #2041 🎉
