### ISSUE TITLE
Solidify grid system

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#2013]

**Comment by austinhernandez** [comment]
grid system is a WIP here on invision -https://invis.io/PK9JJOTQE
- I'm thinking this is blocked until we get solid IA and content
- Meeting with @gemfarmer to discuss specific requirements of visual elements
-- Does it make sense to create a UI pattern library that copies the USWDS?
- Sketch file here https://drive.google.com/open?id=0B0ppzHnivtsDV3g4V1FBZ0FOTzA

**Comment by coreycaitlin** [comment]
We're solving this in #2089 — closing this issue out.
