### ISSUE TITLE
Redirect /consulting to /what we deliver

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2017]
## Desired Behavior
When someone goes to https://18f.gsa.gov/consulting/ they are redirected to  https://18f.gsa.gov/what-we-deliver/ 

## Actual Behavior
https://18f.gsa.gov/consulting/  is linked to from many places outside of 18F or GSA control, but currently 404s

Request is from @quepol https://gsa-tts.slack.com/archives/18f-site/p1478145427000169

**Comment by mugizico** [comment]
it looks like `https://18f.gsa.gov/consulting` is hard-coded(instead of `/consulting`) in posts in which it is reference. This is going to make it difficult to test locally with localhost

**Comment by mugizico** [comment]
so after looking at, and trying to use the [ jekyll-server-redirects](https://github.com/borfast/jekyll-server-redirects) gem and the [jekyll-pageless-redirects](https://github.com/nquinlan/jekyll-pageless-redirects) plugin  to no avail, I am almost inclined to just change the `https://18f.gsa.gov/consulting` to `https://18f.gsa.gov/what-we-deliver` in affected `.md` files(about 15 of them).  thoughts @awfrancisco ?

**Comment by gboone** [comment]
The way we've done redirects in the past was to use [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) by creating a page for the endpoint that needs to redirect (/consulting) with the `redirect_to` frontmatter set to the target page.

**Comment by gemfarmer** [comment]
@mugizico I have time to work on this today, if you'd like!

**Comment by gboone** [comment]
I think this was closed with #2029

**Comment by gemfarmer** [comment]
Ah, you're right!
