### ISSUE TITLE
Project page: EITI/Revenue data

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2022]
We need content for both the homepage and the project-tag landing page when we're ready to feature USEITI on the homepage.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by Michelle H

**Comment by coreycaitlin** [comment]
See #2002 for design!

**Comment by coreycaitlin** [comment]
[Draft here (limited access)](https://docs.google.com/document/d/1nVyNT8jWg9W37W092ehoL7DGln0BOrvTEbxS73zYR6Y/edit

**Comment by awfrancisco** [comment]
@elainekamlley ready for markdown and publishing

**Comment by awfrancisco** [comment]
Let's hold off on this one for now.

**Comment by awfrancisco** [comment]
@coreycaitlin what do you think about this one? Even if the US is still leaving EITI, would it still be good to go forward with highlighting this work?

**Comment by coreycaitlin** [comment]
Yes, it would be great to highlight this work! We might want to reframe slightly from our prior draft, though — let's revisit in July?

**Comment by awfrancisco** [comment]
sounds good

**Comment by eddietejeda** [comment]
Took a stab at it. We're going to remove the quote for now. We can add it later.

**Comment by eddietejeda** [comment]
@hannahkane can you review? https://docs.google.com/document/d/1nVyNT8jWg9W37W092ehoL7DGln0BOrvTEbxS73zYR6Y/edit

**Comment by hannahkane** [comment]
@eddietejeda - added some suggestions. Do you want to take another pass?

**Comment by eddietejeda** [comment]
looks good. @Dahianna?

**Comment by Dahianna** [comment]
Looks good! We're just missing the title, subtitle and excerpt.

**Comment by eddietejeda** [comment]
@Dahianna will convert to Markdown and publish when ready.

**Comment by Dahianna** [comment]
https://18f.gsa.gov/what-we-deliver/onrr-data-site/
