### ISSUE TITLE
Create subnav and simplify nav management

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2023]
We have several sections of content that will need sub-navigation when we migrate them into the site proper (including Join 18F and the Partnership Playbook).

This issue is for implementing the design from #1954

**Comment by coreycaitlin** [comment]
Blocked for implementation until we have the mobile design.

**Comment by gemfarmer** [comment]
@ericronne is it fair to say that the mobile design is good to go? It sounded like we were just going to bootstrap with the USWDS

**Comment by coreycaitlin** [comment]
Mobile design is in #2030 🎉 

Let's start with the simplest option here (i.e. WDS).

**Comment by coreycaitlin** [comment]
Outstanding question: should this be a series of pages, or one long-scroll page?

**Comment by coreycaitlin** [comment]
I've done a cursory content inventory, and I think our instinct that this should be a series of separate pages was the right instinct. Let's treat this as a traditional group of pages, rather than a single long-scroll page.

**Comment by coreycaitlin** [comment]
Changed the title to reflect refactoring that needs to happen here

**Comment by coreycaitlin** [comment]
Closing this out, now that we have subnav capabilities! We'll create a separate issue for pulling in content once we have our first section ready.
