### ISSUE TITLE
KuriousKettle user research

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2024]
## This is issue is done when:
- [x] we have a [research plan](https://github.com/18F/18f.gsa.gov/blob/research/research/3-sprint-kuriouskettle/kuriouskettle-research-plan.md)
- [x] we have a research script — see above! Same script, new content
- [x] we've recruited/scheduled 3-5 users
- [x] we've interviewed 3-5 users

**Comment by gemfarmer** [comment]
@coreycaitlin I can help out with user research!!
