### ISSUE TITLE
Deprecate "description" in post frontmatter

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2032]
`Description` and `excerpt` seem to be duplicate fields in many, many cases. Using one field instead of two will simplify the blog posting template slightly and make it a little easier to maintain.

## This is issue is done when:
- [x] We've changed the post metadata to use the excerpt
- [x] The blogging guide is updated

**Comment by gboone** [comment]
@gemfarmer and I are pretty sure #2041 addressed this but there's still work to be done updating docs. Is that accurate, @coreycaitlin?

**Comment by coreycaitlin** [comment]
I think it got lost, actually — I'm still seeing the `head` look for `page.description` when it should be grabbing `page.excerpt`. Trying again!

**Comment by coreycaitlin** [comment]
Okay, I've also set up a PR in the blogging-guide repo that makes the documentation changes I'm aware of. Let me know if there are other spots we should note this.

**Comment by gboone** [comment]
I can update the blog README; I think that's the only place left.
