### ISSUE TITLE
Concepts: What we deliver page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2040]
Our current `What we deliver` page is mostly text-based and organized roughly by business unit — we've heard from users that they'd like to see more clear examples of how we've helped other agencies.

This issue is for creating some concepts, based on the Web Design Standards, for how to show a few projects. Each project would link to a project tag rollup page, ala [FEC](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/project/fec-gov/).

**Comment by ericronne** [comment]
We don't currently have a "portfolio" or much in the way of case studies. Would be great if this section started to include some of that kind of action! :)

**Comment by awfrancisco** [comment]
We've certainly heard some requests for case studies in user research. It's possible some blog posts could be edited or combined into a case study or two.

**Comment by coreycaitlin** [comment]
Marking as blocked until we have some content to work with here.

**Comment by coreycaitlin** [comment]
Focusing elsewhere for a sprint or two!

**Comment by austinhernandez** [comment]
somewhat related to what we deliver is a rethinking of the navigation inside the project page (which will lead back to this page) - https://invis.io/3X9J87M4V#/210062112_Project_Detail_V1

**Comment by austinhernandez** [comment]
"What we deliver" page mockup - https://invis.io/3X9J87M4V#/211054680_What_We_Deliver_V1

**Comment by coreycaitlin** [comment]
Handing off to #2070 🎉
