### ISSUE TITLE
Improve core call-to-action

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2067]
Right now, the email link is a bit hidden at the end of the "Hire 18F" page — this link is our core call to action, and the only way for someone to take the next step toward hiring us from the website.

We should make this link (or CTA) bigger and easier to use.

- ~We could consider using a simple form instead of an email, if it would be useful to get a bit more info~
- [x] We should come up with some way to track which emails are from the website
- [x] We've heard from users that they'd like to know who they're emailing and what to expect

**Comment by coreycaitlin** [comment]
Started content work on `hire-rewrite` branch

**Comment by gemfarmer** [comment]
What I learned from the [#research slack channel](https://gsa-tts.slack.com/archives/research/p1481128329000078):

- Using a third party services to handle the forms is fine, but two main conditions need to be met
  - We need to be able to ensure that only government employees (contractors are not employees) can use the intake form. Client-side validation is secure enough for this kind of form
  - We need to be sure that PII is handled securely with whatever service we use

Where does this leave us with the proposed third party services/approaches?
- Formspree
  - [ ] Likely not secure enough
  - [x] Can screen for only .gov/.mil employees
- Formkeep
  - [ ] Likely secure, though it costs $
  - [x] Can screen for only .gov/.mil employees
- Google Form
  - [ ] Secure
  - [x] Can screen for only .gov/.mil employees ([Google has regex field validation](https://support.google.com/docs/answer/3378864?hl=en))
  - [ ] Making it fit within the theme of the site could be difficult
    - http://morning.am/tutorials/how-to-style-google-forms/
    - Might be against Google's terms of service: https://productforums.google.com/forum/#!topic/docs/6O0P4ufLVjU

**Comment by coreycaitlin** [comment]
We're simplifying this and solving the above issues by:

- Adding a subject line and simple template to the `mailto` link, so users have a little more help giving us the right information when they reach out
- Noting who they'll be reaching out to

Still to do:

- [ ] Revisit CTA copy on the homepage

**Comment by coreycaitlin** [comment]
@gemfarmer What's the right branch (most recent branch with the new homepage structure and CTA) for me to make these changes on?

**Comment by gemfarmer** [comment]
@coreycaitlin that would be `our-work`

https://github.com/18F/18f.gsa.gov/pull/2150
https://federalist.18f.gov/preview/18F/18f.gsa.gov/our-work/

**Comment by coreycaitlin** [comment]
New words (as well as alternate words, commented out) are here: https://github.com/18F/18f.gsa.gov/pull/2150

Closing this issue out for now, since we can pick up feedback on that branch/PR.
