### ISSUE TITLE
Content: State & local intro section

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2069]
We need content for the project-tag landing page about state & local projects.

This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by project SMEs

**Comment by coreycaitlin** [comment]
Let's start by focusing on our work with one federal agency across states.

**Comment by awfrancisco** [comment]
We should consider about how much we want these pages to be blog focused or also include both other related resources about a project (modularcontracting.18f.gov in this case) and contact or selling information. Anticipating that this might be an ask from project teams.

**Comment by coreycaitlin** [comment]
Next step: Share latest with HHS/State and local team
