### ISSUE TITLE
Content: What we deliver page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2070]
This issue is for revised "what we deliver" or "our work" content - see also #2040

**Comment by coreycaitlin** [comment]
Pushing out a sprint to focus on launching some other chunks of content.

One option when we pick this up again: start by focusing on problem-groupings rather than solution-groupings. From @gboone:

> We solve problems like automating manual processes (CALC, C2), implement laws and mandate (DATA Act, College Scorecard, US EITI), and executing mission critical tasks (FEC, e-regs)

**Comment by coreycaitlin** [comment]
See concepts in #2040 — next step, more solid content.

**Comment by awfrancisco** [comment]
I'll work on drafting a 3 buckets and a 0 buckets version of the content.

**Comment by awfrancisco** [comment]
Both versions are ready for a look [here](https://docs.google.com/document/d/1ekT2hP5zZ000RBgIZ01GLM0fBWSBxf5LAgVdkt0GZ48/edit#)

**Comment by coreycaitlin** [comment]
This is good to go as source content once we start building out this page!
