### ISSUE TITLE
Wireframe + design: Homepage reorg

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2080]
Our homepage structure [isn't quite working](https://github.com/18F/18f.gsa.gov/blob/research/research/3-sprint-kuriouskettle/kuriouskettle-research-results.md#say-who-we-are-first-and-feature-several-projects-instead-of-one) — users get confused by the single featured project, and are eager to learn about who we are. Let's try flipping the order of the two first chunks of information on the homepage, and lead with "what we are".

First step: content + wireframe

**Comment by austinhernandez** [comment]
WIP concepts on invision - https://invis.io/4U9JJB22E 

- comments enabled
- content & images are mostly placeholder

**Comment by austinhernandez** [comment]
MVP styles here & handoff to @gemfarmer https://invis.io/3X9J87M4V#/209522573_Home_Mvp

**Comment by coreycaitlin** [comment]
After all our conversations last week, the priorities are:

- Getting an intro sentence into the hero space
- Featuring 2 projects on the homepage
- Adding a call to action that links to the the `Hire`/`Contact` page

We're leaving a few things alone:

- Nav
- Footer
- Featured blog posts

**Comment by coreycaitlin** [comment]
Draft from @gemfarmer is here: https://federalist.18f.gov/preview/18F/18f.gsa.gov/homepage-update/

**Comment by coreycaitlin** [comment]
Next steps:

- Share this around and get feedback (internally)
- See if we can get a few brief usability tests on the new order of items
- Explore visual (probably graphic, not photo) elements for the hero

**Comment by coreycaitlin** [comment]
Before testing, this page needs the following content elements:

- [ ] State & local teaser content (see #2069)
- [ ] Hero image for state and local feature
- [ ] Eliminate minor intro-content redundancy
- [ ] Copy for call-to-action at the bottom of the page

**Comment by coreycaitlin** [comment]
Remaining work:

- [ ] Refine hover and link styling #2103

**Comment by coreycaitlin** [comment]
Next step: refine the homepage design so that it...

- Includes an image in the hero space
- Has a header + brief body text in the hero space
- Has clearer section breaks between sections

Then, share the latest design + content with @smils and @gboone before launching.

**Comment by coreycaitlin** [comment]
Next: Schedule pairing time to implement and experiment with these changes

**Comment by coreycaitlin** [comment]
WOOT WOOT @austinhernandez designed this awesomeness, let's implement it! 🎉 

![screen shot 2017-01-06 at 9 27 21 am](https://cloud.githubusercontent.com/assets/1450354/21726580/3c1906d2-d3f2-11e6-8ab8-f0100ce438dd.png)

@austinhernandez can you add any source files @gemfarmer will need to get this built? and start thinking about how it will look on mobile?

**Comment by gboone** [comment]
LET'S DO IT!

**Comment by gemfarmer** [comment]
Rearing to implement this. To what @coreycaitlin said, @austinhernandez where is the link to the latest version that I should work from?

**Comment by austinhernandez** [comment]
@amberwreed suggested we hold off for a bit for refinement. The concern is that this is off-brand and needs some polish before it's ready for primetime. Working with her right now.

**Comment by coreycaitlin** [comment]
Update! newer fancy business:

![screen shot 2017-01-11 at 1 41 32 pm](https://cloud.githubusercontent.com/assets/1450354/21869959/ef03b3c6-d80e-11e6-96d8-f15a906b013c.png)

**Comment by austinhernandez** [comment]
hai! here's the latest from amber and austin!

![1-12-16-homepage](https://cloud.githubusercontent.com/assets/23194720/21906089/d69a2d1e-d8d7-11e6-9391-27870833cee6.png)

**Comment by austinhernandez** [comment]
here is the latest version with margins (please note these will still be REM, but they are showing the relative heights between elements:
![1-12-16-homepage-margins](https://cloud.githubusercontent.com/assets/23194720/21906165/2dca3f8e-d8d8-11e6-96b3-2ef0e63702a2.png)

**Comment by coreycaitlin** [comment]
I am closing out this issue, team! If we have more specific refinements, let's issue them separately. 🥇
