### ISSUE TITLE
Code blocks not blocked, missing syntax highlighting

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#2083]
## Expected Behavior
Code blocks formatted with triple backticks should generate into code blocks
```json
  {
    "example": "Like this"
  }
```

## Actual Behavior
Code blocks are generated as single lines code:
`json { "example": "Like this" }`

Indenting every line in the block twice gets the desired monospace font in a block effect but syntax highlighting is still missing.

## Steps to reproduce the behavior
- [ ] Create a post or page and include a code snippet in a block like the one above
- [ ] Modify the block by indenting all lines twice; rebuild the site
- [ ] Alternatively, check [an existing post with code blocks](https://18f.gsa.gov/2016/08/25/micro-purchase-design-philosophy-do-one-thing-well/) to verify they are properly blocked and highlighted.
  Here are a few other examples:
  - https://18f.gsa.gov/2016/10/04/what-is-static-source-analysis/
  - https://18f.gsa.gov/2016/06/24/5-lessons-in-object-oriented-design-from-sandi-metz/
  - https://18f.gsa.gov/2016/04/08/how-we-get-high-availability-with-elasticsearch-and-ruby-on-rails/

## This is issue is done when:
- [ ] All existing posts with code blocks generate correctly
- [ ] All existing code blocks are properly syntax highlighted

**Comment by gemfarmer** [comment]
@gboone was this working before @mugizico and I joined? I'm mostly wanting to know if this is an existing bug or if changes that we made created this problem.

**Comment by gboone** [comment]
This was working as recently as the beginning of October when the ["What is Static Source Analysis"](https://18f.gsa.gov/2016/10/04/what-is-static-source-analysis/) post was published. It's possible syntax highlighting has been busted longer than that because that post doesn't have any highlighting.

**Comment by gemfarmer** [comment]
Hm ok. I don't doubt that some of the changes that were made to markdown rendering inadvertently caused this bug. 😞

**Comment by gemfarmer** [comment]
Testing how github renders codeblocks

```javascript
var hello = 'hello';

function(test) {
	return hello;
}

var hello = {
	"hello": "world"
}

```
