### ISSUE TITLE
Revert font smoothing from body text

### ISSUE THREAD

**Issue by maya** [18F/18f.gsa.gov#2084]
## Expected Behavior
No font smoothing. 

## Actual Behavior
Font smoothing

See: https://github.com/18F/web-design-standards/pull/53
http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

This was introduced in https://github.com/18F/18f.gsa.gov/pull/2049/files and can be removed. Anti-aliasing should only be used with light text on dark backgrounds.

**Comment by coreycaitlin** [comment]
The question: what's the right approach for light text on dark backgrounds?

**Comment by maya** [comment]
@coreycaitlin we should use font-smoothing on light text on dark backgrounds.

**Comment by coreycaitlin** [comment]
Solved! in  [release 1.1.3](https://github.com/18F/18f.gsa.gov/releases/tag/1.1.3)
