### ISSUE TITLE
/Developer page reference to FBOpen and Midas

### ISSUE THREAD

**Issue by lauraGgit** [18F/18f.gsa.gov#2096]
## Expected Behavior
Only see tools that are still available for developers

## Actual Behavior
Seeing links to deprecated projects such as FBOpen and Midas.

## Steps to reproduce the behavior
- [ ] Go to /developer
- [ ] Read down

## This is issue is done when:
- [ ] Those paragraphs are modified or removed

**Comment by coreycaitlin** [comment]
Let's remove these paragraphs for now!
