### ISSUE TITLE
Create build script for blog posts

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2099]
## Expected Behavior

We want to have a few different ways to build the site.

**`bundle exec jekyll serve`**: builds the entire site. Takes about 50 seconds
**`./serve`**:                             builds a pared down version of the site that excludes everything blog related
**`./serve-blog`**: builds a pared down version of the site that also includes the most recent few blog posts

## Actual Behavior

Right now we have two ways of building the site.

`bundle exec jekyll serve`: builds the entire site. Takes about 50 seconds
`./serve`: builds a pared down version of the site that excludes everything blog related

## Steps to reproduce the behavior
- [ ] create new script that is a duplicate of the `/.serve` script named `./serve-blog`
- [ ] make new config file that excludes all blog posts except the most recent.

## This is issue is done when:
- [ ] new blog posts can be displayed locally with significantly shorter build time by running the script

**Comment by coreycaitlin** [comment]
YAY thanks @gemfarmer 🎉
