### ISSUE TITLE
Project intro: College scorecard

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2104]
Format:

```
#Project: Agency name
## Tagline
Agency background sentence. Agency problem in 1-2 sentences.
## Approach statement
What we did first. What we did after that worked.
Wrap-up about the project being great or where we are now.

```

**Comment by awfrancisco** [comment]
Working on this [here](https://docs.google.com/document/d/1UbvlrYo0aJh1SwblrQF0EO5-OG7WJ6Fl0zsdMx8-ExI/edit) (limited access)

**Comment by coreycaitlin** [comment]
Got a 👍 from @meiqimichelle, though we should double-check the accuracy of the last sentence. @awfrancisco, do you know who would be able to weigh in on the Ed Digital Service?

**Comment by awfrancisco** [comment]
I'll work on that.

**Comment by awfrancisco** [comment]
Last sentence is cleared. This is ready to move forward.

**Comment by coreycaitlin** [comment]
Next step: move to Markdown file in `_projects` directory.
