### ISSUE TITLE
Project intro: Every Kid in a Park

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2105]
Format:

```
#Project: Agency name
## Tagline
Agency background sentence. Agency problem in 1-2 sentences.
## Approach statement
What we did first. What we did after that worked.
Wrap-up about the project being great or where we are now.

```

**Comment by awfrancisco** [comment]
Working on the draft [here](https://docs.google.com/document/d/1EbYPpv1ep_85jpye32lgwzsT9i1XG1ZEbJomK2rXv6Q/edit) (limited access)

**Comment by awfrancisco** [comment]
Text is done. Moving to markdown.

**Comment by coreycaitlin** [comment]
Once this is in dev, would be good to get a final a-ok from Emileigh or others from the team.
