### ISSUE TITLE
Some author pages are duplicates and include all posts

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#2110]
## Expected Behavior
Each author should have only one blog archive that displays only posts where they are a listed author. Any author listed in [`_authors`](https://github.com/18F/18f.gsa.gov/tree/master/_authors) who is not listed as an author should have an empty archive page or a 404.

## Actual Behavior
Some authors have a duplicate page that contain all posts in the site.

## Steps to reproduce the behavior
- [ ] Here are two example archives. [1](https://18f.gsa.gov/author/khandelwal/) [2](https://18f.gsa.gov/author/jayhuie/)
- [ ] For those authors [this is the correct archive for 1](https://18f.gsa.gov/author/shashank/) and the other should 404 or display a message saying that author hasn't written any posts.

## This is issue is done when:
- [ ] We've found all duplicate authors
- [ ] Archives show the correct posts.

**Comment by gemfarmer** [comment]
@gboone what is the first example? I don't see a link to it

**Comment by coreycaitlin** [comment]
You can find a bunch of these on this post and a few similar ones: https://18f.gsa.gov/2016/03/21/we-asked-100-of-our-coworkers-why-did-you-join-18f/

**Comment by gemfarmer** [comment]
So it looks like whenever there aren't any records for an 18f team member who has an author page, we have been showing all the records!!! BOOOOO! :ghost:
