### ISSUE TITLE
Write 18F experience principles

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2119]
We could use some experience principles to guide people who are communicating with our colleagues in government. Started drafting [here (limited access)]().

**Comment by coreycaitlin** [comment]
Reassigning to @awfrancisco, since you're working on it already!

**Comment by awfrancisco** [comment]
Adding the [draft doc](https://docs.google.com/document/d/1NpDbdto71wojuWYtLvTJyBXhRXc5f1ma2DxM6MGBTpI/edit). Previous link was back to this issue.

**Comment by gemfarmer** [comment]
@coreycaitlin: open for your review!

**Comment by coreycaitlin** [comment]
Now posted [here](https://github.com/18F/18f.gsa.gov/wiki/Experience-principles), thanks to @awfrancisco 🎉
