### ISSUE TITLE
Create 3-5 Homepage concepts for testing

### ISSUE THREAD

**Issue by austinhernandez** [18F/18f.gsa.gov#2123]
After meeting with Sarah Milstein she suggests brainstorming on 3-5 concepts with Outreach to test user comprehension of what 18F does. Working with "We work with federal agencies to approach technology projects in new ways."

Preliminary research our users respond best to messaging around how we help agencies succeed (currently learning more about  what are their goals, what is success for them, how do we help them meet their mission)

Suggestion: test graphics separately after a tagline is solidified as iconography and graphics are a different set of comprehension.

**Comment by austinhernandez** [comment]
@coreycaitlin here are 2 different designs with text on them for placement examples when you are thinking of tag lines for the homepage.
 
- v1 https://invis.io/a/BPC2FVY9ZCTUW
- v2 https://invis.io/a/6HC2FX94AFS7K

Here's an abstract background to add text on top of:
https://invis.io/a/KGC2FYIS9HR23

**Comment by coreycaitlin** [comment]
## Three options for tagline + brief intro

### Option 1

**We work with federal agencies to approach technology projects in new ways**

[shorter:
**We help agencies approach technology projects in new ways**
]

18F helps agencies improve processes and deliver efficient, easy-to-use digital services to the public.

As an office within the General Services Administration, we know how to work with government. All our projects support agencies in transforming how they deliver digital services and technology products.

### Option 2

**Building 21st century digital government**

18F partners with federal agencies to approach technology projects in new ways. We help agencies improve processes and deliver efficient, easy-to-use digital services to the public.

As an office within the General Services Administration, we know how to work with government. All our projects support agencies in transforming how they deliver digital services and technology products.

### Option 3

**Transforming how federal agencies deliver digital services**

18F partners with agencies to approach technology projects in new ways.

As an office within the General Services Administration, we know how to work with government. We help agencies improve processes and deliver efficient, easy-to-use digital services to the public.

-----

@awfrancisco thoughts? These feel like pretty subtle changes to me. Any ideas for more-different options that might help us answer more specific questions?

These options could potentially help us figure out:

- Whether `transformation` is resonant for users
- Whether `digital services` or `technology projects` makes more sense to users
- Whether people love the older `21st century government` tagline

**Comment by awfrancisco** [comment]
Thoughts in no particular order:

We could also test whether the "We help agencies" or "Helping agencies" construction is better. 
More specifically than whether `transformation` resonates with users, I'd like to explore whether federal employees find it offensive. Whether the idea that you need to be transformed is off-putting. 

Here's another tagline option. 
**Trusted partners in building a digital government**

I'll come back with some more thoughts tomorrow.

**Comment by coreycaitlin** [comment]
@awfrancisco Makes sense. If we could only test one at a time, which would you want to move forward with?

I think I like the first one, but with the shorter variant:

> **We help agencies approach technology projects in new ways**
> 
> 18F helps federal agencies improve processes and deliver efficient, easy-to-use digital services to the public.
> 
> As an office within the General Services Administration, we know how to work with government. All our projects support agencies in transforming how they deliver digital services and technology products.

Very open to other opinions, though!

**Comment by awfrancisco** [comment]
I like that shorter variant, but I think we should replace "deliver" with another word. At least in one of the instances, but probably both. Maybe develop or create?

**Comment by coreycaitlin** [comment]
I think we've narrowed down to one strong option to move forward with, which incorporates recent 1-pager work, and is visible over in #2148. Closing this out for now!
