### ISSUE TITLE
Create flowchart/sitemap and navigation improvements

### ISSUE THREAD

**Issue by austinhernandez** [18F/18f.gsa.gov#2124]
1. Find clearer and faster paths for users to reach their goals (http://mur.al/bGrEZKwQ)
- As a federal employee, I want to learn about how other agencies worked with 18F.
- As a potential partner, I want to know how to contact 18F, and what to expect.
- As a federal employee, I want to know what 18F is and why I should trust it.

2. Mockup navigation ideas to get users to completing 18F site goals (http://mur.al/bW2BB2oR)
- As a business, we want potential partners to comprehend how we can help
- As a business, we want potential partners to contact us

3. Establish sub-navigation to allow users to navigate throughout the site

Long and short term roadmap goals here - http://mur.al/bGrEZKwQ

**Comment by coreycaitlin** [comment]
Thanks for making the issue! Could you add a few notes about the user need here, and what you see as the current tension?

**Comment by austinhernandez** [comment]
https://invis.io/3X9J87M4V#/211089566_18Fflowchart-2

**Comment by coreycaitlin** [comment]
I'm going to close this issue out — we've made significant strides toward creating these paths / improving nav, and will keep measuring in user research.
