### ISSUE TITLE
Accessibility: remove manipulated content

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2128]
As @maya said well [here](https://gsa-tts.slack.com/archives/g-accessibility/p1481742349000108):
> I recently learned that you should not manipulate content so people who use screenreaders can understand it better. You should just give it to them as is, and they will figure it out with their tools. Otherwise it’s confusing to them.

An example of this on the site is
```
<h1 class="sr-only">Eighteen F</h1>
```

We should simply say

```
<h1 class="sr-only">18F</h1>
```

## This is issue is done when:
- [ ] we have located and removed as many instances of `manipulation-with-the-intent-of-screen-reader-users`. This could be done by searching alt, labels, class="sr-only", aria attributes

**Comment by coreycaitlin** [comment]
Fixed with #2143
