### ISSUE TITLE
Check on / update frontmatter tests gem

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2137]
We've changed some of the frontmatter fields in blog posts, and it would be nice to have better validation for whether the content in them are, well, valid.

**Comment by gemfarmer** [comment]
Two things to change:
- frontmatter properties should never be empty strings. They should be blank instead. Make sure that the gem checks for this
- Check array type to determine if the array contains valid values.

**Comment by coreycaitlin** [comment]
We now have issues to track this work over here: https://github.com/18F/jekyll_frontmatter_tests/issues 🎉
