### ISSUE TITLE
Improve `we asked` blog layouts

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2138]
## Expected Behavior

The interview-based blog posts ([example](https://18f.gsa.gov/2016/03/21/we-asked-100-of-our-coworkers-why-did-you-join-18f/)) have a slightly broken layout now.

## Actual Behavior

...better layout?

**Comment by gemfarmer** [comment]
Underway in #2146

**Comment by coreycaitlin** [comment]
Fixed in #2146 🎉
