### ISSUE TITLE
Tweak blockquote styling

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2140]

**Comment by gemfarmer** [comment]
In.vision with block quote styling https://projects.invisionapp.com/share/3X9J87M4V#/screens/210062112_Project_Detail_V1

**Comment by gemfarmer** [comment]
Block quote variations:

- **Basic blockquote**: Text that we want indented within a larger text block
- **Blockquote + Image**: 
- **Pull quote (see Austin's in.vision)**
- Lists of quotes: Ensure that blockquote styles look good en masse  (why did you join)
- List of quotes and images. (path to 18F)
- Image caption??: Maybe handle differently depending on length of the text

**Comment by elainekamlley** [comment]
Examples of current blog posts that use block quotes: 
- [image caption](https://18f.gsa.gov/2016/08/02/jacob-harris-from-big-data-journalism-to-micro-purchase-platforms/)
- [blockquote + image](https://18f.gsa.gov/2016/08/26/mark-trammell-unlocking-the-true-potential-of-public-service/)
- [list of quotes](https://18f.gsa.gov/2016/11/25/what-18f-is-thankful-for-this-thanksgiving/)
- [list of quotes + image](https://18f.gsa.gov/2016/03/22/what-was-your-path-to-18f/)
