### ISSUE TITLE
Organize projects by problem type?

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2154]
We have hypothesized that clear, plain-language project write-ups will help potential partners understand what we do and who we work with. It might also help to group those projects by category of problem solved, where the problem categories are:

- Improve your public-facing services
- Implement new laws or mandates
- Improve your internal systems

If research shows that these categories are useful in helping website users understand our work, we should consider using them to organize the projects featured on the homepage.

This can build on the work started in #2145

**Comment by coreycaitlin** [comment]
We should not pick this up until we've done some initial testing on these project categories.

**Comment by coreycaitlin** [comment]
Initial sorting of some of the projects we have:

Improve public-facing services:
- myUSCIS
- FEC (also internal systems?)

Implement new laws or mandates
- Every Kid in a Park (also public-facing services?)
- DATA Act

Digitize/streamline internal systems
- CALC
- C2
- Ready-2-Serve
- HHS State and Local 

Things that could be part of solving many kinds of problems:
- Agile BPA
- Federalist
- eRegs

**Comment by awfrancisco** [comment]
I think EKIP and FEC are in the right categories there. I'd put Agile BPA and Federalist in internal systems and eRegs in public-facing.

**Comment by coreycaitlin** [comment]
Closing this out for now — noted in the wiki here: https://github.com/18F/18f.gsa.gov/wiki/What-we-would-like-to-do-someday/
