### ISSUE TITLE
Add caption ability for blog hero images

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2162]
Currently, blog hero images don't have captions, which often leads to duplicate images, because we want to use the picture as a hero but we also need its caption...

**Comment by coreycaitlin** [comment]
Example post: https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/2016/10/11/getting-the-most-juice-out-of-the-squeeze/

**Comment by coreycaitlin** [comment]
We could also use a bit more guidance for figcaptions in general! (Within blog posts)

**Comment by austinhernandez** [comment]
Something like this for the header:

```
{    right: 0;
    bottom: 0;
    position: absolute;
    color: #000;
    background: rgba(241, 241, 241, 0.85);
    font-size: 12px;
    padding: 2px 5px;
    font-style: italic;
    width: 40%;     }
```

<img width="1065" alt="screen shot 2017-01-30 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/23194720/22441323/f214cd84-e704-11e6-9e1c-f430740b27ca.png">
<img width="1072" alt="screen shot 2017-01-30 at 2 45 28 pm" src="https://cloud.githubusercontent.com/assets/23194720/22441324/f2160ca8-e704-11e6-86e9-fb5218ddcbd2.png">

---

For the fig caption - light gray, small font, no bottom padding on the img, no top padding on the caption. Bottom margin on the caption

<img width="646" alt="screen shot 2017-01-30 at 4 37 13 pm" src="https://cloud.githubusercontent.com/assets/23194720/22442713/422d7334-e70a-11e6-88db-38c8df7ce0aa.png">
