### ISSUE TITLE
Use correct codeclimate badge

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2179]
## Expected Behavior

[![Code Climate](https://codeclimate.com/github/18F/18f.gsa.gov/badges/gpa.svg)](https://codeclimate.com/github/18F/18f.gsa.gov)

## Actual Behavior

[![Code Climate](https://codeclimate.com/github/18F/micropurchase/badges/gpa.svg)](https://codeclimate.com/github/18F/18f.gsa.gov)

## Steps to reproduce the behavior
- update badge markdown in README

**Comment by coreycaitlin** [comment]
See #2182
