### ISSUE TITLE
Better shorthand for adding captions to blog/page images

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#2185]
As a blog author, I want an easy shorthand for creating images with captions, so that I can spend less time converting google docs to blog posts.

When we have an image that doesn't need a caption, we can use the normal markdown shorthand `[alt text](path/to/image)` but if we do need a caption, we have to either craft a `<figure>` tag, or offset a seemingly unrelated paragraph in italics. It'd be great if we had a shorthand that could fill in the properties of `<figure>` and add a `<figcaption>` for us.

**Comment by gemfarmer** [comment]
This is closed as of #2265 !
