### ISSUE TITLE
Content: About 18F page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2186]
We need a page that explains the basics of 18F, including:

- our relationship to TTS and GSA (i.e. #2155)
- our history
- funding
- more

**Comment by coreycaitlin** [comment]
Source content from the press page:

> 18F is a growing group of technologists, designers, and researchers from around the country who are committed to making government services simpler and easier to use. We put the needs of the American people first, we work in the open to make our products stronger, and we are design-centric, agile, open, and data-driven.

> 18F projects adapted by other organizations

> We publish our code repositories on GitHub and encourage the public to adapt our code and guides for their own projects.
> 
> Here are some examples of how our projects have been adapted by others:
> 
> - A number of governments have used/adapted the code that powers analytics.usa.gov
> - The District of Columbia adapted 18F's Guides Template into their own, which they are using for things like the DC Government Open Source Guidelines.
> - Lovely, a real estate startup, created their documentation platform by adapting the code created for 18F's Hub. The Hub helps 18F organize our information and explore the connections between team members, projects, and skill sets. It serves as the go-to place for all team information.
> - Pulse was forked to check German government domains for HTTPS.
> - Many sites have adopted the Draft U.S. Web Design Standards.
> - AWS Broker for Cloud Foundry is in use by Australia's cloud.gov.au.

> 18F's relationship with the U.S. Digital Service
> 
> 18F and the U.S. Digital Service are distinct groups working toward the same vision of better digital government. 18F is a digital consultancy in an independent agency (GSA) and provides products and services to federal entities on a fee-for-service basis. The U.S. Digital Service is part of the Executive Office of the President and the United States CIO, supporting and coordinating the work of various digital service teams housed in agencies across the federal government.

> Basic information on 18F’s history
> 
> - GSA launched 18F on March 19, 2014. The name is an abbreviation for GSA’s address — 1800 F St.
> - The 18F team started with 15 full time staff. Staffing has grown to over 180 as of May 2016, as 18F’s product and client work has increased.
> - Our goal was (and is) to transform the way the U.S. government approaches problems. Read more about our evolution in the blog posts from our first and second anniversaries.

> How 18F Works
> 
> 18F works in partnership with agencies across government on a reimbursable basis. We deliver public-facing services via web applications, data and service Application Programming Interfaces (APIs), and platforms. 18F operates using three basic models:
> 
> - For you: Building solutions for an agency
> - With you: Integrating with an agency team to provide additional expertise or core capacity
> - By you: Advising an agency on how to build or buy user-centric digital services most effectively
> 
> 18F is an open source team. It uses open source development to transparently promote the security, quality, and modularity of our code and to invite review, participation, and free and simple reuse of our efforts by government agencies, the business community, and the public.

> How 18F is funded
> 
> 18F charges clients on a break even basis for the services we deliver. Revenue generated from these charges is held in the Acquisition Services Fund where it is made available for current and future operating expenses.

**Comment by coreycaitlin** [comment]
[Supporting research and recommendation](https://github.com/18F/18f.gsa.gov/blob/research/research/3-sprint-kuriouskettle/kuriouskettle-research-results.md#recommendations)

**Comment by coreycaitlin** [comment]
We should also change the content on these pages:

- [Insite page (limited access)](https://insite.gsa.gov/portal/content/502378)
- [GSA.gov page](https://www.gsa.gov/portal/content/124182)

**Comment by coreycaitlin** [comment]
- [ ] Add media contact link
- [ ] Explore other agency about pages

**Comment by coreycaitlin** [comment]
- should this be a whole section, and subsume the join content
- do we need pictures / info about leadership?
- should the press page be within this section?

What do we want people to get from this page?

**Comment by coreycaitlin** [comment]
## Tentative plan for this page

This page or section will be a place for a wide audience to get the 5 Ws:
- What 18F is
- Where 18F is (both physically and organizationally)
- Who makes up 18F, at least generally
- When 18F started, and when we became part of TTS
- Why 18F started/exists

As we've moved the homepage and `Hire 18F` page toward a more marketing-focused tone (and are likely to head the same direction with `What we deliver` and additional intake-y pages), we do need a spot for people who are disoriented, are not looking to hire us, or who distrust sales-oriented content. This section can be a place for anyone to learn the who, what, when, where, and why of 18F in a way that is clear, concise, and trustworthy. Having this content out there will also help combat misinformation.

This section — unlike the homepage and Hire 18F page — will _not_ use second-person pronouns (`you`, `your`), because we are assuming a wider audience.

**Comment by coreycaitlin** [comment]
Two "about" pages to look at for in-gov reference:

- [CFPB](http://www.consumerfinance.gov/about-us/)
- [betaFEC](https://beta.fec.gov/about/)

...while keeping in mind that we want to scope this to the smallest thing we can launch

**Comment by gboone** [comment]
I really like how little information there is on CFPB's about page. Lots of links into [deeper content](http://www.consumerfinance.gov/about-us/the-bureau/) that is similarly well organized and designed.

**Comment by awfrancisco** [comment]
I'd say this all looks good. I do think we should include something about leadership. People often ask for the org chart, which is difficult to publish for various reasons. AP also has Rob and Dave in the new pitch deck. So far they've had a good response to that, but we should keep an eye on that as user research for featuring leadership (though the pitch deck and about page have different audiences).

**Comment by gboone** [comment]
Also want to throw it out there that we should find out what people want to know about our leadership before we make a page with Dave's bio on it, and how deep they want to know it before we do an org chart. Worth noting, too, that [CFPB's org chart](http://www.consumerfinance.gov/about-us/the-bureau/bureau-structure/) doesn't go all the way to every individual. Stops at the assistant director level.

**Comment by awfrancisco** [comment]
Yeah, I'm not advocating bios. I would say only boiler plate info. And assistant director/project lead certainly seems deep enough. Could probably stop before then too.

**Comment by coreycaitlin** [comment]
Two notes from past user research on the site:

- When we use "you", some users get confused about whether we really mean _them_
- It's come up a few time that feds want to know who our leaders are (i.e. Dave)

And some notes from content workshop:

- NN articles: [About us info study](https://www.nngroup.com/articles/about-us-information-on-websites/) & [PR on websites](https://media.nngroup.com/media/reports/free/PR_on_Websites_3rd_Edition.pdf)

**Comment by coreycaitlin** [comment]
Some key notes from the NN reports...

[On about pages](https://www.nngroup.com/articles/about-us-information-on-websites/):

> Task success for finding out what the company or organization does actually dropped, from 90% to 81%. In place of a frank summary of the business, marketese and blah-blah text ruled the day on many sites.

> Sites that make it hard to find the most basic information about an organization get dinged hard these days

> We recommend providing About Us information at 4 levels of detail:
> 1. Tagline on the homepage: A few words or a brief sentence summarizing what the organization does.
> 2. Summary: 1-2 paragraphs at the top of the main About Us page that offer a bit more detail about the organization's goal and main accomplishments.
> 3. Fact sheet: A section following the summary that elaborates on its key points and other essential facts about the organization.
> 4. Detailed information: Subsidiary pages with more depth for people who want to learn more about the organization.

^^ _I think we're moving closer to this structurally, even if we're not naming the sections the same thing_

[On websites for PR](https://media.nngroup.com/media/reports/free/PR_on_Websites_3rd_Edition.pdf):

> The top-5 reasons journalists gave for visiting a company’s website are:
> • Locate a PR contact (name and telephone number)
> • Find basic facts about the company (spelling of an executive’s name, his/her
age, headquarters location, and so on)
> • Discern the company’s spin on events
> • Check financial information
> • Download images to use as illustrations in stories

> In general, the more interesting facts you present about your company, products, and executives, the better for PR. Journalists look for facts they can use in their stories. Our study participants were much more excited about genuine information than about marketing claims, which they immediately discarded.

> Feature a link to media information on the homepage and/or in the “About Us” section of the site.

> Name the link to press information one of the following: “Press,” “Press Room,” or “Media.”

> The words you choose should be understood by most audiences. Minimize the marketing hype, especially in the corporate sections of your site. People who visit corporate sections are on a fact-finding mission.

> Avoid repeating the shorthand you use to communicate with the people in your organization. People who come to your site may have varying levels of knowledge about your industry or organization.

> Once on the “About Us” page, users expect to find pertinent organization information right away...The summary should include answers to top questions such as:
> • What does the organization do?
> • How long has the organization been around?
> • How large is the organization?
>     o Number of employees
>     o Number of locations
> • Where is the organization located?
> • What is the organization’s revenue?
> This information helps users understand the organization’s background, stability, and credibility. 

> Make high-resolution product and corporate photos available and downloadable.

**Comment by awfrancisco** [comment]
Very interesting. Feels like we are on the right track and could address a lot of these with a press subpage. Would be so great if we could provide images for press to use. Especially for infosec stories.

**Comment by coreycaitlin** [comment]
Next step:

- Add a few more blog posts to the "who we are" / "our team" section of the page
- Add icons to the principles list
- Press section

**Comment by coreycaitlin** [comment]
#2268 should finish this one up, at least for now!

**Comment by gemfarmer** [comment]
#2268 is closed, so I'm moving this to `Done`
