### ISSUE TITLE
Content: project intro for DoL Wage and Hour Division

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2188]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by somebody on the project (maybe Rebecca R-S or Jay F)

**Comment by coreycaitlin** [comment]
[Draft goes here (limited access)](https://docs.google.com/document/d/1klkLPWft1DBBjiY9UavUyASGNgG2EPisWatFFddPcM8/edit)

**Comment by coreycaitlin** [comment]
Source content from the old intake site:

> In two days, our consulting team was able to work with a team at the Department of Labor’s Wage and Hour Division to take the four-volume, printed Field Operations Handbook and create an internal prototype of an online, searchable version. We were also able to demonstrate the power of using agile design and development methods.

**Comment by awfrancisco** [comment]
Additional source content in this [draft blog post](https://docs.google.com/document/d/15jIVv2WkOy1zuTWOgBACrVCXrmhrQ69PLdIEJXfwSnI/edit#).

**Comment by acolter** [comment]
Draft is ready for @coreycaitlin and @awfrancisco to review: https://docs.google.com/document/d/1klkLPWft1DBBjiY9UavUyASGNgG2EPisWatFFddPcM8/edit

**Comment by awfrancisco** [comment]
Good to go from me.

**Comment by coreycaitlin** [comment]
Looks good — just a few edits and one style question.

**Comment by coreycaitlin** [comment]
this has my 👍 — let's get it into markdown and approved next. @elainekamlley, do you want to help with getting this into markdown? That might be a good way to see if the template is clear (it's in the examples folder).

**Comment by acolter** [comment]
Got the thumbs up from Rebecca for this project intro. Mark down to your heart's content.

**Comment by awfrancisco** [comment]
https://18f.gsa.gov/what-we-deliver/dol-wage-and-hour/
