### ISSUE TITLE
Build new "what we deliver" page with project cards

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2194]
Pull together the design (#2040) and content (#2070) into a "what we deliver" or "our work" page that links to project cards.

**Comment by gemfarmer** [comment]
To do list:
---
Card area
- [ ] Either make images required or create alternative card that looks good without an image
  - [ ] Add missing images
- [ ] Make project `title` show up on cards
- [ ] Determine how they should be filterable (if they need to be filtered at all)
- [ ] Add margin between rows of cards
- [ ] Use flexbox to make cards a consistent height
 
Agency partner area
- [ ] Fix list styling
- [ ] Put them into appropriate buckets (if we need them at all)
- [ ] fix `where_obj` filter


Bottom section
- [ ] add it

Content/ IA
- [ ] how do we want to handle URLs? `/project/whatever/` vs `/what-we-deliver/whatever/` vs `/our-work/whatever/` vs `/work/whatever/`
- [ ] Refine copy/ headings

**Comment by awfrancisco** [comment]
+1 to no filtering and no buckets at this moment.

**Comment by coreycaitlin** [comment]
Remaining chunks of this:

- [ ] finding any images we can hunt down
- [ ] reviewing placeholder image handling with @austinhernandez 
- [ ] making the "all partners" list at the bottom pull from a separate yml file
- [ ] creating a list of all the partners we want to show up there
- [ ] fine-tuning text styling for the intro text at the top of the page
