### ISSUE TITLE
Content: USCIS project intro

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2200]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by Jen E

**Comment by coreycaitlin** [comment]
Source content from old intake site: 

> We’re working with the U.S. Digital Service to move the U.S. Citizenship and Immigration Services (USCIS) from a form-centric website to a human-centric one. This includes work across numerous disciplines to create a suite of resources and tools to demystify the naturalization process, move application forms online, and design an improved account system for applicants.

**Comment by coreycaitlin** [comment]
Source content from the press page:

> We helped the U.S. Citizenship and Immigration Services (USCIS) launch myUSCIS, a platform that allows users to easily access information about the immigration process and find immigration options for which they may qualify. Re-imagining the immigration process meant moving from a form-centric website to a human-centric one. We worked closely with USCIS across multiple disciplines to create a suite of resources and tools to demystify the naturalization process, move application forms online, and design an improved account system for applicants.

**Comment by kategarklavs** [comment]
Claiming this issue now!

**Comment by awfrancisco** [comment]
👍 

I'm working on some project slides for the AP pitch deck and recently drafted this. Feel free to use or not, but might help as a starting point. 

> The immigration application process is complicated and intimidating. It can also be inefficient, both for applicants and the federal workers processing those applications. 
> 
> We worked with USCIS to shift their form-centric process to be a human-centered one. By focusing on what the experience is like for someone applying to immigrate, USCIS was able to radically improve the customer experience. 
> 
> Now, people can enter their current immigration status the site shows them the benefits they’re eligible for and how to apply.
> 
> People can also log in to an improved account system to see their notices and appointments in a single location and find out what to expect next.

**Comment by kategarklavs** [comment]
@awfrancisco Ah, excellent — thanks for sharing this! I'll definitely incorporate it (and I'll post the Drive link below if you'd like to collaborate on the summary).

Draft link: https://docs.google.com/a/gsa.gov/document/d/18AZlocW7B2rpom7ohP7WTDq-TgMKhx2BBIHLBgS9wBo/edit?usp=sharing

**Comment by kategarklavs** [comment]
@coreycaitlin & @awfrancisco Just finished the USCIS summary draft — let me know what you think! (It's a smidge longer than some of the other summaries, but it's well under 400 words.)

**Comment by awfrancisco** [comment]
I think this is looking really good. Seems like the tagline might be the trickiest part since most of the words about this process are pretty long.

**Comment by coreycaitlin** [comment]
Agreed! I made some suggestions to shorten and simplify a bit.

**Comment by kategarklavs** [comment]
Howdy! Just accepted the changes to the draft. For the tagline, I like "Humanizing the process of becoming a citizen."

@awfrancisco — do other folks on the outreach team need to review this, as well? Let me know & I'll be happy to share the doc.

**Comment by awfrancisco** [comment]
Nope. Good to go from Outreach.

**Comment by kategarklavs** [comment]
Excellent! @coreycaitlin who else needs to review the copy before we can publish? (My guess is a representative group from the former USCIS team -- does that seem right?)

**Comment by coreycaitlin** [comment]
I think we can close this out with #2258 🎉
