### ISSUE TITLE
Content: Project intro page for Contract Awarded Labor Category tool (CALC)

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2201]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [ ] Content is reviewed by Alan B

**Comment by awfrancisco** [comment]
Working on a draft [here](https://docs.google.com/document/d/1defN9nirjDx3hYZHbRs-ap4GX_6d3dReDUTLrqhxrv4/edit)

**Comment by awfrancisco** [comment]
@coreycaitlin This is ready for review

**Comment by coreycaitlin** [comment]
@awfrancisco Reviewed and suggested edits! I really like how you dealt with the narrative, even though it didn't quite fit into our other-agency or product-story frameworks. It's super clear and easy to understand.

**Comment by awfrancisco** [comment]
Thanks! Edits accepted. 

@abrouilette Can you give [this doc](https://docs.google.com/document/d/1defN9nirjDx3hYZHbRs-ap4GX_6d3dReDUTLrqhxrv4/edit) a quick look for accuracy? This is the project intro page that will go up on 18f.gsa.gov and link to all the CALC blog posts.

**Comment by coreycaitlin** [comment]
Moving the final approval check to #2283

**Comment by abrouilette** [comment]
Okay to share that final review with the team, @awfrancisco, @coreycaitlin ?

**Comment by awfrancisco** [comment]
@abrouilette the CALC team? Sure. Here's an easy link for reviewing https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/project/calc/. And then you can check the box in #2283 when you all have reviewed.
