### ISSUE TITLE
Content: Project intro for C2

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2202]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by...someone?

**Comment by coreycaitlin** [comment]
Source content from old intake site:

> Communicart is a simplified, email-based purchasing approval tool for purchase card holders authorized to buy office supplies for the government. We designed it to be intuitive and convenient so that federal employees could drastically reduce the time they spend on purchase card approvals. Read more about how Communicart works.

**Comment by kategarklavs** [comment]
Hello again! I've helped out with C2 here and there in the past (and, in fact, during a hackathon during the days of yore, I wrote landing-page copy for an old version of C2). Happy to claim this one 👍

**Comment by kategarklavs** [comment]
Here's a first draft of the C2 summary: 

https://docs.google.com/a/gsa.gov/document/d/1RGFgL2RjQrvyZuTomdtE4fx5DE9Kt6sT-efW4NOrWbg/edit?usp=sharing

Pinging the C2 team now to get more information/a quote from a C2 user.

**Comment by kategarklavs** [comment]
@coreycaitlin & @awfrancisco Having added the testimonial quote at the end, I think this project summary is ready for Outreach review 👍

**Comment by awfrancisco** [comment]
Looking good. Left a couple edits.

**Comment by kategarklavs** [comment]
Thanks, @awfrancisco — just accepted those edits! 

@coreycaitlin I think this is ready for SME review. Being that Raphy is gone, should we ping Micah Taylor?

**Comment by kategarklavs** [comment]
Update: Sent the draft to @yowill for fact-checking & approval!

**Comment by kategarklavs** [comment]
Update to the update: Going to send the copy to Micah T. for fact checking/approval.

**Comment by kategarklavs** [comment]
OK! Micah Taylor reviewed this intro and gave it the thumbs up — I think this is set for publication!

**Comment by kategarklavs** [comment]
@coreycaitlin Howdy! Is it safe for me to close this issue, or should I wait until the summary is up on the site?

**Comment by coreycaitlin** [comment]
Still needs to move to markdown, then we can close!

**Comment by kategarklavs** [comment]
Ah, word! Thanks for the reminder, @coreycaitlin

**Comment by coreycaitlin** [comment]
Last check tracked in #2283
