### ISSUE TITLE
Content: Project intro for The New 10

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2203]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by...someone?

**Comment by coreycaitlin** [comment]
Source content from the old intake site:

> Our consulting team worked with the Department of the Treasury on their digital strategy around the redesign of the \$10 bill, consulted on content and visual design for the website, and helped shape the social media rollout.

**Comment by kategarklavs** [comment]
Happy to take on this issue!

**Comment by kategarklavs** [comment]
Here's where the draft lives: https://docs.google.com/a/gsa.gov/document/d/1h2da_UEFL2VZFW8UzCXnLlmZ7CS9Z4J1YugSIiPWsDc/edit?usp=sharing

(Note: Right now, the draft is more notes than draft — just pinged Kara to get more details about designs we created for the New 10. Hoping to flesh out this draft more tomorrow!)

**Comment by kategarklavs** [comment]
Update: Sent Kara a list of questions yesterday — once I get answers, I'll flesh out the current draft (which is a little sparse on details).

**Comment by kategarklavs** [comment]
Update: On Friday, Kara said she'd be happy to answer the questions I sent over — once I get her responses, I'll be able to flesh out the outline I have in the draft doc.

**Comment by kategarklavs** [comment]
@coreycaitlin and @awfrancisco Okey doke — just finished the draft of this. It's ready for your review!

**Comment by kategarklavs** [comment]
@coreycaitlin and @awfrancisco — thank you both for your awesome feedback! Just implemented nearly all of the proposed changes. The only outstanding comments are 1) a note to get more info from @elainekamlley on the desired impact of the project; and 2) a discussion re: _familiarized themselves with_ vs. _got to know_ (and I'm OK with either of these options — just wanted to clarify why I initially went with _familiarized_). 

Once we get these two items wrapped up, we can ask Kara to review the draft.

**Comment by kategarklavs** [comment]
An update: Just incorporated @elainekamlley's material into the summary — this should be ready for Kara's review.

cc @coreycaitlin and @awfrancisco

**Comment by kategarklavs** [comment]
@CaliforniaKara made some final edits (and many thanks for those edits!) — @coreycaitlin and @awfrancisco, we should be all set 😎

**Comment by awfrancisco** [comment]
@elainekamlley This is ready for conversion to markdown and publishing.

**Comment by coreycaitlin** [comment]
@elainekamlley whoops! I closed this, but then spotted this asterisk situation!

![screen shot 2017-05-17 at 4 03 24 pm](https://cloud.githubusercontent.com/assets/1450354/26179758/6148a3a6-3b1a-11e7-85c1-52125459bfa3.png)

**Comment by awfrancisco** [comment]
https://18f.gsa.gov/what-we-deliver/new-ten/
