### ISSUE TITLE
Content: Project intro for Federalist

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2204]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by Will Slack

**Comment by coreycaitlin** [comment]
Source content from the old intake site:

> The Federalist platform is a suite of tools designed to make it faster and cheaper for government agencies to build websites that are secure, responsive, and accessible. We developed Federalist for two audiences: federal developers who need a platform for reliable, quick hosting of static sites, and federal groups that may not have a developer on staff but need secure, accessible, and responsive websites to get their content out to the public. The White House Social and Behavioral Sciences Team used Federalist to create and launch the site pictured above.

**Comment by kategarklavs** [comment]
OK! While I wait to hear back about the New Ten, I'll get started on this intro 👍

**Comment by kategarklavs** [comment]
And I've got a notes doc going here:

https://docs.google.com/document/d/1nOrbIfEiLXn-4CHVYuOT7FmTOF9CRap2fgHx1u6Tx6A/edit

**Comment by kategarklavs** [comment]
@coreycaitlin and @awfrancisco Okey doke! I have the initial draft done and ready for your review. It's a bit more marketing-y than some of the other summaries (and if that's a problem, I can tone down the features section). Once you all + the Outreach team approve the draft, I'll send it over to Will for his review and approval.

**Comment by awfrancisco** [comment]
I think this is good. It does feel more like marketing, but that seems right for platforms. The other option would be case studies on how each agency used it, but that feels more like a blog post.

**Comment by kategarklavs** [comment]
Ah, OK — I'm glad to hear you're on board with the more marketing-y tone.

**Comment by kategarklavs** [comment]
Update: Being that @awfrancisco has approved the draft, I shared it with @wslack for his review/approval. Once Will signs off, we should be set to publish(!)

**Comment by kategarklavs** [comment]
Okey doke — Will just reviewed this intro and made a few edits (all of which I've accepted). This intro is ready to go 🎉

**Comment by gboone** [comment]
Looks like a few cloud.gov-related edits remaining from Britta then this is ready.

**Comment by coreycaitlin** [comment]
I'm going to run this by Britta or Will one more time and note the result in #2283

**Comment by wslack** [comment]
@coreycaitlin we have a new customer (and independent agency of the executive branch) - Not sure I want to list more specifically until the site is live

**Comment by coreycaitlin** [comment]
Great — we can always file an issue (or just a PR) to add agencies to the list when we're ready.
