### ISSUE TITLE
Create guidance for project imagery

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2205]
It really helps to have good pictures to help us highlight project work — but people might need a little more guidance about how to get pictures we can use.

**Comment by austinhernandez** [comment]
hey @coreycaitlin could you look at these guidelines and tell me if they make sense to you?

If possible:
1. Image should relate to the project title, the department, the process (in order of preference)
2. Show real users that benefit from this project 
3. Show screenshot (without words)
4. Mix it up! look at the current project list do you see too many of the same type of image (e.g. mostly screenshots, mostly brainstorming sessions)

Consider accessibility and try to avoid images that:
- Are low-contrast
- Have wording on them

Consider the audience (government employees and potential partners!) and try to avoid images with the following:
- Sensitive subject material (e.g. children when writing about Child Protective Services)
- Uninteresting subjects
- Super meta imagery (too much of a cognitive leap when relating to subject matter)

Size:
Banner: size 1300x 866

Guidance: 
1. Look at images on site for patterns
2. Ask on #18f-branding, #visual-design, or #beta-18f-site

**Comment by coreycaitlin** [comment]
@austinhernandez This is great, I love it. Want to find a spot in the wiki to put this guidance so we can find it again?

**Comment by austinhernandez** [comment]
https://github.com/18F/18f.gsa.gov/wiki/Finding-the-right-image-for-a-project-page

**Comment by coreycaitlin** [comment]
Yay! thanks @austinhernandez
