### ISSUE TITLE
Reconsider "Edit on GitHub" link or add new link to repo

### ISSUE THREAD

**Issue by maya** [18F/18f.gsa.gov#2220]
## Expected Behavior
Navigate to the GitHub repo in order to open an issue from the website.

## Actual Behavior
I'm looking for a link directly to GitHub from the website, but the only link to GitHub is "Edit on GitHub" which drops me into the HTML of the site. I don't want to edit the HTML, I want to open an issue unrelated to that template and possibly have a discussion. It's a little jarring to pop into that edit page.

## Steps to reproduce the behavior
- [ ] go to site
- [ ] look for github link
- [ ] click link

## This is issue is done when:
- [ ] I can reach the repo without being forced to edit a page

**Comment by coreycaitlin** [comment]
Thanks @maya!

**Comment by maya** [comment]
Thank you, @coreycaitlin!
