### ISSUE TITLE
Project page layout v2

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2226]
## Expected Behavior

The project pages are working well, but the content hierarchy and context are a little unclear, even to internal users.

## Actual Behavior

We want users to be able to tell quickly:

- That this is an 18F project summary / case study
- Who the partner agency was/is
- Which section of the site they're in
- What to do next (some kind of call to action)
- That the blog posts are related to the project

------

These pages should still be maintainable in Markdown — we don't want to have to custom-code each page in HTML.

**Comment by coreycaitlin** [comment]
The problems we're trying to solve on the existing version:

- People aren't clear on what the pages are — they're too easy to confuse with blog posts or general content pages, rather than example projects
- The transition to blog posts is clunky and confusing
- We need more content taxonomy and clearer hierarchy; for instance, it would be nice to set off the sections, i.e. `partner`, `overview` or `background`, and `our approach`.
- We're gonna need spots for some metadata and/or links — especially when there's a live site to link to or a product site that we want users to go to

**Comment by austinhernandez** [comment]
First version to tackle problems listed above:
![project-pagev1](https://cloud.githubusercontent.com/assets/23194720/22305450/9dd40ab8-e309-11e6-91fd-74ad760e1cca.png)

- Added breadcrumbs
- Reusing similar styles to the homepage for the project title
- Some of the content will change!

**Comment by awfrancisco** [comment]
Love it. I feel like I didn't know how clunky the current design was until I saw this one. I like the clear sections, the reused style on the blog posts, and that sidebar has all kinds of potential for additional info/transparency (time on project, cost, team size, documentation, etc).

**Comment by gboone** [comment]
Totally agree. The layout also looks flexible enough that adding new sections won't necessarily require involving a designer or developer.

**Comment by coreycaitlin** [comment]
This is looking great! My only hesitation, just cause it's a new pattern, is the gray background under the blog post excerpts — we should double-check the contrast there.

**Comment by austinhernandez** [comment]
good point! i copied the styles from the featured project section, but let's try the lightest gray we have in our style guide, or the color from the footer.

**Comment by coreycaitlin** [comment]
Fields to go in the sidebar!

- `agency` - "Agency partner"
- `timeframe` - "When" [new]
- `github_repo` - "GitHub repository"
- `product_clients` - "Agency partners" [new; list]
- `project_url` -  "Learn more"

**Comment by austinhernandez** [comment]
@gemfarmer here's the sketch file!
[projectpage.zip](https://github.com/18F/18f.gsa.gov/files/743168/projectpage.zip)

**Comment by austinhernandez** [comment]
I found this page on the [ellen macarthur foundation site]( https://www.ellenmacarthurfoundation.org/case-studies/france-collaborative-textiles-recycling-initiative) with a similar "meta content chunk" section. their headers are
```
sector: 
topics: [which look like content tags] 
policy types: 
barriers addressed: 
level of government: 
responsible agencies:```

i know we want to reduce content, but these titles may help us better frame each project. :)
