### ISSUE TITLE
Refine subnav functionality

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2227]
As we build out the About section, we'll need to tweak how the subnav ( #2043 ) works.

**Comment by coreycaitlin** [comment]
During pairing today, we talked through 3 options:

1. **Separate pages:** Each `li` in the side navigation is its own separate page with a unique URL, and you navigate between them using the side navigation
2. **Long scroll:** The entire section is one page, and the side navigation allows you to navigate through the headers
3. **Have your cake and eat it too:** The first level of side navigation represents separate pages, and the sub-navigation under each item allows you to navigate through the headers within each page

----

@austinhernandez and @gemfarmer agreed that option 2 is likely the best, simplest option here. I agree, and I think we can make the content work with this constraint.

**Comment by gemfarmer** [comment]
I think this is finished. Is there anything else not covered in this issue that needs taking care of??

**Comment by coreycaitlin** [comment]
Nope! I think anything else is covered in #2245
