### ISSUE TITLE
Content: Figure out the format for platform and product pages

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2228]
- eRegs
- cloud.gov
- login.gov
- Draft U.S. Web Design Standards
- Federalist

**Comment by awfrancisco** [comment]
Initial ideas that @coreycaitlin and I came up with. 

- Describe the large problem this product solves and give a brief background on the problem. Do not mention a specific federal agency.
- Explain our approach for solving this problem
- Provide a short example using the first agency we helped
- Briefly explain the next phase/feature for the platform
- If facilitated by the page design, list all agencies using the platform in the sidebar

**Comment by coreycaitlin** [comment]
I think this is a great starting point, and we'll adjust for each as needed (for instance, e-Regs #2189  needs to mention CFPB in the intro, to give them proper credit).
