### ISSUE TITLE
Improve gdoc-to-markdown conversion process

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2236]
When a blog post is completed, approved, and ready to post, it has to be converted into markdown for the site. That process is documented here, but is very bumpy.

Current pain points:

- all links are italicized
- dollar signs don't come out as dollar signs
- lists where an item is greater than 1 line long turn out as blockquotes
- if you use custom styles in a google doc (i.e. orange headings), some links come out as font-files references instead of links
- headings aren't reliable
- frontmatter goes okay, but people are bad at typing it correctly
- images don't show up
    - have to export gdoc as webpage, then extract images and re-add manually
- code snippets get mangled
- add space between list items

**Comment by awfrancisco** [comment]
Note that these bugs are produced when we use [pandoc](http://pandoc.org/index.html). Find open pandoc issues [here](https://github.com/jgm/pandoc/issues). 

@elainekamlley @gboone got any more bugs to add?

**Comment by gboone** [comment]
[Here's a list of all the things I look for — when I remember.](https://github.com/18F/18f.gsa.gov/wiki/Troubleshooting-formatting-with-pandoc)

**Comment by coreycaitlin** [comment]
Scripts seem like a good option to explore — [this variant](https://github.com/lmmx/gdocs2md-html) looks promising, too.

Do you have any estimates of how long this currently takes for simple blog posts? For more complex posts?

**Comment by coreycaitlin** [comment]
More info! Using Pandoc via `odt` instead of `docx` seems to resolve some of the issues, particularly the weird list formatting.

I suspect that many of these issues are being introduced in the GDocs --> Word part of the process, rather than the Word --> markdown step, so I think we should explore ways to remove the interim step.

**Comment by gemfarmer** [comment]
Has this [Google script](https://github.com/mangini/gdocs2md) been tried as an alternative to pandoc? I tried it just now and it seemed to solve some of the issues, but mangled the frontmatter.

Would the `convert to markdown` --> `check email` --> `amend any errors` be an acceptable new workflow, or is that even worse than before?

**Comment by gemfarmer** [comment]
Whoops! Should have read this thread before posting. Looks like this option has been/is being explored :(

**Comment by awfrancisco** [comment]
@gboone would know more, but I think either we aren't allowed to use Google Scripts, or you have to reinstall them for each document. There's some high burden that makes it kind of a pain.

**Comment by coreycaitlin** [comment]
I've submitted the OCIO vetting form for at least one of the Google Scripts, to see if that process can be worked-through. Hopefully if that works, it will give us the ability to use that script again.

**Comment by gboone** [comment]
Yeah, @awfrancisco's description matches my experience — I'd have to reinstall the script every time I wanted to use it. I wasn't aware of this form for getting them approved, but I did open an IT helpdesk issue about it a long time ago that went largely unanswered. Fingers crossed that the form works for us.

**Comment by coreycaitlin** [comment]
@awfrancisco When we talk next, I want to ask some about the overall blog workflow and it there are upstream opportunities to improve this process (like writing in markdown within gdocs) — understanding the whole process will help me understand a bit better what we can/can't change.

**Comment by coreycaitlin** [comment]
I'm marking this as blocked until I hear back about the Google Script.

**Comment by coreycaitlin** [comment]
First hypothesis about what "better" looks like:

- NOT having to fix list styling (pandoc via ODT might help)
- copy/paste frontmatter instead of editing linebreaks
- better keyboard shortcuts to help speed things up — documented

----

Things we are unlikely to fix:

- images
- special characters? (check odt option)
- code snippets (ask people to put them in GitHub gists so we can copy/paste directly)

**Comment by gemfarmer** [comment]
Update on where this is at:

I few weeks ago I had submitted a request to GSA IT to get [a google script](https://script.google.com/a/gsa.gov/d/1zdXIbImhgIQajZCA8zBOaYK4zou8wfS0VHcZ9kOrDvG9StrZXAhCmMSx/edit?usp=drive_web) approved for usage.

I thought that getting it approved would mean that it was available as an add-on, but it turns out that approval just means that we won't get in trouble, not that using it is functionally different.

To make sure that it would work as an add-on, so I tested it on my own personal gmail account and posted it [here](https://github.com/18F/gdocs2md/blob/master/gdocs2md.js), for reference.

Steps that worked for me (make sure to configure the SDK):
1. [add-ons#before_you_publish](https://developers.google.com/apps-script/add-ons/domain-wide#before_you_publish)
2. [add-ons](https://developers.google.com/apps-script/add-ons/publish)

**Comment by gemfarmer** [comment]
We are currently pivoting to tackle this issue in a few different ways:
- [ ] @gboone is going to document the best practices that are currently used for converting gdocs --> odt --> markdown. GIFs ftw!
- [ ] I will look into making a bookmarklet to do the same thing
- [ ] Greg and I will continue working with GSA IT to figure out how we can get the [script we wrote](https://github.com/18F/gdocs2md/blob/master/gdocs2md.js) or the existing [Export as Markdown](https://chrome.google.com/webstore/detail/export-as-markdown/hbojhdcnbcondcdfpfocpkjkfkbnbdad?hl=en-US) add-on approved for use org-wide

**Comment by gemfarmer** [comment]
cc @toolness @jeremyzilar

**Comment by gboone** [comment]
Work in progress [on the best practices wiki page](https://github.com/18F/18f.gsa.gov/wiki/Publishing-a-blog-post).

**Comment by elainekamlley** [comment]
@gboone is this good to close?

**Comment by jeremyzilar** [comment]
@elainekamlley If you could keep this open for the time being,... I sent this thread to the Google Docs team

**Comment by evbacher** [comment]
Try [gd2md-html](https://github.com/evbacher/gd2md-html/wiki), a free Google Docs add-on that I developed as an add-on after using Renato Mangini's standalone script.

**Comment by jeremyzilar** [comment]
Great news @evbacher 🎉 We'll test it out and then get it run through our approval process here at the GSA. So excited about this

**Comment by lsgitter** [comment]
Don't have the resources to do this. Would be nice to have if we do get the resources. Moving this to the parking lot.

**Comment by jeremyzilar** [comment]
I just submitted **gd2md** to GSA IT for approval https://github.com/evbacher/gd2md-html/wiki

**Comment by lsgitter** [comment]
Not enough resources to work on at this time.
