### ISSUE TITLE
Certain collections have an empty primary path

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2244]
## Expected Behavior

All collections that have subpages should also have a parent. Even if it is only a parent landing page the shows the different subpages

## Actual Behavior

Parent urls are 404s or empty

* [ ] https://18f.gsa.gov/author/
* [x] https://18f.gsa.gov/project/ **_this is now `/what-we-deliver/`_**

cc @coreycaitlin

**Comment by coreycaitlin** [comment]
Let's make `/author` be a list of blog authors, much like the `/tags` page.

And `/project` is no longer an issue, right? 😁

**Comment by gemfarmer** [comment]
@coreycaitlin correct. `/project` is no longer an issue.

FOr `/author/` or `/authors/` (maybe rename it?), I think a list would be great. We could even borrow the card style template from `What we deliver` and have images for authors associated with their most recent blog entry title.

**Comment by lsgitter** [comment]
Will work on this once we have the new design.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
