### ISSUE TITLE
Content: Project intro for Ready-2-Serve

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2248]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [ ] Content is reviewed by Tom Black

**Comment by awfrancisco** [comment]
Source content:

> As part of their strategic vision for 2015 to 2025, the U.S. Navy Reserve committed to using technology to reduce administrative burden and increase readiness. Previously, reservists had to use official desktop computers to access personnel records, duty assignments, and other information. 
> 
> In 2015, 18F partnered with the Navy Reserve to conceive, research, and deliver a prototype of a mobile application that allowed selected reservists to conduct all official business on an approved mobile device, whether government issued or personally owned. The Ready-2-Serve app is designed to allow reservists to report to duty across the globe, return to their home of record, receive broadcasts, access pay and personnel information, and send/receive official e-mail, all from a mobile device.
> 
> Our work with the Navy Reserve fulfilled a major mission goal and allowed reservists to more rapidly and efficiently respond to national security incidences and natural disasters. Or as the Navy put it “A Sailor’s time, and more importantly our nation’s use of it, must be focused to the greatest possible extent on the mission and not on administrative overhead.” 
> 
> Our approach allowed the Navy Reserve to eliminate years of potential requirements gathering and save millions of dollars through applying lean product development practices.
> 
> Beyond the successful delivery of the app, our work with Navy Reserve introduced them to agile product development practices and human-centered design, while also paving the way for new digital capabilities and the creation of a DevOps “center of excellence” in the Department.

**Comment by acolter** [comment]
Draft will go here: https://docs.google.com/document/d/10NHCmVuZQAReVEXnYOkaLo9_XwLt0Q9L9UujTjuTsAQ/edit

**Comment by acolter** [comment]
Draft ready for review: https://docs.google.com/document/d/10NHCmVuZQAReVEXnYOkaLo9_XwLt0Q9L9UujTjuTsAQ/edit

**Comment by awfrancisco** [comment]
Made some edits to include more plain language, but I think this one is almost ready to ship.

**Comment by acolter** [comment]
I incorporated the edits. Take another look, then assign to Tom Black if he needs to review it.

**Comment by awfrancisco** [comment]
@blacktm Can you give the doc linked above a quick look? It's a short intro to the Ready-2-Serve project.

**Comment by coreycaitlin** [comment]
We can also move this into Markdown!

**Comment by blacktm** [comment]
I'm going to review a make a few comments tonight.

**Comment by acolter** [comment]
There are some photos from the Navy Reserve workshop at https://drive.google.com/drive/u/1/folders/0Bz4vHpO5ki26Ukt0NUl2LVdTYVk and https://drive.google.com/drive/u/1/folders/0B1ebyFpRd3jVfm5PbEIzN18yMkpTMXo3S2xEVDVMcWhJUFJYOERRU0hfdUJPTjE3MWVLYnM that could be used for this project intro.

**Comment by coreycaitlin** [comment]
@blacktm: Here's a [preview link to see the content in-template](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/project/navy-ready-2-serve/)

**Comment by coreycaitlin** [comment]
Moving the final approval check to #2283

**Comment by blacktm** [comment]
Left a couple comments [on the draft doc](https://docs.google.com/document/d/10NHCmVuZQAReVEXnYOkaLo9_XwLt0Q9L9UujTjuTsAQ/edit). Looks great! Also, if you're looking for an image, they made [this cool header](https://drive.google.com/file/d/0B1ebyFpRd3jVZ0ZEOFplS0FObU0/view).
