### ISSUE TITLE
Content: Project intro for Military OneSource

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2249]
We need content for the project-tag landing page about this project. Background can be found [here](https://docs.google.com/document/d/1Y-5tcMjmiYlQ6k53UAVwj_SUsnMZV4IGSRbrYfn-unQ/edit?ts=582dbee2#) under Office of the Secretary of Defense.

## This is issue is done when:

- Content is drafted
- Content is reviewed and revised with outreach team
- Content is reviewed by Dave Z

**Comment by awfrancisco** [comment]
So, this is a project that we'd like to highlight for a number of business development reasons, but we've never written a blog post about it. What do people think about project pages that have zero blog posts attached to them?

**Comment by coreycaitlin** [comment]
@awfrancisco I think it's fine (not ideal, but okay!) — we just need to make sure the page template handles it well

**Comment by acolter** [comment]
Here's a draft of the project intro: https://docs.google.com/document/d/1d8SoFPq92D48kI6lO9qrClCguAw6_FFlT3Ox9pZWt30/edit

**Comment by awfrancisco** [comment]
Couple small edits from me, but this is looking great.

**Comment by acolter** [comment]
It looks like Tom Black worked on this project too, so I've reached out to him with a request to review it.

**Comment by blacktm** [comment]
Just reviewed, looks good! Only comment I made was about making sure we can publicly share costs savings compared to the Independent Government Cost Estimate (IGCE), which Dave Z could give a 👍 / 👎  on.

**Comment by awfrancisco** [comment]
@elainekamlley this is ready to be markdowned and published

**Comment by awfrancisco** [comment]
https://18f.gsa.gov/what-we-deliver/military-onesource/
