### ISSUE TITLE
Content: Project intro for the Agile BPA

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2250]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by Zac Cohn and Alla

**Comment by awfrancisco** [comment]
Background info [here](https://docs.google.com/document/d/1Y-5tcMjmiYlQ6k53UAVwj_SUsnMZV4IGSRbrYfn-unQ/edit?ts=582dbee2#)

**Comment by awfrancisco** [comment]
[AP slicksheet on Agile BPA](https://docs.google.com/document/d/1_vwAOSO5eETiyXfP0GdpA8n06nXXOgn4wuTd81jWV80/edit)

**Comment by acolter** [comment]
Draft will go here: https://docs.google.com/document/d/130Iwni79C4a7-b30W940l-jw_hz55V8C3JJZGG_QogE/edit

**Comment by coreycaitlin** [comment]
This is great @acolter — I left a couple of notes/questions. This one, again, doesn't quite fit into the single-agency framework OR the product framework, and the sheer number of concepts users have to grok to understand the Agile BPA is a little staggering. Happy to talk more if it would help!

**Comment by acolter** [comment]
@coreycaitlin Happy to talk further. I gave this draft another shot; take a look and let me know if this is any closer to what you had in mind. https://docs.google.com/document/d/130Iwni79C4a7-b30W940l-jw_hz55V8C3JJZGG_QogE/edit

**Comment by acolter** [comment]
Here's the content in template: https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/project/agile-bpa/

**Comment by acolter** [comment]
@mtorres253 would you have time to review this project intro for the Agile BPA to go on the 18F web site? https://docs.google.com/document/d/130Iwni79C4a7-b30W940l-jw_hz55V8C3JJZGG_QogE/edit

**Comment by awfrancisco** [comment]
I know I wrote the initial comment that mentioned Michael, but he might not be the right person to review this. Maybe @allalala (or someone she designates)?

**Comment by allalala** [comment]
I requested access to the doc. Also will designate someone to look at this imminently.

**Comment by zacharycohn** [comment]
I'll be doing this. Can I get access to the doc?

**Comment by acolter** [comment]
@zacharycohn Just granted you access to the doc on Google Drive.

**Comment by zacharycohn** [comment]
Edits have been completed in suggest mode.

**Comment by coreycaitlin** [comment]
Yay! Noting final-ish review in #2283
