### ISSUE TITLE
Design/dev: Mobile stickies

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2254]
## Expected Behavior
When we have "sticky" elements, they should be static or reduce in size when they are stuck

## Actual Behavior
Sticky navs on `/join/`, `/about/`, and `/project/**/` are fine in desktop sizes, but are overly large in mobile

## Steps to reproduce the behavior
- [ ] Design
- [ ] Impliment

## This is issue is done when:
- [ ] The stickies look spectacular

**Comment by austinhernandez** [comment]
looks good to me! good work @gemfarmer !

the only thing thats missing is some content! I'm looking specifically at the meta content chunk, the  `APPROACH` sub-title and the `We work with federal agencies to approach technology projects in new ways` text for "get in touch"
