### ISSUE TITLE
TrepidatiousTentRock: Tie up loose ends

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2276]
In this sprint we have:
- added a new About page
- added the join pages
- added a new project page layout with new attributes

Loose ends to tie up
- [x] #2275 About pages
- [x] #2274 Project pages
- [x] update information architecture for project pages? (alternatively wait til we have a better project landing page)
- [x] being on a project page should make the `what we deliver` nav item active  **(_work is at #2281_)** 

cc @coreycaitlin

**Comment by coreycaitlin** [comment]
- [ ] take down the /press page and redirect to the new press section

**Comment by coreycaitlin** [comment]
I don't think we need to sort out ALL the IA for project pages, since that'll be coming in #2194, but we should change a few of the hyperlinks on the current What we deliver page in the meantime.
