### ISSUE TITLE
Research: Write a plan for the next round of research

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2293]

**Comment by acolter** [comment]
@coreycaitlin Mind throwing a link to the last research plan in here?

**Comment by coreycaitlin** [comment]
Here's our last research plan: https://github.com/18F/18f.gsa.gov/blob/research/research/5-sprint-especialesker/especialesker-research-plan.md

And our last script: https://github.com/18F/18f.gsa.gov/blob/research/research/5-sprint-especialesker/especialesker-script.md

**Comment by coreycaitlin** [comment]
This is (wonderfully) done and has found a home in the research branch: https://github.com/18F/18f.gsa.gov/blob/research/research/research-plan-template.md

Thanks @acolter 🎉
