### ISSUE TITLE
Add method cards links to right column of project pages

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2300]
fill in more about this idea here

**Comment by awfrancisco** [comment]
Like all the methods we used in a given project?

**Comment by coreycaitlin** [comment]
Yep, that was the idea! The method cards team has found that people really want to know more about how individual methods fit together on projects, and it seemed like it might be useful to include on these pages.

The big questions to explore include:

- First, of course: which methods were used on each project, and are they identifiable (by someone who worked on the project, probably)?
- If we list them in the right rail, do they make sense, or are the titles too jargony to be helpful to non-designer users?

**Comment by coreycaitlin** [comment]
Closing for now — [noted in the wiki](https://github.com/18F/18f.gsa.gov/wiki/What-we-would-like-to-do-someday) that this can be reopened if research shows it would be valuable for site users.
