### ISSUE TITLE
Blog entry heroes require additional compression

### ISSUE THREAD

**Issue by waldoj** [18F/18f.gsa.gov#2307]
Many blog entries' heroes have file sizes that are just too big—many hundreds of kilobytes, when they could be closer to 50–200kb. Reduce these in size, without unduly sacrificing quality.

**Comment by coreycaitlin** [comment]
@waldoj What's your standard process here? It would be great to document a recommended process, such as:

- figure how the largest the image will need to be
- make the image that size in preview/sketch/pixelmater/photoshop
- export as jpg
- drop into imageOptim
- put file in appropriate folder and add to post

Are there specific filetypes or tools you use to sqeeze every last drop of cruft out?

**Comment by waldoj** [comment]
(I opened this issue solely so that I could tie my pull request to it, as a best practice. Which I did, but it's not showing up here? ... D'oh! I left a space in there (`# 2308`). OK, I just fixed it!)

**Comment by waldoj** [comment]
But, after posting an issue that just looked like I was trolling the 18f.gov team, I might as well answer your question. :)

24 years as a website developer has given me a second sense for how big an image should be. So it helps that I start with that target in mind, but that's not something that's really teachable.

I start by making the image the correct dimensions in whatever program.

Then I export it in the proper format. I'm generally shooting for a target size for the image, thinking through which image format (GIF, PNG-8, PNG-24, or JPEG) would be best for it. (e.g., GIFs are terrible for vertically-striped images, because of how their compression algorithm works, while JPEGs are lousy for images with large color fields, because compression artifacts are visible in them.)

If I'm going to make it a JPEG, then I carefully figure out the best level of compression within my image editor (e.g., Photoshop), using the preview function, that establishes a good tradeoff between image quality and image size.

If the image is a PNG, I drop it into [ImageAlpha](https://pngmini.com/) and reduce the color palette in the same manner as I optimize a JPEG, balancing that size/quality tradeoff. If the PNG has an alpha channel, turn it into a transparent PNG-8 instead (which almost always looks good enough).

If it's a JPEG or a PNG, I then drop the image into ImageOptim.

Then add to post!

**Comment by coreycaitlin** [comment]
I didn't take it as trolling at all! Just wanted to rope you into helping write the documentation for future image-fixers and image-posters. Thank you so much for doing this. 💟

**Comment by coreycaitlin** [comment]
Next step: turn this into documentation!

**Comment by gboone** [comment]
Does this seem like the type of thing we would put in the styleguide? I can see arguments either way.

**Comment by gemfarmer** [comment]
Great idea! Could be added to https://18f.gsa.gov/styleguide/images in a new section as "How to add images" or "Adding images" #2388

**Comment by elainekamlley** [comment]
This has been completed
