### ISSUE TITLE
What we deliver: Agencies list

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2327]
At the bottom of the "What we deliver" page, we'd like to list all the agencies we've worked with.

- This will need to be a curated list ([started processing here](https://docs.google.com/spreadsheets/d/1FZJvf2e8GdRlLp3zI-xEN2Y9ai0w2S6URStW2MrBCLE/edit); limited access)
- It should probably be stored in a `yml` file for ease of maintenance
- We have an open question about how to organize and de-duplicate this list — for instance, should `Department of Energy` and `Federal Energy Regulatory Commission` be listed separately? hierarchically? should only one be listed? Should all agencies be listed in alphabetical order (including smaller independent agencies), or should we separate cabinet-level depts?

## This is issue is done when:
- [ ] there is a decision about how to organize the list
- [ ] the list is finalized
- [ ] the `yml` or other data file is created
- [ ] the list is displayed on the "What we deliver" page in a way that makes sense

**Comment by gemfarmer** [comment]
This looks great. I can start implementing this with the list in that spreadsheet and we can edit it again once the list is _finalized_

**Comment by gemfarmer** [comment]
Closed with #2348
