### ISSUE TITLE
Join 18F redirects

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2340]
`join.18f.gov` currently redirects to `https://pages.18f.gov/joining-18f/`.

BOTH of those URLs should now go to `https://18f.gsa.gov/join/`.

**Comment by wslack** [comment]
PR to https://github.com/18F/federalist-redirects/blob/master/nginx.conf  - which, contrary to the name, isn't actually a core part of Federalist.

**Comment by gemfarmer** [comment]
**This is complete now that [this PR was merged](https://github.com/18F/federalist-redirects/pull/3)**

This updates a few redirects:
* [join.18f.gov](https://join.18f.gov/) --> [18f.gsa.gov/join/](https://18f.gsa.gov/join/) 
* [pages.18f.gov/joining-18f/](https://pages.18f.gov/joining-18f/) --> [18f.gsa.gov/join/](https://18f.gsa.gov/join/) 
*  [pages.18f.gov/intake/](https://pages.18f.gov/intake/) --> [18f.gsa.gov/contact/](https://18f.gsa.gov/contact/)
*  [guides.18f.gov/intake/](https://guides.18f.gov/intake/) --> [18f.gsa.gov/contact/](https://18f.gsa.gov/contact/)
