### ISSUE TITLE
Keep eye out for move from pages to <site>.18f.gov

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2351]
## Expected Behavior
Links to pages will work

## Actual Behavior
When the shift happens, many links on the site will break including in blog posts and multiple main site pages. 

## This is issue is done when:
- [ ] Scanned the site for pages.18f.gov links
- [ ] Replace with new <site>.18f.gov links

**Comment by wslack** [comment]
I expect we'll have a simple redirect in place so that links don't break, fwiw.
