### ISSUE TITLE
Join 18F: Find application form

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2355]
We should make sure we know where the application form currently lives, and put a link in the `open-positions` example file so it's easy to use next time there's an open position.

**Comment by coreycaitlin** [comment]
It's here: https://pages.18f.gov/joining-18f/pages/apply.html

This should probably get pulled into this site? Or something?

**Comment by fureigh** [comment]
Yep. @hestherchang has more info on the upcoming bout of hiring (and thus on timing).

**Comment by fureigh** [comment]
Technical suggestion: best to make an include file for the application link so you can just include it wherever needed and, when it inevitably changes, change it in only one place.

**Comment by gboone** [comment]
@gemfarmer should we close this issue since the talent team has moved to a Google Form for this?
