### ISSUE TITLE
Techical notes from building the styleguide

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2370]
While creating documentation for the styleguide, I have come across several technical items that should probably be addressed:

* [ ] Embeds: 
  * [ ] There are a few oembeds that aren't working, but are not private. These should be investigated.
  * [ ] Consider removing all instances where the deprecated `embed` filter is applied. _**we should probably just keep these in place**_
  * [ ] Add more documentation details on how we deal with privacy settings, what we decide to embed/not to embed
* [x] Navigation: There are several navigation filters that should at the very least be moved out of `utility.rb` to a separate `navigation.rb` plugin. These could also be simplified as the navigation.yml file isn't being used in the expected way. **_This should definitely be done to improve maintainablitiy of the site_**
* [ ] Filters
  * [ ] Consider removing some custom filters in `utility.rb` and replacing them with combinations of supported liquid filters.
  * [ ] Write tests for the untested filters.
~~* [ ] it may be worthwhile to override `jekyll_pages_api_search` with a custom search that uses the [JSON output](https://18f.gsa.gov/api/v1/pages.json) created by `jekyll_pages_api`~~

**Comment by gemfarmer** [comment]
After reviewing the navigation, it looks like most of the navigation complexity is in the subnav. @elainekamlley and I have put together some next steps to work on:

- Look at `includes/navigation/subnav.html` 
  - refactor it so that it only goes 1 level deep
  - avoid using custom filters to determine the active state (`usa-active`)
- in `includes/navigation.html`, reduce complexity of subnav so that the navigation items for a subnav are ALWAYS derived from the page-specific front matter, and not programmatically defined. Corey said that this was easier to maintain from her perspective, and I want to follow that intuition.

**Comment by gemfarmer** [comment]
Cases:

* When we are on **desktop** 
  - **hompage**, **none** the links are highlighted
  - **[/what-we-deliver/](https://18f.gsa.gov/what-we-deliver/)**, then **/what-we-deliver/** is highlighted
  - **[a project subpage](https://18f.gsa.gov/what-we-deliver/college-scorecard/)**, then **/what-we-deliver/** is highlighted
  - **[/what-we-deliver/blog/](https://18f.gsa.gov/what-we-deliver/blog/)**, then **/blog/** is highlighted  
  - [a blog post](https://18f.gsa.gov/2017/03/21/nasa-journey-with-us-web-design-standards/), then **/blog/** is highlighed
  - **[a tag page](https://18f.gsa.gov/tags/web-design-standards/), then **/blog/** is highlighed
  - **[an author page](https://18f.gsa.gov/author/julia/), then **/blog/** is highlighed

**Comment by jenniferthibault** [comment]
Really really like how this shaped up! I have a mishmash of thoughts, observations, and questions and would love to discuss any/all of them together!

______________

A couple of things were misbehaving/seemed like they might be occupying dimensions in space set by their old layouts:
- [ ] Code/Documentation accordions in typography section should be full-width to match other sections. They're currently half size:
  - <img width="995" alt="screen shot 2017-03-28 at 7 20 49 pm" src="https://cloud.githubusercontent.com/assets/11636908/24431720/b0a4090a-13eb-11e7-8fc5-075dc1d0003a.png">
- [ ] In the `Buttons` section, the accordions change size when they're opened and closed, and seem to jump around!
  - ![o3xl7wf7ws](https://cloud.githubusercontent.com/assets/11636908/24431785/0d27d274-13ec-11e7-9342-4bbe16e87231.gif)

**One observation on structure:**
- I noticed that there are a couple sections that might overlap each other: `Images`, `Blog components`, and `Blog images`. It feels like `Blog images` should be a child section to one of those, probably Blog images? I'd defer to your expertise with the system though.
  - Related: do you want to consider using child elements in the side navigation to show sub-sections? Some are complex enough that I think being able to skim the sections before scrolling would be beneficial, and it's already baked into the USWDS pattern:.
  - <img width="348" alt="screen shot 2017-03-28 at 7 58 16 pm" src="https://cloud.githubusercontent.com/assets/11636908/24432533/f3e5b650-13f0-11e7-8a11-bbbf6f0f7f72.png">
 
**A few picky content things** (though if this isn't the right time for those, 🤐 🙊 )
- On the home page: 
  - Exp**i**dite > Exp**e**dite
  - I *think* "Standards" is supposed to be capitalized when referring to the U.S. Web Design Standards or "the Standards"
- "Breadcrumb" is the only singular item in the side nav: I know we only have one style for those, but I think it would be normal to use the plural "Breadcrumbs" for consistency. (now I'd like a 🍪 to go with those crumbs...)

**And a style question!**
Are we doing anything on the 18F site to set limits on body text line length for better readability? If not, would it be something we consider for this guide's content? Looking at pages like the Introduction, or elements like the accordions, even if the containers are full-width on these pages, the content could be more readable if the text had a narrower line length. (more white space and breathing room, 💭 !) I think USWDS sets their body styles to ~75 characters using the class `usa-content`  [as seen in the typesetting section](https://standards.usa.gov/components/typography/#typesetting)

**Comment by gemfarmer** [comment]
@jenniferthibault thank you, thank you, thank you again for the critique! 

- **Accordions**: yes, these definitely need to be wrangled!
- **Structure/children**: I was hesitating from giving the drawer child items because of complicating things, but I think you are right that it is more confusing the way it is now
- **Other**: Typos ✅. I will pluralize all components for consistency ✅ 
- **Style question**: Yes, we do limit content width with a class called `content-focus`. I'm not entirely sure why we don't follow the Standards here as this predates my involvement in this project, but I think we could use `usa-content` to get the content to a standard line width within the style guide and consider introducing that approach to the site itself!

**Comment by jenniferthibault** [comment]
On the line-length limits for the 18F site, if there isn't already a class controlling them under the hood I think the way the layouts use the grid often impose de-facto widths right around the 75 character mark. So maybe no changes needed to the site, just to the style guide! 

Here are two examples of what I mean by layouts that comply with good line-width measures:
<img width="1280" alt="screen shot 2017-03-29 at 11 15 08 am" src="https://cloud.githubusercontent.com/assets/11636908/24462136/397fa060-1471-11e7-94c8-1059d914c4e2.png">
<img width="1278" alt="screen shot 2017-03-29 at 11 15 15 am" src="https://cloud.githubusercontent.com/assets/11636908/24462137/397ff6e6-1471-11e7-97b8-3c53d70adb7c.png">

**Comment by gemfarmer** [comment]
> So maybe no changes needed to the site, just to the style guide!

I think I'll go ahead with this for now, although in the long run it does seem a counter-productive to invent an entirely new character max (`content-focus`) . I might be wrong here, but it seems like it would be better to set a max-width and design layouts to make that decision, instead of the other way around.

For now, I can mention that we:
- are using the `content-focus` class to cap the width at ~70rem (image 2).
- use the grid to impose layouts, as you mentioned.

**Comment by gemfarmer** [comment]
@jenniferthibault the changes are up and will available at https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/styleguide/ in about 20 mins!

**Comment by elainekamlley** [comment]
Pulled out the embeds issue and created a new one capturing that since it is not entirely related to the style guide #2465. Closing issue.
