### ISSUE TITLE
Team API should be removed from https://18f.gsa.gov/developer/

### ISSUE THREAD

**Issue by porta-antiporta** [18F/18f.gsa.gov#2381]
## Actual Behavior
404

## Steps to reproduce the behavior
- [1 ] Open https://18f.gsa.gov/developer/
- [2 ] Click on `Team API` hyperlink
- [ 3] Receive 404

## This is issue is done when:
- [ ]
- [ ]
- [ ]

**Comment by gboone** [comment]
This closed with #2382. Thanks @porta-antiporta
