### ISSUE TITLE
Team API 🚫

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#2386]
Find, remove, or repair any scripts or site components that rely on the Team API. It's deprecated and will return 404 if we attempt to use it.

related: #2382

**Comment by gboone** [comment]
These appear to be the only non-blog files referencing the API:
- [ ] https://github.com/18F/18f.gsa.gov/blob/master/api-endpoints
- [ ] https://github.com/18F/18f.gsa.gov/blob/f26d5d495e9cc9f31f7da044841d96a2b0859735/_data/team.json

These blog posts make mention of it, the links should be deactivated or removed:
- [ ] https://github.com/18F/18f.gsa.gov/blob/5cdfa563aa4ed7e568cbc7a0b6f86c9cc672c815/_posts/2015-12-23-looking-back-2015-our-own-words.md
- [ ]  https://github.com/18F/18f.gsa.gov/blob/fd29fcdae6747e68f7ff2c46b4bbbfc1df13f36e/_posts/2016-01-04-turning-learning-up-to-11-transparency.md

**Comment by elainekamlley** [comment]
Checked those links and looks like they are good and do not return a 404. Closing.
