### ISSUE TITLE
Style guide research plan

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2391]
Per [this issue comment](https://github.com/18F/18f.gsa.gov/issues/2383#issuecomment-293320068), we are going to conduct a series of research on how to better improve the site style guide

[Slack conversation about style guide review](https://gsa-tts.slack.com/archives/C0MKZ8E9H/p1491926816194686)

To summarize, we are going to break up the review process into a few steps:
1. **v5** – User interview outreach team
2. **v6** – User interview folks from guides and subdomains
3. **v7** – Design review

cc @elainekamlley

**Comment by gemfarmer** [comment]
To do items for style guide:
- document project properties [slack convo](https://gsa-tts.slack.com/archives/C0MKZ8E9H/p1492032173024116)

**Comment by elainekamlley** [comment]
Research plan: https://docs.google.com/a/gsa.gov/document/d/1TXfhWX0LMTz4CBwFU3l3OU5G_knSGTyJ9vPCQFXE-u4/edit?usp=sharing
