### ISSUE TITLE
Images for project page tiles

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2395]
## Need images

- cloud.gov
  - logo
- Military OneSource
  - military family
- Labor Wage and Hour
- Micro-purchase
- Treasury new ten
  - cash money
- Web Design Standards
  - [firework and flag](https://standards.usa.gov/)

## Icons that would be good to replace

- Agile BPA
- CALC
  - graph from homepage
  - image from slide 5, 6, or 9 in [this deck](https://docs.google.com/presentation/d/1ad7k2FB8noKEWPHq1j2QxriNzco97EgrisL1eWIagiU/edit#slide=id.g1a6586c441_1_176)
- eRegs
  - header image from [here](https://www.consumerfinance.gov/eregulations/)
- C2
- betaFEC

**Comment by elainekamlley** [comment]
Working through these and will check off when they are done. 
## Need image
- [x] cloud.gov
- [ ] Military OneSource
- [ ] Labor Wage and Hour
- [ ] Micro-purchase
- [x] Treasury new ten
- [ ] Web Design Standards

## Icons that would be good to replace
- [ ] Agile BPA
- [ ] CALC
- [ ] eRegs
- [ ] C2
- [ ] betaFEC

**Comment by elainekamlley** [comment]
Waiting till #2620 is done to add images

**Comment by ShannonBad** [comment]
[Logos - DataAct CloudGov Federalist.zip](https://github.com/18F/18f.gsa.gov/files/1623570/Logos.-.DataAct.CloudGov.Federalist.zip)

This is a sketched preview of the logos on three different background colors, sharing so we can discuss them.
<img width="784" alt="screen shot 2018-01-10 at 7 52 12 pm" src="https://user-images.githubusercontent.com/35078464/34838373-aa84d400-f6b2-11e7-8b9e-aa80bd865d66.png">

**Comment by elainekamlley** [comment]
Hey @ShannonBad, thanks for all your work on this! Discussed it with the team and we feel like the light background is the best option for contrast.

**Comment by ShannonBad** [comment]
Hi @elainekamlley, OK that sounds good. Do you need me to set up the files with background colors? Right now the files are only SVGs of the logos, on transparency. I have more icon/logos to upload here too - which I will do ASAP.

**Comment by elainekamlley** [comment]
@ShannonBad that would be great if you could set up those files. Another thought we talked about is setting up the logos with the light grey color: #f1f1f1. We don't want the image to blend in with the body of the page. What do you think? 

Looking forward to seeing the others

**Comment by ShannonBad** [comment]
FILES: [Logos - DataAct CloudGov Federalist 2.zip](https://github.com/18F/18f.gsa.gov/files/1641588/Logos.-.DataAct.CloudGov.Federalist.2.zip)

I agree it looks better on the grey background (#f1f1f1) too. Let me know if you have any problems opening this zip folder.

<img width="684" alt="screen shot 2018-01-17 at 7 58 23 pm" src="https://user-images.githubusercontent.com/35078464/35080194-f133c9de-fbc0-11e7-8377-a2e186cc1c62.png">

**Comment by ShannonBad** [comment]
These are just a few ideas for the logo for Web Design Standards, they can be in any color. I am happy to make revisions based on your feedback. 
<img width="593" alt="screen shot 2018-01-17 at 8 55 11 pm" src="https://user-images.githubusercontent.com/35078464/35081469-39cec1dc-fbc9-11e7-815b-60d019acdc8d.png">

**Comment by ShannonBad** [comment]
A few ideas for the logo for Labor and Wage. 

<img width="767" alt="screen shot 2018-01-18 at 10 27 50 am" src="https://user-images.githubusercontent.com/35078464/35114682-6beae454-fc3a-11e7-9916-8c72091aaf54.png">

**Comment by elainekamlley** [comment]
@ShannonBad great work! Here's some of our thoughts: 
1. Could you incorporate a web design standards image to the icon you made? I'll send that image to you directly
2. Labor and wage: We like the clock and coin one. Let's try experimenting with WDS colors for the clock and the coin since we know those are 508 compatible. Here are they [colors](https://standards.usa.gov/components/colors/)
3. For the logo images, lets try it out! I can add the images to the project pages and we can see how they look overall. We can see what they look like with different backgrounds and how they look with all the same grey background. We can review that in next week's co working session.

**Comment by ShannonBad** [comment]
@elainekamlley Thanks for the feedback I will work on those updates. As well as work the other logos on this list, which are a little bit more difficult since they're more abstract. I also started playing around with the three icons we had talked about - is that a different GitHub project page?

**Comment by ShannonBad** [comment]
Here's the WDS colors (in shades of blues and grey) of Labor and Wage! 
<img width="760" alt="screen shot 2018-01-21 at 8 06 13 pm" src="https://user-images.githubusercontent.com/35078464/35205031-0ae56a9e-fee7-11e7-9b0d-703d36a25e0d.png">

**Comment by ShannonBad** [comment]
<img width="520" alt="screen shot 2018-01-27 at 11 56 57 pm" src="https://user-images.githubusercontent.com/35078464/35480217-60c3fcf6-03be-11e8-9dfc-e3ce0ffaf515.png">

This is an example of adding a scrim of 30% of the grey color (#f1f1f1) on the left side photo & no scrim on the right side photo --- the grey color could be changed based on what is decided for the background colors for the icons, but the idea being by adding a scrim to the photo images we are making the page as a whole look more cohesive. 

<img width="727" alt="screen shot 2018-01-28 at 12 05 53 am" src="https://user-images.githubusercontent.com/35078464/35480259-24ab4728-03bf-11e8-91ed-dad3d6db72db.png">

And this image to show what that might look like in a larger context of the page.

**Comment by ShannonBad** [comment]
<img width="695" alt="screen shot 2018-01-27 at 11 54 24 pm" src="https://user-images.githubusercontent.com/35078464/35480285-7af6eaa6-03bf-11e8-876b-bf337467ff6d.png">
One idea I had was for the projects that do not have any obvious icons (also for future projects with the same issues) to add in a pattern that is different for each post but still cohesive as a whole together. The colors in the pattern will be WDS and tie in with the icons themselves. The example here is of a sort of "network" pattern image - on the right side V4 we have the pattern with a white background, and on the left side V5 the pattern is in a grey (#f1f1f1) background.

**Comment by ShannonBad** [comment]
<img width="748" alt="screen shot 2018-01-29 at 12 08 40 am" src="https://user-images.githubusercontent.com/35078464/35499820-d86b40aa-0488-11e8-82f4-ba92049829f1.png">
This is another version of the same pattern idea (as the previous post), however these "abstract" patterns are inspired by the EPA Graphics Standards System and the NASA Graphics Standards of the 1970s but using the WDS colors.
