### ISSUE TITLE
Queue functionality for blog posts?

### ISSUE THREAD

**Issue by quepol** [18F/18f.gsa.gov#240]
Is there a possibility to queue blog posts to go live at a certain time? Key functionality from Tumblr.

**Comment by gboone** [comment]
Some ideas tossed around on the #18f-site channel on chat yesterday after reading this GitHub blog post: https://github.com/blog/1939-how-github-uses-github-to-document-github

A chat bot might be a good tool to use to help us manage a queue for the blog. If we merge posts with `date` set in the future Jekyll won't build those pages. So if we queue up a post and then send hubot a command like `publish 18f-site at 9AM on Thursday` we could effectively manage a queue that way. We could have subcommands like `publish 18f-site schedule` to list out any scheduled builds, and have it report back on successful/failed builds as well.
