### ISSUE TITLE
Suggestions for how to improve the site

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2404]
After doing development work on the site for several months, I have put together a series of suggestions for potential ways the site could be improved

- [x] Improve the search functionality of the site
- [ ] Update/streamline plugins
  - Replace `_plugins/team.rb` with a complex include. 
  - remove `find_collection` filter
- [ ] Layouts
  - Rename layouts to be less confusing
- [ ] How we work
  - update page icons. The different colors on the SVGs is a bit off-putting
- [ ] Mobile footer: could be visually refined
- [ ] Author pages
  - improve header
  - potentially include tags of all author posts in one consolidated section on the page
- [x] Tag pages:
  - Make header of page match other pages throughout site (blue top ribbon)
- [x] Blog
  - Consider changing page of all posts to more closely resemble blog cards used in the related posts section of an individual post
  - In list of blog posts, the last list has a border bottom that should be removed
- [x] Homepage
  - [ ] make hero more closely resemble hero in project pages, with image not going full width

cc @elainekamlley

**Comment by lsgitter** [comment]
not enough resources at this time.
