### ISSUE TITLE
User research synthesis

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2410]
Taken from [this user research](https://drive.google.com/drive/folders/0B8kn3cuJUwEkQ3EwenZtTkM5Mjg):
	
**Done**:
- [x] Buttons:
  - [x] Remove “anatomy of a button”

**Together**:
- [ ] General:
  - [ ] Documentation should include gotchas when relevant. Make sure that we fully document all the components that someone needs to make something work
  - [ ] Consider allowing accordions to both expand at the same time
  - [ ] Accordions should go full width, but have constrained content
  - [ ] Could include simple and complex examples of how code is generated. Think project cards. The simple include is great, but the html example is also useful

**Elaine**:
- [x] Sticky subnavigation:
  - [x] Change “heading two” to “heading 2”
  - [x] Show examples of where we have this within the site
- [x] **Elaine** Images: 
  - [x] Each section should have an explanation of usage (image with/without caption)
- [x] Blog: 
  - [x] Consider renaming to “blog components”
- [ ] Layout: 
  - [x] People seemed to expect templates or layouts for the site, not a description of classes
  - [ ] If there are descriptions of classes, they should be accompanied by usage examples
  - [x] Move right aligned list to example of layout, not in components
  - [x] Rename right-aligned list to sidebar
  - [x] Examples for how to populate data within a layout (think sidebar)
  - [ ] Current Layout page should be “Using the Standards” or something like that??

**Brian** 
- [x] Introduction/Getting started:
  - [x] Button on Introduction page should go to Layout, not Typography
  - [x] Link should not go to plugins page
  - [x] Could have sentences that indicate what the subpages do (if you want to do X go here…)
- [x] Using Jekyll could take the documentation in the wiki for plugins
- [x] Two first pages could be “For developers” (using jekyll) and “for designers”

@elainekamlley

**Comment by elainekamlley** [comment]
Thanks @gemfarmer for putting this together!

**Comment by elainekamlley** [comment]
Closing and opening #2464 to pull out the remaining issues to fix.
