### ISSUE TITLE
Make a "Application no longer available" page

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2425]
## Expected Behavior
If I got to a job listing a few days after it was up, I don't expect to get a 404 page

## Actual Behavior
I get a 404 page

## In action
See https://18f.gsa.gov/join/product-manager/ or https://18f.gsa.gov/join/product-manager/apply/

## This is issue is done when:
- [x] Content for this page is drafted (assigned to @awfrancisco)
- [x] There is a page, maybe `/apply/expired`?, that use the `jekyll-rediriect-from` plugin to redirect expired job listings to that page  (assigned to @elainekamlley)

**Comment by awfrancisco** [comment]
@elainekamlley Here's some content. Let me know if you need more/different stuff. https://docs.google.com/document/d/17UJtCtp8Y0Gw_7Wk5sutO43-vd9BnZ71BWeQ1CpmMWM/edit

**Comment by elainekamlley** [comment]
Closing. Fixed through #2481
