### ISSUE TITLE
Clarify job titles and handoff from USAJobs

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2431]
The talent team is hearing quite a bit of confusion about our job postings because of the discrepancies in official titles/functional roles in different locations. I think we can fix this by changing the button text on the join page, as well as some other tweaks.

**Comment by elainekamlley** [comment]
@coreycaitlin makes sense. Greg is out this week and I can help with these updates. @hestherchang  What can we update on site?

**Comment by coreycaitlin** [comment]
@elainekamlley I spent a few minutes talking it through with @hestherchang and paired on a tiny change in #2432, but would love your review there! Also, should we pull master back into dev, just to keep it all on the same page?

**Comment by elainekamlley** [comment]
Closed because of #2432
