### ISSUE TITLE
Broken link at https://18f.gsa.gov/join/position-description/acquisition/gs-15/

### ISSUE THREAD

**Issue by sqs** [18F/18f.gsa.gov#2434]
## Expected Behavior

On https://18f.gsa.gov/join/position-description/acquisition/gs-15/ at the bottom under "Ready to apply?" when I click the "Read the GS-13 position description here" link, I expect it to take me to that page.

## Actual Behavior

HTTP 404 at the link's destination: https://18f.gsa.gov/join/position-description/gs-13/

## Location of bug

https://github.com/18F/18f.gsa.gov/blob/900c25318526460b9ee9ed7d75dbda6b23c793a1/_join/job-listings/acq-gs-15.md?raw#ready-to-apply

I don't know the correct fix because there seem to be two forms of URLs and I am not sure of the difference between them: https://18f.gsa.gov/join/position-description/acquisition/gs-14/ vs https://18f.gsa.gov/join/position-description/gs-14/.

**Comment by gboone** [comment]
Thanks @sqs we'll make sure we try and catch this the next time we have a job posting. This position is taken down now, so we'll close this.
