### ISSUE TITLE
Public Salary Data

### ISSUE THREAD

**Issue by commit-dkp** [18F/18f.gsa.gov#2439]
## Expected Behavior
https://18f.gsa.gov/join/#government-pay-grades includes content that explains individual federal employee salaries are public data.

## Actual Behavior
https://18f.gsa.gov/join/#government-pay-grades does not include content that explains individual federal employee salaries are public data.

## Steps to reproduce the behavior
- [ ] Search 18f.gsa.gov for content about government pay.
- [ ] Fail to find content that explains individual federal employee salaries are public data.

## This is issue is done when:
- [ ] Search 18f.gsa.gov for content about government pay.
- [ ] Find content that explains individual federal employee salaries are public data.

**Comment by coreycaitlin** [comment]
Hi @commit-dkp — could you add a bit more about when we expect users to look for this? (For instance, did you hear about this from an applicant?) It can really help to have more context as we find the right spot for content and make sure the pathways to it are clear.

**Comment by commit-dkp** [comment]
Hi @coreycaitlin - I expect this kind of information is relevant for our users who are considering applying to join 18F; I knew this information before I applied, but I don't recall learning it from 18F, and https://www.buzzfeed.com/jsvine/sharing-hundreds-of-millions-of-federal-payroll-records prompted me to check if we explain this to potential applicants at all.

**Comment by awfrancisco** [comment]
Fixed by #2470
