### ISSUE TITLE
Need to Clarify Federalist is not equivalent to cloud.gov 

### ISSUE THREAD

**Issue by thecapacity** [18F/18f.gsa.gov#2444]
For this page: https://github.com/18F/18f.gsa.gov/blob/f128bd9e6030bbcb38899c35e7b2015c9a217e7f/_posts/2017-06-01-federalist-is-out-of-beta-and-open-for-business.md

## Expected Behavior

`In one package, built on a FedRAMP authorized platform, we provide a trusted solutions for hosting your site…`

## Actual Behavior

`Federalist allows you to simplify. In one package, we provide a trusted, FedRAMP authorized platform for hosting your site with flexibility to scale and security compliance built in....`

## Steps to reproduce the behavior
- [] visit the site

## This is issue is done when:
- [ ] there is clarity that FedRAMP has certified cloud.gov and not Federalist, which sits on top of the PaaS

**Comment by thecapacity** [comment]
@wslack @awfrancisco @elainekamlley - suggestions on edits above

I don't have easy options to create a PR for it sorry.

**Comment by awfrancisco** [comment]
@wslack if you are 👍  up on that change, I can make the PR.

**Comment by awfrancisco** [comment]
can do
