### ISSUE TITLE
pages.18f.gov/API-All-the-X returns 302

### ISSUE THREAD

**Issue by minhaz** [18F/18f.gsa.gov#2448]
## Expected Behavior
View page at https://pages.18f.gov/API-All-the-X/

## Actual Behavior
return 302

## Steps to reproduce the behavior
- Browse to https://pages.18f.gov/API-All-the-X/

## This is issue is done when:
https://pages.18f.gov/API-All-the-X/ returns a page

**Comment by gboone** [comment]
@gbinal do you know the correct URL for this site?

**Comment by awfrancisco** [comment]
Fixed [here](https://github.com/18F/pages-redirects/issues/90)
