### ISSUE TITLE
The link to code-of-conduct.md in the CoC page 404's for the general public

### ISSUE THREAD

**Issue by toolness** [18F/18f.gsa.gov#2449]
Unfortunately, the existing CoC link at the beginning of [`pages/code-of-conduct.md`](https://github.com/18F/18f.gsa.gov/blob/594fa532d2fdd26b4f4cebb9b060cf75ec5f0d36/pages/code-of-conduct.md) 404's for public contributors due to the fact that the 18F/code-of-conduct repository is currently private.

For more details on this issue, see:

  https://github.com/18F/code-of-conduct/issues/4

Until this issue is resolved, it might be worth changing the language around that link. Perhaps we could explain that we're normally welcoming of comments on it, but that due to technical issues the repository is currently private?  Or alternatively, we could just comment-out the link for now and uncomment it once the CoC repo becomes public again.

Let me know what you think is best, I'm happy to file a PR to make the fix if you like.

**Comment by elainekamlley** [comment]
Closing this since the CoC is currently in revision.
