### ISSUE TITLE
Styleguide updates

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2464]
Now that we changed the design for the blog template we need to update the blog post template in the guide.

- [ ] Documentation should include gotchas when relevant. Make sure that we fully document all the components that someone needs to make something work
- [ ] Consider allowing accordions to both expand at the same time
- [ ] Accordions should go full width, but have constrained content
- [ ] Could include simple and complex examples of how code is generated. Think project cards. The simple include is great, but the html example is also useful
- [ ] Add instructions and guidelines for project images
- [ ] Update the [guide](https://18f.gsa.gov/styleguide/layouts/#blog-post-template)

**Comment by lsgitter** [comment]
Move this issue to the branding repo

**Comment by Dahianna** [comment]
@cmajel and @Dahianna will work on this as part of 18f-branding
