### ISSUE TITLE
Project cards and page updates

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2466]
## Project images:
- [ ] Follow up with visual design to see what they suggest
- [ ] Add images to the repo
- [ ] Add the set of images to `18f.gsa.gov/styleguide` with the include tags 

## Project card content: 
- [x] update summaries on each card 
- [x] Collect quotes/testimonials for projects (Moved to issue #2599)
- [ ] Add content about how agencies changed to cards

## Featured projects:
- [x] Update home page with new cards
- [ ] Rearrange cards on `what we deliver`

**Comment by awfrancisco** [comment]
I'll try to do this while @elainekamlley is out so they can work on it while I'm out.

**Comment by awfrancisco** [comment]
PR for updates of summaries https://github.com/18F/18f.gsa.gov/pull/2572

**Comment by awfrancisco** [comment]
Added tasks above for project page updates. 

[Spreadsheet to gather and track testimonials](https://docs.google.com/spreadsheets/d/1dvSsuZqnWzLsHSrCQcoGCe7dY5eUfx3t1j7bjWHVZCY/edit#gid=0)

**Comment by awfrancisco** [comment]
We should also prioritize [issues for new project pages](https://github.com/18F/18f.gsa.gov/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20project%20page) as part of this work

**Comment by elainekamlley** [comment]
Broke the bullets up into their own issues
