### ISSUE TITLE
Content audit of join pages

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2467]
Given that we're likely going to have some new job posts up soon, we should give the join content an audit. 

## Possible issues to address in audit

- Content matches current application process
- Tone matches current outreach, value prop, and talent research
- Content helps talent reach goals for applicants

## This is issue is done when:
- [ ] Current content is audited
- [ ] New issues filed to address findings of audit
- [ ] Interview talent to see if additional information needs to be added
- [ ] Research plan for flow and content (?)

**Comment by eddietejeda** [comment]
Being tracked here: https://github.com/18F/writing-lab/issues/386
