### ISSUE TITLE
Blog post image is too large

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2472]
## Expected Behavior
The image in [this blog post](https://18f.gsa.gov/2016/07/19/strategies-for-starting-your-own-writing-lab/) should be smaller and have text nearly wrap around it

## Actual Behavior
Image is huge and breaks up paragraph

## This is issue is done when:
- [x] Image is appropriate size

**Comment by elainekamlley** [comment]
closing with #2662
