### ISSUE TITLE
Content for Intro to job postings

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2477]
## Expected Behavior
A plain language introduction for each job posting will help applicants navigate the extensive amount of information. 

Example: 
> We are hiring a Talent Engagement Specialist to help us build an amazing team. This person will work with all of TTS to recruit, interview, evaluate, etc. This page includes key objectives for the role, as well as the official job description. For more information about how to apply, see Joining 18F.

## This is issue is done when:
- [x] content is written @awfrancisco 
- [x] Add to job descriptions @elainekamlley

**Comment by awfrancisco** [comment]
How's this?

Template

We're hiring a [job title] to [short, plain language job basics]. This person will work with [TTS team] to [three item list of duties]. This page includes key objectives for the role, as well as the official job description. You can apply at the bottom or learn more about the application process at Joining 18F.

Example:

We're hiring a Talent Engagement Specialist to help us build an amazing team. This person will work with all of TTS to recruit, interview, and evaluate potential candidates. This page includes key objectives for the role, as well as the official job description. You can apply at the bottom or learn more about the application process at Joining 18F.

**Comment by elainekamlley** [comment]
This is great! Added them to #2483
