### ISSUE TITLE
Content for thank you page

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2478]
## Expected Behavior
When you sign up for the 18F newsletter an email is sent to your email to confirm your subscription. When you click confirm from the email body, it should take you to `18f.gsa.gov/thank-you`

## Actual Behavior
Takes you to a 404 page 

## This is issue is done when:
- [x] Content for thank you page is drafted @awfrancisco 
- [x] Add page to the site @elainekamlley

**Comment by awfrancisco** [comment]
@elainekamlley Content is [here](https://docs.google.com/document/d/1WwXvK7x2IhQMPfxU9V8WghjZbiJCzYgVPlJB2d_0xEE/edit#). I think this should be good to go

**Comment by elainekamlley** [comment]
Closing with merging of #2480
