### ISSUE TITLE
Incorporate 18F's mission statement and value proposition

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2494]
18F has drafted a new mission statement and value proposition that describes our work and what we bring to our partner agencies. We will need to align the site content to this new language. 

How we know this is finished: 
- [x] **Content audit**
- [x] What we deliver
- [x] Home page
- [x] How we work
- [x] About 18F 
- [x] Contact
- [x] CTA box 
- [x] **Write new content for each page identified**

**Comment by awfrancisco** [comment]
I've got some draft content for this issue. Would love to get some reactions in a coworking session. It's all on a local branch at the moment.
