### ISSUE TITLE
Define terms we use for the site

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2497]
Inspired by a talk given by Abby Covert, we need to define terms and features we use on the site. 

## terms
- [x] Project cards
- [x] Project page
- [x] join page 
- [x] Side bar nav 
- [x]  Inquiries call to action (bar at the bottom of project pages) 
- [x]  blog card
- [x]  project page sidebar
- [x]  top banner text

## This issue is done when:
- [x] Make a full list of terms
- [ ] Create template for definitions 
- [ ] write definitions using template
- [ ] add new page to the style guide

**Comment by awfrancisco** [comment]
Additional terms

- Inquiries call to action
- blog card
- project page sidebar
- top banner text

**Comment by lsgitter** [comment]
Eric to sync up with Dahianna on this issue.

**Comment by lsgitter** [comment]
For the interviews, I took screenshots from the 18F site and highlighted various components and added labels. I then asked the interviewees "What name would you give this component and how would you define it?" Their answers are compiled here: https://docs.google.com/document/d/1EYbFOpB_3gNHy5Lp5LzSlXOD4HJej3Fe3Lv6_sjCyYI/edit?usp=sharing
The slides and screenshots can be found in this Google Drive along with a preliminary template for adding new terms: https://drive.google.com/drive/folders/1FK7Dp7MGwRAPunSGbzU4MsODqD2OLxOJ?usp=sharing
In terms of next steps, hopefully these notes can serve as the basis for creating a dictionary of components used on the site. I did notice that most of the interviewees used different terms to describe components than the ones listed in the ZenHub issue here: https://app.zenhub.com/workspaces/18fgsagov-573f0fc5cd9225ae72c87da4/issues/18f/18f.gsa.gov/2497

**Comment by lsgitter** [comment]
Next steps: synthesize information and create a dictionary for components of site

**Comment by Dahianna** [comment]
I added a summary of the findings to this doc: https://docs.google.com/document/d/1eVHtBhEQUZ2D7fyBLhh_AavtCxgTuTb8O-ko5rug3j4/edit?usp=sharing

**Comment by lsgitter** [comment]
@Dahianna will add terms to the wiki so engineers and designers will know what we call the assets.

**Comment by Dahianna** [comment]
https://github.com/18F/18f.gsa.gov/wiki/Terms-and-features-we-use-on-the-site
