### ISSUE TITLE
Finalize content for partnership playbook

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2501]
The partnership playbook is a key resource for partner agencies in making a decision to hire 18F. 

[Current site](https://partnership-playbook.18f.gov/)

## This issue is done when:
- [x] Finalize edits for the revised content
- [x] Sarah to review 
- [x] CPS to review
- [x] Make additional edits based on reviews

**Comment by awfrancisco** [comment]
[Partnership Playbook draft 1.1](https://docs.google.com/document/d/1hW6gHLC9Tx99f-cP7p-gu6m6lR1ydePraGPA-Ub_D-o/edit#heading=h.zba207q4r2ls)

**Comment by awfrancisco** [comment]
@smils Ready for your review. Probably an hour or so depending on the extent of changes.

**Comment by smils** [comment]
@awfrancisco  Did a substantial rewrite, based on the idea that we're going to start nearly all partnerships w/FEs. Also tried to make it a lot shorter (four pages would be nice in the final formatting, if possible). Could use a sanity check, at least.

**Comment by awfrancisco** [comment]
@smils Looks good to me. I think more revisions on ASF and FE/modular stuff might be necessary but this feels right to ship now. Do you need to take another look or is this ready for CPS? Anyone else we need to add to the review list?
