### ISSUE TITLE
Content audit for IAA process

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2503]
The IAA process can be a complicated set of tasks. We want to make this process clear and informative to our partner agencies who are ready to hiring us and need guidance on all the paperwork. 

[Current site](https://iaa-forms.18f.gov/)

## This issue is done when:
- [x] [Content audit](https://docs.google.com/spreadsheets/d/1RFGX9ArvuhgiW4bm7Og6Bx21hjcAG2scn6KyZ44HOGg/edit#gid=0) 
- [x] [Review agreements email sent to partners](https://docs.google.com/document/d/1-qR4e9He9kdRkNBv1EM8tGtU4TmvaWkfMNYOJgW3wdA/edit#heading=h.37abpqqznvz6)
- [x] [Interview expert IAA comms process ](https://docs.google.com/document/d/1rv3xf9USQDK7Of4lVrp3EXS5cjWFb_j5a-9cP4zsCCw/edit)
- [x] [IAA forms walkthrough](https://docs.google.com/document/d/1I0jB_Mwo9x1rHfJZACkiaknjsgMBwtGKuF1KHYc_ETU/edit)

**Comment by Dahianna** [comment]
IAA comms process expert interview schedule for 8/17 at 4:30pm ET

**Comment by elainekamlley** [comment]
Through the research the team has found that this information is better suited as marketing materials
