### ISSUE TITLE
HOLD: Add IAA content to site 

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2506]
The IAA process can be a complicated set of tasks. We want to make this process clear and informative to our partner agencies who are ready to hiring us and need guidance on all the paperwork. 

[Current site](https://iaa-forms.18f.gov/)

## This issue is done when:
- [ ] Add content to 18f.gsa.gov using `primary` layout (ex. 18f.gsa.gov/join) 
- [ ] Link page to partnership playbook  
- [ ] Redirects from current site to new site

**Comment by awfrancisco** [comment]
Holding on this while IAA working happens in marketing materials. After improving in-person/PDF process, we'll evaluate what materials to bring into the site.

**Comment by elainekamlley** [comment]
Closing for now, till we have a better idea on how we want to add this info
