### ISSUE TITLE
Remove accesslint-ci

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2522]
From AccessLint:
> With the release of the new GitHub App, we’ve deprecated accesslint-ci and, as of now, it will no longer comment on your Pull Requests. On October 1st we’ll also be revoking all tokens for the accesslint-ci bot. Please note that this has the potential to disrupt your CircleCI build. We suggest removing accesslint-ci as part of your build process.

This means that we will need to 
  - remove accesslint-ci from `_config.yml` 
  - potentially replace its functionality with the new-and-improved [AccessLint GitHub integration](https://www.accesslint.com/)

**Comment by lsgitter** [comment]
@apburnes do you have a sense if this is still a thing we need to do or how much of a lift it would be?

**Comment by apburnes** [comment]
The AccessLint GitHub integration looks like a good option but setting up the integration will need to be discussed with the Github admins.
