### ISSUE TITLE
Experiment with header for homepage buckets

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2556]
Per comments from @smils in #2551, let's test out ways to separate the 3 buckets on the homepage from the VP-type language so that it's clear to potential partners that these are broadly the areas where we work. Could be a header, different color of background, other design element, or a content change. 

## This is issue is done when:
- [x] Evaluation of possible solutions
- [x] Present recommendations to design and outreach
- [x] Push changes to dev

**Comment by elainekamlley** [comment]
Done (for now):
![screen shot 2017-11-02 at 11 21 22 am](https://user-images.githubusercontent.com/7362915/32334099-fa0ae2b4-bfbf-11e7-9451-64b268b235c6.png)
