### ISSUE TITLE
New visual representation of resources on contact page

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2557]
Hypothesis: Creating a more visual representation of the three resources in the sentence below would drive more site visitors to click through to these resources. We want potential partners to read these resources to understand our methods, funding constraints, and principles. 

>To learn more about how we work with agencies, see our principles, explore our Partnership Playbook, or learn about how we’re funded.

## This is issue is done when:
- [x] Investigate whether icons/images/etc are more likely to be clicked
- [ ] Draft possible visual treatments for these links
- [ ] Present recommendations to design and/or Outreach
- [ ] Push changes to dev

**Comment by awfrancisco** [comment]
Could be done in conjunction with #2490

**Comment by Dahianna** [comment]
[Research plan](https://docs.google.com/document/d/19gSpx0JUk5W-RnTkCpDBb6F3W_1ClTUmSuQb1XjFq-A/edit?usp=sharing)

**Comment by Dahianna** [comment]
Findings from researched done on the contact show that these resources are not necessary on the contact page. Check issue #2490
