### ISSUE TITLE
beta.fec.gov page is now live!

### ISSUE THREAD

**Issue by lauraGgit** [18F/18f.gsa.gov#2594]
## Expected Behavior

https://18f.gsa.gov/what-we-deliver/fec-gov/
Now that FEC.gov is live, let's remove the beta!

## Actual Behavior
Links and a number of mentions of the public beta which is now live.

## Steps to reproduce the behavior
- [ ]
- [ ]
- [ ]

## This is issue is done when:
- [ ] links go to the fec.gov
- [ ] the beta prefix is removed.
- [ ]

**Comment by awfrancisco** [comment]
Addressed in #2630. Closing
