### ISSUE TITLE
Collect testimonials from past partners for project pages

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2599]
Hypothesis: Including quotes or testimonials from past partners in project pages will help potential partners better understand our work and encourage them to contact us about potential projects. 

Quotes may be worked into the body of project pages or put in the sidebar. Still TBD. 

[Spreadsheet to gather and track testimonials](https://docs.google.com/spreadsheets/d/1dvSsuZqnWzLsHSrCQcoGCe7dY5eUfx3t1j7bjWHVZCY/edit#gid=0)

## Gathering testimonials

- [x] Gather 18F contacts for all project pages
- [x] Draft template text to reach out to past partners
- [x] Ask 18F contacts to send emails
- [x] Follow up with 18F contacts until all testimonials gathered
- [x] Edit testimonials  
- [ ] Add testimonials to site

**Comment by Dahianna** [comment]
[Testimonials](https://docs.google.com/a/gsa.gov/document/d/1TH0M3wDsLKPnd8u4vgY0bqGXyIAxCbLF7Q19MiPND4Y/edit?usp=sharing)

[Tracker for submissions](https://docs.google.com/a/gsa.gov/spreadsheets/d/1dvSsuZqnWzLsHSrCQcoGCe7dY5eUfx3t1j7bjWHVZCY/edit?usp=sharing)

**Comment by elainekamlley** [comment]
Testimonials have been collected and will continue to be collected in the future. This issue is finished and will break out editing and adding to the site to another issue.
