### ISSUE TITLE
Analytics for What we deliver 

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2601]
Acceptance criteria
- [x] Report covers conversion rate from project page to contact 18F last 2 months
- [x] Project pages featured on the home page conversion rate to contact last 2 months
- [x] Contact us conversion rate to email 18f
- [x] How much contact pages come from project pages
- [x] What is the most visited project pages 
- [x] Bounce rate from what we deliver page 
- [x] Bounce rate from individual project pages 

--- 
After review of analytics report:
- [x] setting goal metrics on areas on where we want to improve 
- [ ] Create a more in depth user research plan on why some of the trends are happening

**Comment by awfrancisco** [comment]
[Notes](https://docs.google.com/document/d/1jGd7AkVoZsTXqBUuXX9Fsho9zQ1wI4qtNrLiWSc389g/edit#heading=h.dlipnlp85xkj)

**Comment by Dahianna** [comment]
Added 18F inquiries email data to the [doc](https://docs.google.com/document/d/1jGd7AkVoZsTXqBUuXX9Fsho9zQ1wI4qtNrLiWSc389g/edit#)

**Comment by elainekamlley** [comment]
After analyzing the last three months of analytics we have determined this goal: 

Increase traffic to contact page from DC, VA, MD that goes to the contact page since ~80% of our business is from people in those states.

**Comment by elainekamlley** [comment]
Created issues as a result of the analytics research. Closing this due to the creation of next steps
