### ISSUE TITLE
Hero image on blog posts pushes article content below the fold

### ISSUE THREAD

**Issue by esgoodman** [18F/18f.gsa.gov#2604]
## Expected Behavior
I would like to be able to skim the first paragraph of the blog post without scrolling. Honestly, I don't know if it's really a problem but it did feel like we weren't making as good use of that top screen real estate as we could be. I like the graphic, but maybe a different image would feel like a more meaningful use of that space? 

## Actual Behavior
The height of the hero image on the blog post moved the first paragraph below the fold. 

## Steps to reproduce the behavior
- [ ] Open https://18f.gsa.gov/2017/11/08/four-lessons-we-learned-while-building-our-own-design-research-recruiting-tool/ on a Mac laptop with the window at less than full screen height

## This is issue is done when:
- [ ]
- [ ]
- [ ]

**Comment by eddietejeda** [comment]
Thanks for reporting this. We resolved this in the most recent pull request.
