### ISSUE TITLE
update FEC repo link

### ISSUE THREAD

**Issue by LindsayYoung** [18F/18f.gsa.gov#2607]
We are linking to a deprecated repo openFEC-web-app on this page https://18f.gsa.gov/what-we-deliver/fec-gov/

active repos are:
FEC: a general discussion forum. We compile feedback from the FEC.gov feedback widget here, and this is the best place to submit general feedback.
openFEC: the first RESTful API for the Federal Election Commission
fec-eregs: the FEC's new Code of Federal Regulations explorer
fec-cms: the content management system (CMS) for the new FEC.gov
fec-proxy: the proxy application to manage and route requests coming to the new FEC.gov site
swagger-ui fork of swagger for API documentaion
fec-infrastructure: manages the gov cloud RDS instances 

If you only link to one you might want to link to https://github.com/18F/FEC

**Comment by DeathCamel57** [comment]
I hope that #2609 helps @LindsayYoung!

**Comment by LindsayYoung** [comment]
Thanks!

**Comment by elainekamlley** [comment]
@LindsayYoung reopened this since we are going to do some updates to the full body of the project page. We want to make sure that the language is aligned with the new phase.

**Comment by LindsayYoung** [comment]
Update: we have move the repos to the FEC's github org- it's a great!!!

Here are the relevant repos for the project
- [FEC](https://github.com/fecgov/fec): a general discussion forum. We [compile feedback](https://github.com/18F/fec/issues) from the FEC.gov feedback widget here, and this is the best place to submit general feedback.
- [openFEC](https://github.com/fecgov/openfec): the first RESTful API for the Federal Election Commission
- [fec-eregs](https://github.com/fecgov/fec-eregs): the FEC's new Code of Federal Regulations explorer
- [fec-style](https://github.com/fec-gov/fec-pattern-library): shared styles and how to use interface components
- [fec-cms](https://github.com/fecgov/fec-cms): the content management system (CMS) for the new FEC.gov
- [fec-proxy](https://github.com/fecgov/fec-proxy): the proxy application to manage and route requests coming to the new FEC.gov site
- [fec-infrastructure](https://github.com/fecgov/fec-infrastructure): manages the gov cloud RDS instances
