### ISSUE TITLE
Have a better connection to join from contact

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2623]
Need to iron out what this means but analytics show that the main pages that our users visit are `join` and `contact`. We want to make sure that folks are reaching us the way they want to.

**Comment by awfrancisco** [comment]
About [16% of traffic](https://analytics.google.com/analytics/web/#report/content-pages/a48605964w80166384p82926493/%3F_u.date00%3D20170601%26_u.date01%3D20171226%26_r.tabId%3Dnavigationsummary%26_r.drilldown%3Danalytics.pagePath%3A%2Fcontact%2F/) goes to the join page from the contact page. Second only to the about page. Hypothesis: People looking to apply to 18F are going to contact and then leaving for join when they find it isn't the right place. Providing a better path might help those users.
