### ISSUE TITLE
Change "About 18F" to "About"

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2646]
The current page title "About 18F" feels redundant and unlike other about pages on other sites. Changing it to "About" will be clearer and shorter. This change will not require redirects.

## This is issue is done when:
- [x] Change `About 18F` to `About` in navigation and headings, where appropriate. Here is a [list of all instances](https://github.com/18F/18f.gsa.gov/search?utf8=%E2%9C%93&q=%22about+18f%22&type=) of the phrase, though many (such as blog posts) don't need to be changed.

**Comment by elainekamlley** [comment]
close with the merge of #2654
