### ISSUE TITLE
Reformat What we deliver page

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2667]
Goal: Based on the decision of #2666, reconfigure in code the layout of the page

Tasks:
- [x] Adjust liquid templating to render different groups based on their category
- [x] Determine style of category
- [x] Write new headers

**Comment by awfrancisco** [comment]
Suggested order for project cards, broken up by row. What do you think?

**Services**
FBI
FEC
CALC

Data Act
State and Local
ePermits

College Scorecard
America’s Seed Fund
myUSCIS

USWDS
Wage and Hour
C2

**Products**
Cloud
Federalist
Login

Agile BPA
eRegs

**Comment by awfrancisco** [comment]
[Draft content for new section headers](https://docs.google.com/document/d/11VPbnaYUxNc6F4eodMWBxEYGnhF8nOsZUIYQdYy1tg8/edit)
