### ISSUE TITLE
Determine image requirements for project pages

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2668]
Goal: Standardize project page images. This provides guidance to the team and a more cohesive design for What we deliver page. Be simple and lightweight. Adding images should be a task that any team member can do. 

Tasks: 
- [ ] Have a site cowork session cover this topic and invite a designer
- [ ] Write out guidelines and add them to the style guide

Questions: 
- We have a mix of media on the project pages from images to logos to icons. Do we want to continue with a diversity of formats or be more homogenous on the type of image?
- Projects and platforms have various levels of branding. Some are heavily branded by the partner agency or it is a platform looking to establish its own identity, some have none at all. What are our guidelines on adding the various levels of brands into What we deliver?

**Comment by elainekamlley** [comment]
For consideration: each image has same treatment

**Comment by lsgitter** [comment]
@Dahianna is this something we want to to do sooner rather than later? If we want to do it soonish this could dovetail with the conversation on the process for using 18F folks on the bench.

**Comment by Dahianna** [comment]
I don't think this is an issue anymore since we no longer use icons, but it'll be good to create some guidelines.
