### ISSUE TITLE
Research the services pages of other companies to inform renaming

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2672]
With the new content for the How We Work page, it might be appropriate to also rename the pages to something like Services. We should research similar pages on private contractor websites to see what patterns federal employees might recognize. 

Tasks
- [x] Write up brief hypothesis and research plan on goals, tactics, expected outcome
- [x] Research 3-5 private IT contractors for how their websites talk about their services
- [x] Compile the research into recommendations

**Comment by awfrancisco** [comment]
@Dahianna Do you have time to take this on next week?

**Comment by Dahianna** [comment]
[Research plan](https://docs.google.com/document/d/1K0uYSmli7avM0DO_WMhwOkWrA4QIxz7Cj9hof4ZwEy4/edit?usp=sharing)
