### ISSUE TITLE
Change project card names to descriptions

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2673]
Project page cards currently use the project name as the title (for example, College Scorecard) which may be confusing or unhelpful for new users or those unfamiliar with 18F's work. 

Hypothesis: Changing the title to a brief description of the impact of the work (such as the current subtitle field) might make it easier for people to understand what projects are about and better understand 18F's work. 

Concerns: Space is tight on project cards and descriptions would have to be short. Might need to adjust the design of the cards to include agency or some other additional information. 

Tasks

- [x] Prototype a new what we delivers with descriptive titles
- [ ] Test the prototype and current version for design, readability, and with new users
- [x] Add product name to agency field on project cards
- [x] Update "see our work" field to url with not HTTPS for all cards

**Comment by awfrancisco** [comment]
Sample of project pages with descriptions instead of titles. Thoughts? 
![project-page-descriptions](https://user-images.githubusercontent.com/12051887/36617994-0df50f28-18af-11e8-9f1a-70bbdf2cfc52.jpeg)

**Comment by smils** [comment]
Really like the direction you've take this. 👍 @awfrancisco
