### ISSUE TITLE
Redirect to new hiring site

### ISSUE THREAD

**Issue by afeld** [18F/18f.gsa.gov#2681]
## Expected Behavior

When I visit https://18f.gsa.gov/join/, I should be redirected to https://join.tts.gsa.gov/. The latter is ["the new home for all TTS job postings"](https://18f.gsa.gov/2018/02/21/technology-transformation-services-launches-new-job-site/).

## Actual Behavior

There's a different (older) page that provides similar information.

/cc @rooneywp @JennMoran

**Comment by JennMoran** [comment]
@afeld I don't think it should redirect them to the TTS site as the TTS site redirects them to the join18F site under the "TTS offices" section, if a candidate wants to learn more about 18F. The 18F join page explains the hiring process specific to 18F and it also links them to the 18F website. 
on the 18F join page we should probably mention something about the TTS website like "to learn more about our parent org and other offices within it go here.."

**Comment by afeld** [comment]
Ah, didn't realize both were still going to exist. I think that may be confusing to applicants and annoying to have to keep the two (sub)sites in sync, but that's out of scope for this issue 😁
