### ISSUE TITLE
Switch code from MailChimp to new mailing platform 

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2687]
We are moving off of mailchimp and need to add new code to the newsletter sign up form

**Comment by awfrancisco** [comment]
We've replaced the Mailchimp signup with a temporary Google Form sign up until we procure newsletter software.

**Comment by eddietejeda** [comment]
We should get the sign up code for the contact page by Oct. We will check in on this then.

**Comment by Dahianna** [comment]
New code can be found [here](https://docs.google.com/document/d/1YZ_J0z_YWfsPXK4z4Aj_fMr8D4DZ6S7Y7-X03tt-XCg/edit#heading=h.z0udyh6s630m)

**Comment by awfrancisco** [comment]
We have the new embed code. This is ready to be added to the next sprint.

**Comment by Dahianna** [comment]
The code for the box is also in this [doc](https://docs.google.com/document/d/1YZ_J0z_YWfsPXK4z4Aj_fMr8D4DZ6S7Y7-X03tt-XCg/edit#)
