### ISSUE TITLE
Pull analytics of contact us info from the last two months

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2701]
Pathways for users to the `contact us` page increased in previous sprints. Our hypothesis for this work would increase potential customers to contact us. This issue is to pull from our analytics to see any increase in emails. 

Issue is finished: 
- [x] This template is filled out: [18f.gsa.gov analyticis 12/18 - 2/18](https://docs.google.com/document/d/1TCUYBCv09Mrck5US5iAQIU7RE3z_I1O0lhXnSLBReJ4/edit?usp=sharing)

**Comment by awfrancisco** [comment]
Added analytics and analysis at the link above. tl:dr Many of the stats are down from the last period, but I'm not convinced it's directly tied to site changes. I suspect outside forces around the budget and our blog post publishing rate are more likely to blame for reduced traffic.
