### ISSUE TITLE
Redirect guides 

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2702]
Steps: 

- [ ] For closed guides, redirect them to the retired GitHub repo

**Comment by elainekamlley** [comment]
Unfortunately, this is not a simple one. The instructions involve updating four different files in two different repos. [Here](https://docs.google.com/document/d/1Qx9ChOtz1SADUadsPkuJsbcrJGv49LEadrkTlJDqVWo/edit?usp=sharing) are the instructions. Will offered to help us out but blocking some time to walk us through it. I can do this when I return on the 24th or this can be picked up by another team member.

**Comment by eddietejeda** [comment]
In progress here: https://github.com/18F/pages-redirects/commit/688169735d469963ddc56c1a14e4bd8e885d0e68

**Comment by awfrancisco** [comment]
Update sent out to team about redirects

**Comment by eddietejeda** [comment]
This is done https://github.com/18F/dns/commit/9cf3513336d097c63abbe4e5b2441114525847ab
