### ISSUE TITLE
Generating a research plan for How we work

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2703]
Is the text too long? Does the content make sense?  Draft research plan for investigating the `How we work` page. 

**Tasks**
- [x] Draft a research plan (hypothesis, methods, timeline and recruitment email)
- [x] Recruit participants
- [x] Conduct studies
- [x] Analyze findings and write out results

**Comment by Dahianna** [comment]
[Research plan](https://docs.google.com/document/d/1lGzglS81K4644HrUAhy_c-30az2wXeqGQXQOTCaBLJE/edit?usp=sharing)

**Comment by Dahianna** [comment]
Analysis: https://trello.com/b/BS7tZIGG/site-content-what-we-deliver-how-we-work
Findings report: https://docs.google.com/document/d/1uqA5yc8-oWdLSrwzDmyxXkVl5weRivM7-Wj1m89vh1o/edit#
