### ISSUE TITLE
0% bounce rate error on some project pages

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2723]
Two project pages ([DOL Wage and Hour](https://18f.gsa.gov/what-we-deliver/dol-wage-and-hour/) and The New Ten (no longer live)) show a 0% bounce rate in Google Analytics. Both pages had traffic, entrances, and exits. I believe this stat is a bug. I found some additional information [here](https://www.togetherdigital.ie/blog/why-0-bounce-rate-is-not-good-news). 

[Analytics report showing bounce rate of project pages](https://analytics.google.com/analytics/web/#/report/content-pages/a48605964w80166384p82926493/_u.date00=20180101&_u.date01=20180405&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22~2Fwhat-we-deliver~2F%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Fpreview%22,1%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Fsite~2F%22,1%5D%5D/)

## This is issue is done when:
- [ ] All project pages show a reasonable bounce rate

**Comment by lsgitter** [comment]
not enough resources to work on at this time.
