### ISSUE TITLE
Reevaluate list of agencies we've worked with

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2732]
The current list is on `what-we-deliver`. Based on research, they expect to see the list sooner. We can either move it higher up on the `what we deliver` or added to the homepage

**Comment by Dahianna** [comment]
Design lab issue: https://github.com/18F/design-lab/issues/49

**Comment by Dahianna** [comment]
From research findings:

>  ...after looking through the “What we deliver” page, participants were happy to find the list of agencies. But they wished it was visible sooner without having to scroll further down the page.
"Not seeing anything for that [past partnerships] from the homepage” - State of Washington Employee"

**Comment by Dahianna** [comment]
New designs for homepage and what we deliver are on the design lab issue. Now we just need to implement
