### ISSUE TITLE
Replace "Under Review" Code of Conduct text w/ approved revision

### ISSUE THREAD

**Issue by jeanninehunter** [18F/18f.gsa.gov#2746]
Replace the ["Under Review" statement](https://18f.gsa.gov/code-of-conduct/) on 18F website with revised and vetted [Code of Conduct](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md).

**Comment by jeanninehunter** [comment]
[Pull request](https://github.com/18F/18f.gsa.gov/pull/2747) ready for review

**Comment by awfrancisco** [comment]
Completed in #2747
