### ISSUE TITLE
Explore design elements for How we work

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2749]
Based on our research, informative graphics that help our users understand how we can help agencies are needed. 

## Research Recommendations
- Include a timeline, preferably a graph, on the [18F partnership process](https://docs.google.com/document/d/1hUV8Fyc3W8GVpFyAyNyFkvDxAYMU48CxwiKAKzBi66w/edit?usp=sharing)
- Decrease the amount of text by creating graphics that explain the services or breaking down the text using bullet points.

## This is issue is done when:

- [x] Review partnership timeline with AP and CPS
- [x] Create a mockup of the timeline graph and get approval
- [x] Submit request to [design-lab](https://github.com/18F/design-lab)
- [x] Review graphic with designer
- [x] Submit approved design to developer

**Comment by Dahianna** [comment]
## Research Recommendations
- Include a timeline, preferably a graph, on the 18F partnership process
- Decrease the amount of text by creating graphics that explain the process or breaking down the text using bullet points.

**Comment by Dahianna** [comment]
[Here's](https://docs.google.com/presentation/d/1rq9ZRGva1EYRW9CTITkUo_sI8y4xTE90ORtYrkfwyh8/edit?usp=sharing) a very rough concept for the process graph

**Comment by Dahianna** [comment]
Here's a [doc](https://docs.google.com/document/d/1hUV8Fyc3W8GVpFyAyNyFkvDxAYMU48CxwiKAKzBi66w/edit?usp=sharing) with the process. Feel free to edit as necessary.

**Comment by eddietejeda** [comment]
Want to follow up with designers?

**Comment by eddietejeda** [comment]
We working with Aviva on this... More information later.

**Comment by Dahianna** [comment]
Design lab [issue](https://github.com/18F/design-lab/issues/18)

**Comment by eddietejeda** [comment]
We will revisit in October.

**Comment by Dahianna** [comment]
Aviva is moving to a full-time project, so we are waiting for a new designer from the lab
