### ISSUE TITLE
Path Analysis project pages

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2753]
Write a handful of project pages about Path Analysis projects. 

The current project pages only cover larger projects. Highlighting the value of a Path Analysis could help potential partners learn more about our services and determine if they fit their needs. These project pages could be featured in a future design of the How we work page. 

Potential PAs for case studies

- State Diamonds
- DOJ Litigation
- NSF CMS
- Army Cyber

[Full list of PAs](https://docs.google.com/spreadsheets/d/15i2HXu5UI0s82Yr-2uEc3Yy_UZ0sYtB7ncjAIMLR0w4/edit#gid=0)

**Comment by eddietejeda** [comment]
@Dahianna can you break this apart into smaller issues?
