### ISSUE TITLE
Find blog posts to highlight

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2769]
Review existing blog entries and identify a couple of "best of" groupings.  Propose the grouping names and the specific posts.

A few possible groupings may include:
- “Post from our partners”
- “Popular posts”
- “Examples of lasting impact”

Work with @Dahianna to identify popular posts.

**Comment by awfrancisco** [comment]
[Draft categories and blog posts](https://docs.google.com/document/d/1s1AZYCxR7VW557evmC_g1h4D7SBTJjniyNMfuW5_nkY/edit)

**Comment by awfrancisco** [comment]
The link above has a number of possible categories with 3 top blog posts for each category and some alternatives. Thoughts welcome.
