### ISSUE TITLE
Identify key metrics to measure success in blog

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2770]
Reach out to DAP team to learn about the site's analytics. Identify metrics used to measure success of blog posts. 

Key metrics may include:
- popular posts
- most linked/shared
- breakdown of readers coming from gov domain vs public
- time on post

Provide team with examples of metrics and specific blog posts. We will then use these metrics as baseline and see what changes as we make improvements to site.

**Comment by Dahianna** [comment]
After doing some research, I created this [list](https://docs.google.com/document/d/1Vi0ANzygsysnhXFJSU3Rb8d6ArZCxgXPOb67kmKy2Eg/edit) of metrics for the blog. Most of these should be available on Google Analytics. Andre and I will work on gathering this information.

**Comment by Dahianna** [comment]
The doc is updated with the relevant metrics and how we are going to use them.

**Comment by Dahianna** [comment]
I've added the numbers for the blog to contact conversion for gov traffic
