### ISSUE TITLE
Propose design examples for highlighting blog entries

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2771]
We want to highlight successful blogs on the front page. Review examples of designs that may work for 18F site.

- [x]  Propose examples to 18F website team
- [ ]  Identify which 18F member can help implement design changes

**Comment by Dahianna** [comment]
I looked at blogs from other civic tech and fed tech consulting organizations, and they seemed to follow one of these two formats:
- [Design 1](https://docs.google.com/drawings/d/1WyIWDoLJNgamGHmcD_ISWv2jmGGA0cZ7v6bkK2Q8ZVU/edit)
- [Design 2](https://docs.google.com/drawings/d/1ZCkpUtQyKcJ5eDZso7ypI9JCjDFJQv5T4thnvU1YuOw/edit)

After looking at those examples, I came up with this [proposal](https://docs.google.com/drawings/d/17BltUYGz9POTh7UngNUm4LzjTyve84d1fLQHzEtQr7M/edit)

**Comment by eddietejeda** [comment]
Looks good! Lets discuss what "feature posts" means and how we will use it to track our key metrics.

**Comment by awfrancisco** [comment]
Playing around with [another version](https://docs.google.com/drawings/d/1PFDauXQQaTULOGs_eCzuY9yemJ2-4xW7PYku6x8uqA8/edit)

**Comment by Dahianna** [comment]
Added screenshots from the site to the version above to improve the mock-up

**Comment by eddietejeda** [comment]
@awfrancisco What do you think of linking to categories instead of specific posts?

**Comment by awfrancisco** [comment]
That's fine with me, but we should probably create new categories specifically for the homepage, tag old posts, and then use them to highlight especially good ones going forward.
