### ISSUE TITLE
Project page: State Diamonds

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2776]
Write a project page about the Path Analysis and build of the new [USKPA.org](https://www.uskpa.org/) (United State Kimberley Process Authority). 

Emphasis should be on the flexibility of the Path Analysis, mission of the project, and large change from a small technical engagement. 

More info here 
https://docs.google.com/document/d/1nxkxgO3264PNq3mUH-xCa6_2rO5oLRLrkpVMOdg43TQ/edit#heading=h.gckw2p1z0uh1

**Comment by Dahianna** [comment]
Here's the draft: https://docs.google.com/document/d/1V5Cz67Ftsg4-14zKKkzpzicTpTMYoGuG9D-Rz9wLgBY/edit?usp=sharing

**Comment by eddietejeda** [comment]
Closed https://github.com/18F/18f.gsa.gov/pull/2961

**Comment by Dahianna** [comment]
Merged #2961
