### ISSUE TITLE
Search results return some blank entries

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2777]
## Expected Behavior
When a user enters a search term, they get links related to that term

## Actual Behavior
For some search terms (such as `software`), a portion of the search results are blank lines. For example:

![18f-search](https://user-images.githubusercontent.com/12051887/40808838-1572d196-64ee-11e8-9138-3f5522d3f881.jpeg)

## Steps to reproduce the behavior
- [ ] Enter `software` in the search bar

## This is issue is done when:
- [ ] Search results return lists with items on each line

**Comment by eddietejeda** [comment]
I noticed this yesterday as well. Is this new behavior?  I can investigate.

**Comment by awfrancisco** [comment]
I don't think I've seen it before. Did you notice it with another search term?

**Comment by floresam** [comment]
I noticed this while searching "blog"
![image](https://user-images.githubusercontent.com/15929779/41120413-71b0d64a-6a63-11e8-8722-2d038bab3e2c.png)

**Comment by eddietejeda** [comment]
This is resolved in #2786
