### ISSUE TITLE
Organize card sorting session for creating tags

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2793]
## Expected Behavior
As a vistor to 18f blog, I want to be able to read the best content organized by key topics and categories. To determine what these categories are, we will need to organize session with users to see what the best labels are.

## This is issue is done when:
- [x] Draft [research plan](https://docs.google.com/document/d/1s1AZYCxR7VW557evmC_g1h4D7SBTJjniyNMfuW5_nkY/edit#) and create categories
- [x] Reach out to OPP to borrow Optimal workshop for card sorting exercise
- [x] Create card sorting exercise
- [x] Share link to exercise with potential testers through listservs
- [x] Identify best tags
~Begin implementing tags into site.~ Moved to it's own issue

**Comment by Dahianna** [comment]
I've updates this [doc](https://docs.google.com/document/d/1s1AZYCxR7VW557evmC_g1h4D7SBTJjniyNMfuW5_nkY/edit#) to include the research plan

**Comment by Dahianna** [comment]
[Preview](https://usagov.optimalworkshop.com/optimalsort/n0i73tt0) for the card sorting exercise

**Comment by awfrancisco** [comment]
@Dahianna will we have enough data from this to choose the best tags on Tuesday before sprint planning?

**Comment by Dahianna** [comment]
The card sorting exercise was closed today, and you can see the results [here](https://www.optimalworkshop.com/optimalsort/usagov/n0i73tt0/shared-results/p288w2s31yhh3ctxuj12bhb423q5lb57). The TLDR is as follows:

We had 110 participants who completed the questionnaire and exercise with the following results:

- **Lessons learned** - 94%
- **Modern practices** - 93%
- **What not to do** - 84%
- **Convincing stakeholders** - 82%
- **Culture change** - 81%
- **Getting buy in** - 81%
- **U.S Web Design System** - 75%
- **Product launch** - 53%
- **Government software design** - 49%
- **Lessons in contracting** - 37%

**Comment by eddietejeda** [comment]
Based on the results, we've selected the following tags:

- Lessons learned
- Modern practices
- Convincing stakeholders
- Culture change
- Product launch
