### ISSUE TITLE
Work with design team to implement changes to blog

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2794]
## Expected Behavior
As a visitor to the site, I want to see the most recent blog post and have visibility into other top posts that show me what 18F does.

Based on our research, we developed mockups that help accomplish this goal. Now we need to begin implementing.

## This is issue is done when:
- [x] [Draft ](https://docs.google.com/document/d/1aM1OPHo-g7P-gv3tPI9DQLwSsjQ9lUbAidjGS26uOMA/edit)issue request
- [x] Submit request to the [design-lab repo](https://github.com/18F/design-lab)
- [x] Set up time to discuss design changes
- [x] Update request with any changes
- [x] Schedule call with Austin to review design changes
- [ ] Work with design lab to implement changes

**Comment by awfrancisco** [comment]
Looks like the design lab is a little backed up. We might not get a design back during this sprint, but we'll get the ball rolling.

**Comment by Dahianna** [comment]
Design lab mockups https://github.com/18F/design-lab/issues/17

**Comment by awfrancisco** [comment]
@hbillings Is on for this one. I think we can close and track this in the issues she is going to open.
