### ISSUE TITLE
Add caching headers to /assets

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#280]
As [recommended](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2F18f.gsa.gov&tab=desktop), add cache expiration headers to `/assets/`.

**Comment by gboone** [comment]
@18F/federalist-admins do we know if this is something cloudfront can accomplish?

**Comment by konklone** [comment]
So this is actually supported now:

![screenshot from 2016-09-03 15-27-07](https://cloud.githubusercontent.com/assets/4592/18227219/f02f5a1e-71ea-11e6-9fd5-690ae08abf36.png)

However, as you can see it's only instructing clients to cache the resource for 60 seconds, which is not very long. I'd recommend a much longer cache lifetime, with the understanding that when you deploy CSS/JS changes, you'll have to expect that clients won't see those changes until up to the length of the cache time.
