### ISSUE TITLE
Remove dates from blog excerpts on project pages

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2800]
Old dates on the blog posts at the bottom of project pages can give the impression that the site is outdated, even if there are new blog posts published elsewhere. 

## This is issue is done when:
- [x] Update the template for blog excerpts on project pages to remove the date field

**Comment by Dahianna** [comment]
I found the template for the project pages https://github.com/18F/18f.gsa.gov/blob/master/_layouts/project-page.html @hbillings can we fix it by just deleting **line 155** _post_date=post.date_?

**Comment by hbillings** [comment]
@Dahianna Yes! You'll want to remove it on line 155 there, and also remove [line 9 of `_includes/related-posts.html`](https://github.com/18F/18f.gsa.gov/blob/master/_includes/related-posts.html#L9). I *think* that should work (and if for some reason removing line 155 of `_layouts/project-page.html` breaks something, removing just line 9 of the related posts template should do the trick).

**Comment by Dahianna** [comment]
Removing the date line from both of these files didn't work. I'll keep investigating @hbillings

**Comment by eddietejeda** [comment]
I can take a look here as well.

**Comment by eddietejeda** [comment]
Merged #2856
