### ISSUE TITLE
Broken link to FDA resume template

### ISSUE THREAD

**Issue by LSummers33** [18F/18f.gsa.gov#2802]
## Expected Behavior
URL opens to PDF of FDA resume template in another browser tab.

## Actual Behavior
URL currently returns following response: 

    Content Server Request Failed
    Unable to download 'UCM279014'. Unable to find latest released revision of 'UCM279014'.

## Steps to reproduce the behavior
- On a web browser visit https://18f.gsa.gov/join/#government-style-resumes
- Click on link "Food and Drug Administration (FDA)’s Federal Resume Template"
- Clicking on above link takes you to the following broken link: https://www.fda.gov/downloads/AboutFDA/WorkingatFDA/UCM279014.pdf

## This is issue is done when:
- URL is updated or broken link is removed

**Comment by awfrancisco** [comment]
Thanks for filing this issue @LSummers33! We'll work on getting that content updated.
