### ISSUE TITLE
Gzip compression in transport for /assets/

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#281]
Set up gzip in nginx for assets, [as recommended](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2F18f.gsa.gov&tab=desktop).

**Comment by gboone** [comment]
@18F/federalist-admins is this something Federalist/CloudFront can handle? see also #280

**Comment by konklone** [comment]
This is supported now:

![screenshot from 2016-09-03 15-27-07](https://cloud.githubusercontent.com/assets/4592/18227222/28d4b58a-71eb-11e6-85f2-65c921604efa.png)
