### ISSUE TITLE
Fix metadata for Twitter cards

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2816]
## Expected Behavior
Tweets with links to 18F blog posts should show the correct headline of the blog post and a large image if available. 

## Actual Behavior
The Twitter card pulls a small image and a generic title for the 18F site, though it does include accurate excerpt text. 

Example https://gsa-tts.slack.com/archives/C02QNKTNK/p1531239132000028

[Twitter card validation tool](https://cards-dev.twitter.com/validator) to test solutions

**Comment by eddietejeda** [comment]
Eddie will investigate
