### ISSUE TITLE
Project Page: NSF Brand Principles 

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2818]
A new project page on our work with the National Science Foundation to help them develop brand principles. We already have [another project page](https://18f.gsa.gov/what-we-deliver/seed-fund/) about a separate NSF project.

[Draft of new project page](https://docs.google.com/document/d/16uT7Jip6uFvxaf5t_I11FXoKPjvPIXLOIoA_igSx01g/edit#heading=h.yak0e3ymzg61) by @kategarklavs 

## This issue is done when:
- [x] Edit draft
- [x] @ominina gets approval from the partner on the draft language
- [x] Write sidebar content
- [x] Find/create image
- [x] Connect to other NSF page?
- [x] Convert to Markdown
- [x] Publish

**Comment by hannahkane** [comment]
I'm asking the designer on the project for an image, and @ominina is going to ask the partner for a quote and to review the draft language.

**Comment by ominina** [comment]
sent to the partner for approval, might have to wait until the government reopens for a response since NSF is likely furloughed.

**Comment by hannahkane** [comment]
@Dahianna and @eddietejeda - do you think this image will work? 

![cropped](https://user-images.githubusercontent.com/8389648/51198939-6d5f9b80-18aa-11e9-97e4-a948b3423df2.png)

**Comment by Dahianna** [comment]
Looks good to me!

**Comment by hannahkane** [comment]
@ominina - do you think it would be appropriate to ping the partner on this now?

**Comment by ominina** [comment]
@hannahkane sent the partner another ping and made sure you were cced

**Comment by hannahkane** [comment]
@eddietejeda @Dahianna - the partner made some content changes. I added their edits to the document. What do you think?

**Comment by eddietejeda** [comment]
Comments are in document.

**Comment by hannahkane** [comment]
@Dahianna - do you need me to do anything else on this one, or are we good to move into production?

**Comment by Dahianna** [comment]
Yes we can move into production, we can add the quote later

**Comment by eddietejeda** [comment]
@Dahianna Will now convert the content to markdown and begin the publishing process.

**Comment by Dahianna** [comment]
https://github.com/18F/18f.gsa.gov/pull/2999

**Comment by Dahianna** [comment]
https://18f.gsa.gov/what-we-deliver/nsf-brand-principles/
