### ISSUE TITLE
Implement new layout for blog page

### ISSUE THREAD

**Issue by hbillings** [18F/18f.gsa.gov#2824]
The [new blog design](https://github.com/18F/design-lab/issues/17#issuecomment-402828003) ...
- [x] requires a sidebar layout instead of the existing full-page one.
- [x] moves the search bar out of the header into the sidebar.
- [x] adds new lines of content to the header.
- [x] adds a footer with a "get in touch" call to action.

**Comment by awfrancisco** [comment]
Potential blog tag lines

A view from the inside of 
technology modernization

Bits, bytes, words, and lessons
from 18F’s partnerships

What we delivered and what we
learned in the process

**Comment by eddietejeda** [comment]
For now, lets go with:

"A view of how we 
deliver civic technology"
