### ISSUE TITLE
Add topics, popular articles & social media to sidebar

### ISSUE THREAD

**Issue by hbillings** [18F/18f.gsa.gov#2825]
The [new blog design](https://github.com/18F/design-lab/issues/17#issuecomment-402828003) contains...
- [x] a hard-coded list of topics.
- [x] a hard-coded list of popular articles.
- [ ] social media icons.

**Comment by hbillings** [comment]
@eddietejeda @awfrancisco is this content ready?

**Comment by awfrancisco** [comment]
Not yet, but we can add them to the next sprint.

**Comment by awfrancisco** [comment]
[Here's a doc](https://docs.google.com/document/d/1pZzbcT288UyyjHUfpkn63CkNQwJjtAUlFyguS_7IgWA/edit) with the topics, popular articles, and social media icons. They should all be listed in the order they are listed in this doc. The `convincing stakeholders` and `product launch` topics/tags do not exist yet, but I'll get on that. But this is the list if you want to add it to the new design.

**Comment by awfrancisco** [comment]
Once #2870 is merged, this content is ready go into the new blog design.

**Comment by eddietejeda** [comment]
Hi @hbillings. How is this looking? Ready for merge?

**Comment by hbillings** [comment]
I don't know where the social media icons in the mockup are from, still.

**Comment by maya** [comment]
_Chiming in as I have some time..._ 

It looks like the social media icons are in this [Sketch file](https://github.com/18F/design-lab/files/2167943/blogSketch-ah.zip).

**Comment by maya** [comment]
Done in #2887.
