### ISSUE TITLE
Optimize images more routinely

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#283]
OK, I'm coming around to optimizing images where possible, since @waldoj and [Google](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2F18f.gsa.gov&tab=desktop) are both yelling at me. Site build is one solution, but it seems needlessly wasteful to keep re-compressing.

One interesting idea - build an image compression detection script into the Travis build command, and provide a simple command to run to quickly address failed builds and rectify them.

**Comment by gboone** [comment]
Related to #1800, another consideration for this is doing it _before_ we first commit the images so we don't have duplicate (if smaller) copies of the images lying around in the commit history.
