### ISSUE TITLE
Update Ruby

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2840]
We need to update the site to the newest version of Ruby.

## This issue is done when:
- [ ] Update site to newest version

**Comment by Atul9** [comment]
@Dahianna I have opened up a PR for this #2871

**Comment by eddietejeda** [comment]
Thanks for the pull request @Atul9! We're fixing a few tests that are failing due to this update. Will merge when we fix these tests.

**Comment by eddietejeda** [comment]
It looks like the tests were failing previously but this update is now blocked. Fixing the tests first.

**Comment by apburnes** [comment]
Closed by #2873
