### ISSUE TITLE
Add "Here's how you know" link to official US gov site banner

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2841]
Investigate why the link is missing from the banner. It should look like [this](https://cloud.gov/)

## This issue is done when:
- [ ] We identify the issue and fix it
- [ ] The link appears on the 18f site banner

**Comment by hbillings** [comment]
I _think_ we could probably crib off an old site (pretty sure that CALC, for instance, uses an older version of WDS). I'm happy to look into this if it's helpful.

**Comment by eddietejeda** [comment]
That would be great! Keep us posted.

**Comment by lsgitter** [comment]
should be fixed once we update the library

**Comment by Dahianna** [comment]
Fixed with #3097
