### ISSUE TITLE
CircleCI can not run on forks

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2875]
## Expected Behavior
We would like to be able to easily accept contributions from members of the public and staff outside the core 18F site team while still following our continuous deployment and integration rules. 

## Actual Behavior
CirceCI will not successfully run on pull requests from forks of the 18f.gsa.gov repo. Therefore, pull requests from the public fail to pass the required tests and have to be closed and repeated on a branch by site staff. This process is cumbersome and doesn't encourage public participation and contributions. 

## Steps to reproduce the behavior
- [ ] [Example 1](https://github.com/18F/18f.gsa.gov/pull/2706), [Example 2](https://github.com/18F/18f.gsa.gov/pull/2871)
- [ ] Open a new pull request from a fork rather than a branch

## This issue is done when:
- [ ] CircleCi can successfully run on forks

Unclear if this is an issue with our GitHub or CircleCI settings.

**Comment by hbillings** [comment]
Perhaps helpful: https://circleci.com/docs/1.0/fork-pr-builds/

**Comment by eddietejeda** [comment]
I understand why it's not a good idea to trigger the pull on other people's pull requests. From now on, I am going to merge the public's pull request into a branch, test myself, and merge the branch.

**Comment by eddietejeda** [comment]
Allowing anonymous/external pull requests to build on our servers is deemed a security risk. So we're going to continue blocking this.
