### ISSUE TITLE
Rethink the /developer page and/or developer resources

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2876]
Hypothesis: A researched and maintained version of the now-closed /developer page (#2872) would be a valuable resource to two primary audiences:

- Technical federal employees looking to explore our work who could become future partners or advocates
- Potential candidates interested in more technical roles, such as engineering or design

This page could potentially include resources like

- APIs we have built for other agencies
- Reusable tools or small applications we've created
- Technical policies
- Links to federal tech communities of practice
- Curated list of active GitHub repos/help wanted issues

## This issue is done when:
- [ ] Develop goals for these audiences
- [ ] Research audience needs and test prototypes
- [ ] Create proposal for new /developer page
- [ ] Create content governance plan

**Comment by lsgitter** [comment]
@Dahianna @apburnes I don't think we have the resources to do this project and looks like it would require more time than any of us have available. Are you ok with putting this in the icebox category for now?

**Comment by apburnes** [comment]
We have dev resources being maintained in other locations.
- https://before-you-ship.18f.gov/
- https://github.com/18F/development-guide

Maybe updating just the [`/guides/`](https://18f.gsa.gov/guides/) would be a minimal lift

**Comment by Dahianna** [comment]
I'm ok with  adding a developer section to /guides/

**Comment by lsgitter** [comment]
can link this to handbook developer guide. @apburnes to look up resource .

**Comment by apburnes** [comment]
We have transitioned to using micro-sites https://engineering.18f.gov/
