### ISSUE TITLE
Add rel=canonical to Tumblr

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#288]
We need to add `rel=canonical` to our Tumblr blog. I did this in #287 for our staging site. However, I think it will require drudge work in Tumblr, and manual pasting of our blog URLs. This is because there's not a clean one-to-one mapping of URLs. 

In other words, our Tumblr URL is `http://18fblog.tumblr.com/post/96977653581/the-encasement-strategy-on-legacy-systems-and-the` and our live URL is `https://18f.gsa.gov/2014/09/08/the-encasement-strategy-on-legacy-systems-and-the/`. You can't just switch the domain. 

Since the live URLs are constructed from a Tumblr import (and they share slugs), it _might_ be possible to have Tumblr automatically assemble the URLs from its knowledge of the post's slug and publication date. We'd have to research that. Otherwise, this is a matter of someone spending some time in Tumblr clicking through and copy/pasting and saving posts, one by one.

**Comment by AlbertoFdzM** [comment]
You made it!
