### ISSUE TITLE
Update USWDS library

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2883]
The site's USWDS is a couple years old and some functionality, like the dropdown stating the site is an official site does not work with this older version library.

I've begun investigating updating the USWDS library and fortunately it is possible.

**Comment by maya** [comment]
What version of the USWDS is it currently using?

**Comment by maya** [comment]
>like the dropdown stating the site is an official site does not work with this older version library.

I'd recommend breaking that into its own issue, as it seems distinct enough and may not be related to the USWDS version, though we'd have to investigate.

**Comment by eddietejeda** [comment]
It's using pre-versioned USWDS, but https://github.com/18F/18f.gsa.gov/tree/update_to_uswds_1.6.8 adds support for a more recent version. The upgrade seemed okay, but I did not have time to verify it.

The dropdown is its own issue: https://github.com/18f/18f.gsa.gov/issues/2841

This issue is focused on just the upgrade.

**Comment by maya** [comment]
It can't be pre-versioned bc it launched as version 0.8 three years ago and the USWDS code is from two years ago.

**Comment by maya** [comment]
Going just off of the dates, it looks as though it could have been version 0.11.1.

**Comment by apburnes** [comment]
closed by #2907
