### ISSUE TITLE
Tests are failing in new version of ruby.

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2884]
The tests are failing in the new version of Ruby.

/Users/eddie/.rvm/gems/ruby-2.5.1@18f.gsa.gov/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load': cannot load such file -- /Users/eddie/Code/18f.gsa.gov/_layouts/spec/_plugins/author_data_spec.rb (LoadError)

It appears that paths are getting screwed up.

**Comment by lsgitter** [comment]
@apburnes is this a duplicate of the ruby update task?

**Comment by apburnes** [comment]
This will be closed by #2873

**Comment by lsgitter** [comment]
#21873 was approved on 7/9/2019
