### ISSUE TITLE
Using LinkedIn and Facebook pages 

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2891]
The LinkedIn and Facebook pages for 18F are currently abandoned. We should either shutter them or keep them current.

My take: We seem to use Twitter effectively. We should just post the same content on FB and LinkedIn.

**Comment by awfrancisco** [comment]
The linkedin page is probably a question for Talent. I'd rather shutter them than do a half strategy.

**Comment by Dahianna** [comment]
I talked to Talent and they don't own https://www.linkedin.com/showcase/18f/ We should talk with OSC to determine who owns this page. As for Facebook, I don't think it reaches our niche audiences, so we can shutter it. I'll discuss with Karen.

**Comment by eddietejeda** [comment]
I think that's a good idea. USDS uses LinkedIn and they get a lot of attention there. I think claiming our 18F page and using it to post excerpts from our blog would be useful.

Facebook: yeah, I agree. I doubt that's our audience.

**Comment by Dahianna** [comment]
The Facebook is not really a page just an interest. I made changes to the logo and submitted it. Not sure how long the approval process takes. I am meeting with the OSC person in charge of LinkedIn in January when she comes back from maternity leave

**Comment by eddietejeda** [comment]
Checking in with the team who manages LinkedIn at GSA on Jan 18th.

**Comment by eddietejeda** [comment]
Still investigating...

**Comment by eddietejeda** [comment]
posted in #alumni, waiting to hear back

**Comment by Dahianna** [comment]
This is the new 18F LinkedIn page https://www.linkedin.com/showcase/18f/
