### ISSUE TITLE
Off-topic: any information on how 18f does billing / chargeback?

### ISSUE THREAD

**Issue by aegershman** [18F/18f.gsa.gov#2895]
Apologies, I know this isn't a "real" issue. Not sure where else to post this. Feel free to close this issue if you no one has any intention of answering this, no hard feelings.

I'm very curious how 18f does chargeback for orgs/teams, both on **how an invoice is calculated**, and on **how the money is transferred from one org to the platform team**:

- Is it an automated process? 
- Do you integrate with an external billing management system?
- Do you do something with cf-abacus and then manually send out invoices...?

If you can't share, I understand, but I'm very curious about it.

Thank you.

**Comment by awfrancisco** [comment]
Hello! 18F bills its partner agencies for actual time staff spend on projects based on a set hourly rate. Staff record their time using a tool we developed called Tock and then we create invoices based on hours reported to Tock. Our account managers manually send invoices to our partner agencies. 18F uses an Interagency Agreement form to create an official partnership with agencies, and that form authorizes agencies to pay 18F for our services. Hope that answers your questions!

**Comment by aegershman** [comment]
Gotcha. That does explain how 18F bills for labor-hours, though I'm more curious how CF platform tenants (e.g., orgs that are running their workloads on the platform) are billed for their app-usage hours / services?

**Comment by eddietejeda** [comment]
Not sure. That's a question for https://github.com/18F/cg-site team.
