### ISSUE TITLE
Use consistent header color in tags page

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2899]
## Expected Behavior
The "tags" page should use similar header colors as other blog pages.

## Actual Behavior
When you go to a tag page, the header is white and does not resemble any other page. 

You can see the blue header here: https://18f.gsa.gov/blog/
And a white header here: https://18f.gsa.gov/tags/lessons-learned/

This was not a decision, but an oversight.

**Comment by maya** [comment]
Have you looked at the design files (Sketch)? They do not use a dark header, unless there was a more recent one that did. 
<img width="805" alt="screen shot 2018-10-17 at 12 39 51 pm" src="https://user-images.githubusercontent.com/5249443/47111984-ded77180-d209-11e8-8eae-3adc6470b55a.png">

**Comment by eddietejeda** [comment]
Oh, I didn't see the Sketch file. Do you recall what the rationale was for it sometimes being white and other times being blue?

**Comment by maya** [comment]
No, I don't recall any reasoning as that question never came up. If I had to guess, it looks as though the blue was used for regular internal page types and the tags page was different enough to warrant this style.
