### ISSUE TITLE
Project page: Alaska Medicaid 

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2904]
As part of bringing acqusition content into the 18F site, we should [migrate this page about the acquisition project with Alaska](https://modularcontracting.18f.gov/projects/ak-medicaid/) into a project page. 

- [x] Transfer content to a [google doc](https://docs.google.com/document/d/1GTffbENWhqkAuOv9fEcztkM3pBmQp7F-1qBF1jCGuX8/edit#)
- [x] Create writing lab [request](https://docs.google.com/document/d/1xMVyueOhm4fM4KrbmVwcE_sGgKOveyNxGUT_WvERvv8/edit)
- [ ] Find new picture for project card
- [ ] Check content with @mheadd 
- [ ] Publish

**Comment by Dahianna** [comment]
@eddietejeda [here's](https://docs.google.com/document/d/1xMVyueOhm4fM4KrbmVwcE_sGgKOveyNxGUT_WvERvv8/edit?ts=5bca166f) the text for the writing-lab request

**Comment by eddietejeda** [comment]
Writing lab request https://github.com/18F/writing-lab/issues/395
