### ISSUE TITLE
Can we get a list of Federalist website?

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2905]
To catalog all of TTS's websites, we need a list of all Federalist websites.

**Comment by eddietejeda** [comment]
@awfrancisco 
https://docs.google.com/spreadsheets/d/17IG7n6HqjxIyemld8YawIvY_7n3Eny4w9bnuzx_8dTc/edit#gid=0

**Comment by awfrancisco** [comment]
Thanks!
