### ISSUE TITLE
Update jekyll

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2912]
## Expected Behavior

Jekyll should always be running the latest version.

## Actual Behavior

It's currently not.

## This issue is done when:
- [x] Update Jekyll
- [x] Release to production

**Comment by eddietejeda** [comment]
Pull request made: https://github.com/18F/18f.gsa.gov/pull/2913

**Comment by awfrancisco** [comment]
A+ issue description
