### ISSUE TITLE
Replace quote on /what-we-deliver/hhs-states/

### ISSUE THREAD

**Issue by hannahkane** [18F/18f.gsa.gov#2918]
We're re-purposing the pullquote on the HHS project page for the newer Alaska Medicaid page (/what-we-deliver/alaska-dhss/), so we should either remove or replace the quote on the HHS page.

See discussion here: https://github.com/18F/writing-lab/issues/395

**Comment by Dahianna** [comment]
@nkkl and @hannahkane Before we remove the quote, let me know if you'll be able to get a new one

**Comment by hannahkane** [comment]
cc @alexpandel because I'm not sure who's in the best position to get a new quote (I know it's not me 😉)

**Comment by nkkl** [comment]
TBH this is lower priority than getting our IAA mod hashed out, and it'll probably need to be escalated a bit to their comms people, so CMS will be a minute.

Would getting a quote from the Vermont project suffice?

**Comment by awfrancisco** [comment]
Yeah, Vermont would work. And doesn't have to be urgent.
