### ISSUE TITLE
Update the list of agencies we've worked with?

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2938]
The list of agencies should represent the work we want to work with. Does this list accomplish that? This list of agencies is out of date and over 2 years old.
https://18f.gsa.gov/what-we-deliver/

This issue is done when:

- [x] New agencies have been selected
- [x] Agencies information and logo has been added to banner

**Comment by Dahianna** [comment]
Here's the list: https://docs.google.com/document/d/1OVWKqOHJtvS9UiOBALQYr3XyZQtgD5FlRYZFuFBx-1o/edit?usp=sharing

**Comment by Dahianna** [comment]
Design lab issue: https://github.com/18F/design-lab/issues/49

**Comment by Dahianna** [comment]
Pull request for banner #2978. Let's wait until we decide on new design to merge
