### ISSUE TITLE
DOD / EA Cyber Training Ranges Project Page

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2941]
Draft a project page  for the Army Cyber project to showcase path analysis

**Comment by Dahianna** [comment]
agency: "Department of Defense"
title: 
subtitle: 
permalink: 
redirect_from:
excerpt: 
Image:
image_accessibility: ""
project_weight: 
tag
expiration_date:
github_repo:
project_url:
resources:

## BACKGROUND
### Heading
Text

_“Quote”_

## APPROACH
### Heading
Text

**Agency partner**
Department of Defense

**See our work** (if available)

**See the code on Github** (if available0

**Comment by lsgitter** [comment]
Reach out to project staff and ask them to fill out google form

**Comment by lsgitter** [comment]
Project team is no longer interested in doing a project page
