### ISSUE TITLE
Add search.gov to the site

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2949]
By integrating TTS tools such as search.gov into our site, we can show to others how all of our services can work together. We will investigate what steps are needed to implement search.gov, and if we have the tools to do it.

- [x] Meet with search.gov team to learn more about implementation
- [x] Discuss with 18F site team to see if it meets our needs

**Comment by eddietejeda** [comment]
I am more interested in this topic and created a search.gov account to test it out, but because of furlough, can't confirm my account. Will follow up.

**Comment by eddietejeda** [comment]
Next steps:

- [ ] Add 18F to search.gov account
- [ ] Bring over templates developed by Aaaron for search results to this repo

**Comment by lsgitter** [comment]
@Dahianna to follow up with @eddietejeda on how he did it for federalist

**Comment by lsgitter** [comment]
@lsgitter to look into 18F metohds use of search.gov

**Comment by eddietejeda** [comment]
Great timing. I just pushed up this change that's been pending for a while:

https://github.com/18F/federalist-uswds-jekyll/pull/33/files

**Comment by Dahianna** [comment]
@eddietejeda what does this change do?

**Comment by apburnes** [comment]
Use @eddietejeda example from the `federalist-uswds-jekyll` to integrate the search.gov into the site.

**Comment by eddietejeda** [comment]
We merged in search.gov example here: https://github.com/18F/federalist-uswds-jekyll

**Comment by lsgitter** [comment]
We will add search.gov with the new design.

**Comment by Dahianna** [comment]
Moved to #3142
