### ISSUE TITLE
resizing bug with photos when screen width is > 605px and < 778px

### ISSUE THREAD

**Issue by jgrevich** [18F/18f.gsa.gov#295]
# > 605px
![gt_605px](https://cloud.githubusercontent.com/assets/24955/4547612/953a699e-4e4e-11e4-92c3-04e569d8ca4b.png)

# < 778px
![lt_778px](https://cloud.githubusercontent.com/assets/24955/4547611/8b9827dc-4e4e-11e4-9a29-d656609710c8.png)

**Comment by elainekamlley** [comment]
New team layout via the PR #645

**Comment by gboone** [comment]
There are no bugs in the new layout. Promise.
