### ISSUE TITLE
Update homepage with new language and BD goals

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2954]
Angela and the BD team have new language and BD goals for 18F that need to be updated in the homepage. For example the type of projects/buckets we work on
- [ ] Meet with Angela and Alex to discuss new content
- [ ] Update content
- [ ] Publish to site

**Comment by eddietejeda** [comment]
Lets loop in @hannahkane once we have content.

**Comment by lsgitter** [comment]
closing this issue as it is the same as 2981
