### ISSUE TITLE
Implement new contact page design

### ISSUE THREAD

**Issue by hbillings** [18F/18f.gsa.gov#2958]
The design in #2490 is ready to go. Implement it!

**Comment by eddietejeda** [comment]
Hey @hbillings, what's the latest on this?

**Comment by hbillings** [comment]
@eddietejeda So I implemented most of this and then got swamped with other stuff before I circled back to the mobile design. I just opened a pull request for what I was able to get done: https://github.com/18F/18f.gsa.gov/pull/2962

**Comment by Dahianna** [comment]
https://18f.gsa.gov/contact/
