### ISSUE TITLE
US Tax Court Project Page

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2959]
Waldo and Vickie are working on a draft

**Comment by eddietejeda** [comment]
Waldo and Vicky are working on draft and @hannahkane will review.

**Comment by waldoj** [comment]
This is in the hands of the court, who needs to have a judge review our draft for approval.

**Comment by eddietejeda** [comment]
We should have an update later this week.

**Comment by eddietejeda** [comment]
hey @hannahkane any update on this?

**Comment by hannahkane** [comment]
Have asked the partner about it, but it's not a top priority for them. Will ask again in a couple weeks.

**Comment by hannahkane** [comment]
Draft is here: https://docs.google.com/document/d/1RFVOtrcnbEahh1ae3SXv_eMm1yM6Z9JB9qTiE25ky20/edit#

**Comment by Dahianna** [comment]
Hi @hannahkane! Is this approved?

**Comment by hannahkane** [comment]
Not as far as I know. I've actually rolled off of this project, and @ominina is the new AM. Olesya, is this something you could ask the Tax Court team about?

**Comment by ominina** [comment]
@Dahianna this is still in partner review, will follow up here when we have approval

**Comment by Dahianna** [comment]
Ok, thanks for the update

**Comment by Dahianna** [comment]
@ominina any updates?

**Comment by ominina** [comment]
@Dahianna tax court is still reviewing - they have a pretty rigorous review process there for anything that will be published publicly. we are checking on it every 2 weeks

**Comment by Dahianna** [comment]
Thanks @ominina !

**Comment by Dahianna** [comment]
Page under review by writing lab and then it'll get approval by the Chief Judge

**Comment by Dahianna** [comment]
@vickimcfadden is this good to go?

**Comment by Dahianna** [comment]
@vickimcfadden and @ominina did you ever receive any updates on this? If not, I'll go ahead and close this issue

**Comment by vickimcfadden** [comment]
@Dahianna the court isn't comfortable doing public communication about the project prior to the launch of the MVP (march 2020). We can close the issue for now and revisit later.

**Comment by Dahianna** [comment]
Sounds good. Thanks!
