### ISSUE TITLE
Typo on /about page

### ISSUE THREAD

**Issue by nicoleslaw** [18F/18f.gsa.gov#2985]
## Steps to reproduce the behavior
- [x] Head on over to https://18f.gsa.gov/about/#history-and-funding
- [ ] Check `Federal Acqusition Service` for all the vowels etc.

## This issue is done when:
- [ ] Y’all are happy
- [ ] Hi, I miss you all

**Comment by Dahianna** [comment]
Thank you @nicoleslaw ! I'll fix the typos

**Comment by Dahianna** [comment]
All done!
