### ISSUE TITLE
Implement new home page and what we deliver designs

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2986]
The final designs can be found here 18F/design-lab#49 
## This issue is done when:
- [x] We find a front-end developer with capacity to implement the new designs
- [x] Pull request with new design is created and merged

**Comment by lsgitter** [comment]
@Dahianna  can we mark this as done?

**Comment by Dahianna** [comment]
No, the changes haven’t been implemented. We’re still looking for a front end dev

**Comment by lsgitter** [comment]
@apburnes will try to make this update. This issue needs to be closed out before #2978 can be worked on.
