### ISSUE TITLE
Audit wiki content

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2993]
The wiki for this repo is outdated and needs a full review for:

- Current team processes
- Technical guidelines
- Current experience principles and goals for the site
- Relevance of all content

**Comment by eddietejeda** [comment]
- [ ] Home @eddietejeda 
   - Recommendation:
- [ ] Adding a page to the site @eddietejeda 
- [ ] Content hypothesis @Dahianna 
- [ ] Converting Google Docs to markdown @Dahianna 
- [ ] Experience principles @Dahianna 
- [ ] Git Troubleshooting @@eddietejeda 
- [ ] How we Git @@eddietejeda 
- [ ] Jekyll Plugins @eddietejeda 
- [ ] Posting a job opening  @Dahianna 
- [ ] Project hypotheses @Dahianna 
- [ ] Project names @Dahianna 
- [ ] Publishing a blog post @Dahianna 
- [ ] Tagging on the Blog @@eddietejeda 
- [ ] Troubleshooting formatting with pandoc @eddietejeda

**Comment by Dahianna** [comment]
- New content for [Converting Google Docs to markdown](https://docs.google.com/document/d/13bQeYjpcaTxOjqbxVzTax_1FI-NzlYFhMUihOSTZDXo/edit#)
