### ISSUE TITLE
Update the Federalist page with 18F page 

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2995]
Update the Federalist page with 18F page and get it in line with the current http://federalist.18f.gov website

**Comment by lsgitter** [comment]
compare content differences what we deliver/federalist and federalist.gov content and find a way to align the content.

**Comment by lsgitter** [comment]
Leah to research difference between content and will synch up with Andrew and Dahianna about changes.

**Comment by lsgitter** [comment]
Copied content from both pages and put it in a google doc so content can compare. @margaretmildrew @Dahianna would you be able to take on the next steps?

https://docs.google.com/document/d/1PiIhAe_ovQtpW69sa_ohcz0-y4e7kQeA7G8I3hc6CP8/edit#

**Comment by Dahianna** [comment]
@eddietejeda can you draft a doc with the changes using the project page style? This way we can't ensure it has the correct information.
