### ISSUE TITLE
Add new tag to blog post

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2996]
@Dahianna had a problem building the site when she added new tag. @eddietejeda will look into why this occurred and offer solution

**Comment by Dahianna** [comment]
Found it! https://github.com/18F/18f.gsa.gov/blob/034e423f1c8af1a321976d89ef73029273df98c5/tests/schema/tags.yml

**Comment by apburnes** [comment]
Move tags to a more logical location within the repo outside of the `tests`

**Comment by lsgitter** [comment]
@apburnes will add instructions on creating new tags to wiki and readme and then close out this issue.
