### ISSUE TITLE
Share strategy with Leah Gitter

### ISSUE THREAD

**Issue by lsgitter** [18F/18f.gsa.gov#3026]
Share strategy doc with Leah Gitter so she can understand the 18F site strategy

**Comment by Dahianna** [comment]
So, I can't seem to find the strategy doc. But here are some notes from our last retreat with our future plans for the [site](https://docs.google.com/document/d/1aLbTepmzgzAGFGHRg8DZk73w-8CB71a1vNPL3mFhS3w/edit#heading=h.hbqkxistn1j1).

**Comment by Dahianna** [comment]
Also the repo wiki has some guidance on our content principles: https://github.com/18F/18f.gsa.gov/wiki/Content-and-experience-principles
