### ISSUE TITLE
Research if we have a standardized process for posting and managing project page content

### ISSUE THREAD

**Issue by lsgitter** [18F/18f.gsa.gov#3033]
## Expected Behavior
There is a wiki or some sort of guidance on how to post and mange content on projects

## Steps to reproduce the behavior
- [ ]
- [ ]
- [ ]

## This issue is done when:
- [ ]
- [ ]
- [ ]

**Comment by Dahianna** [comment]
Yesish. Project teams can reach out to us to get access to the [project page template](https://docs.google.com/document/d/1z-SlrcDOuajm3dNQgtUT8LOQL4G6P55a1OniWoHx0qg/edit) They draft the content and get approval from the partner agency. Then outreach reviews the content and approves for the site team to publish on the site.

**Comment by lsgitter** [comment]
Do we have instructions somewhere on how to do this? If so where do the instructions lived? Do we create issues when we need to put projects up? Should we create a project page tag in the trello board?

**Comment by Dahianna** [comment]
We've had sent an email back in the day and talked about it at all hands. In the past, the site team was the one that would reach out to project teams to create a page. We haven't had many instances in which a project team reaches out, also we'd have to decide if it's a good project for the site. We can't give everyone a project page.
