### ISSUE TITLE
margin/padding removed from blog title

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#3046]
## Expected Behavior
The blog post title should be properly aligned and padded to header

## Actual Behavior
The blog post title is now pressing up against the header.  The original design looks like this https://github.com/18F/design-lab/issues/17#issuecomment-402828003

## This issue is done when:
- [ ] Fix alignment and add top padding
- [ ] Fix search in blog
- [ ] Check all `<inputs />`

**Comment by apburnes** [comment]
Add fixing search bar to PR 
- Ex. https://18f.gsa.gov/search/?q=tags
