### ISSUE TITLE
Update content on "How we work" page

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3058]
## Objective
Work with the design, strategy, and acquisition chapters to add language for their services.

## This issue is done when:
- [x] Create a [document to draft new content](https://docs.google.com/document/d/16RHE1vOc5pDAmkFlS67Pm56WJeMfygraeOCsmKg-Hes/edit#)
- [x] Work with the chapter leads to add the new language
- [ ] Get language approve by 18F and TTS Outreach directors
- [ ] Publish updates to the page

**Comment by lsgitter** [comment]
Closing this issue as it overlaps with issue 2981
