### ISSUE TITLE
Update USWDS library for 18F site

### ISSUE THREAD

**Issue by lsgitter** [18F/18f.gsa.gov#3061]
## Expected Behavior
working Daniel William to co-work on 18F site will help ensure the site meets 21st century IDEA ACT standards.

Currently UWDS is experiencing breaking changes

Might want to update to new version of USWDS

**Comment by lsgitter** [comment]
Justification: 21st Century IDEA ACT Compliance. GSA is going to newest version of USWDS as well. OSC is doing this for GSA.gov. Have asked website owners to fill out a form stating what they are missing. 

- need a person  with some visual design experience with familiarity USWDS 

- need to update 18f-site to newest version of USWDS. 
- Will update portions of site - (not try to update all of site to newest version of USWDS all at once)
- To update a single page on 18f site - USWDS and tweek it - 15hrs to get started and determine next steps.
- would start on main site first 
    - total of pages to update : 12 (this would be in addition to the 15hrs)
- may need review by design lab
- Maya Benari was working on this before she termed out.

**Comment by Dahianna** [comment]
GSA guidelines here: https://docs.google.com/document/d/1doMIkfIYgFHFxqS9Q8-ltXSfDybRBFr7jZfy38XLDbM/edit#

**Comment by austinhernandez** [comment]
**Here are the mockups on InVision:**
https://gsa.invisionapp.com/d/main#/console/18851755/392608183/preview

**Sketch files for USWDS 2.0 are here on Drive in the site folder:**
https://drive.google.com/open?id=1jGVEhjizHt7ZZ0eFmqedlccs1O6y69Vh

**Photos from 18F workshops here on Drive:**
https://drive.google.com/open?id=1ySWACkfQXw3n9yA1-KotGrBKN9Ue_I-T

**Next steps:**
1. Executive and Outreach approval 
2. Implementation feasibility
3. Building out components on the homepage
4. Implementing secondary pages

**Suggestions:**
1. Revisit navigation titles
   -   Through testing, this seemed to make sense, maybe they are fine!
   -  Here is an article shared by [design critique about navigation titles](https://www.nngroup.com/articles/category-names-suck/)

2. Sync public-facing messaging
   -  @Dahianna is actively working on this:
   -  Biz Dev
   -  External speaking slides (recruiting and civic community events) - [Who is 18F](https://docs.google.com/presentation/d/1Rcn6U4Rz3BPr0y4VFxZEnviuRrlheFr7zBLZR_xOEFE/edit?usp=sharing)

**Comment by Dahianna** [comment]
Hi @austinhernandez, we're having issues accessing Invision. Would you mind adding the mockups as pdfs or images to this issue. Thanks!

**Comment by austinhernandez** [comment]
I updated the previous comment with this link: https://gsa.invisionapp.com/share/PMUWVRMSUKN. Does this work?

**Comment by Dahianna** [comment]
It works for me. Let me check with leadership

**Comment by Dahianna** [comment]
Feedback from leadership:

**Homepage**
- Desktop 3 or 4 

**Project page**
- Projects 1 

**Comments**

Desktops
3 has the clearest call to action, and the header image speaks more culturally about who we are than some of the others, which are a bit more generic.
4 is really visually arresting and strong, but the CTA gets a little lost. That _may_ not be a bad thing, depending on what you're trying to do.
2 is nice, but felt a little more generic than the other options. I don't dislike it, but it didn't grab me as much as 3 and 4, either.
1 had a little too much loose white space up top for my tastes. That may just be me.

Note that all of those are only my opinions and should not be construed as any actual design critique :-)

I liked the gray-headered project page (1), with the left-aligned text better. Is there a reason we didn't use an image there, too? Page weight? Differentiation? Just curious.

**Comment by austinhernandez** [comment]
Some of the sites I used that do similar work in non-profit and private sector are:
https://www.cooper.com/
https://www.ideo.com/
Looks like these are moving away from the home hero image, but 

For the pages where we want to focus on the projects, I wanted to have the project images the focal point of the page. Here are some examples:
https://www.ideo.com/work
https://www.cooper.com/corporate-training-for-teams/
https://www.invisionapp.com/talks/designsystems

**Comment by Dahianna** [comment]
Also talked to Star and she's leaning towards desktop 4 as well, but 3 is fine if it aligns better with the USWDS.

**Comment by austinhernandez** [comment]
I like the illustration on 4, but now I'm leaning toward 3 because it might be more memorable? https://github.com/GSA/digitalgov.gov/issues/1517#issuecomment-555750354

Maybe we could do some visual preference testing with users?

**Comment by Dahianna** [comment]
It'd be great if we can do a quick test. Do you know if we still have access to Optimal Workshop?

**Comment by Dahianna** [comment]
I created this form to gather feedback. Feel free to make edits or add your own questions https://docs.google.com/forms/d/1deN4tUoP9XGIE9ipTeTK-e0hEddGRey1ygCKTkhVhUs/edit

**Comment by Dahianna** [comment]
Here are the results for the survey. As we've seen with our internal interviews, desktop 4 seems to be the preference. It's not perfect and we have to work on updating the content, but the illustration was seen more favorable over the hero image https://app.mural.co/invitation/mural/gsa6/1577730854809?sender=dahiannasalazarforeman2861&key=06243d9e-8f83-494b-894c-33787fd1bd81

**Comment by Dahianna** [comment]
I recommend using desktop 4 layout but using the desktop 3 language on the second half of the page. For example "case studies" instead of "future projects"

**Comment by Dahianna** [comment]
@apburnes and @Artahlil USWDS has updated to 2.8 including an update to the gov site banner https://designsystem.digital.gov/components/banner/

**Comment by Dahianna** [comment]
Moved implementation of homepage to issue #3207 Other issues solved by #3097
