### ISSUE TITLE
Digital Dashboard. gov

### ISSUE THREAD

**Issue by sbeliew** [18F/18f.gsa.gov#3067]
## Expected Behavior
Show all the link boxes when logged in as I see when I am not

Not Logged in:
![DigitalDashboardCorrect](https://user-images.githubusercontent.com/29760613/66052840-44963980-e4ff-11e9-8573-537bb63d708e.jpg)

## Actual Behavior
All link boxes except the Government-wide Reports and the Top Performing Agencies don't show up

Logged in:
![DigitalDashboardBug](https://user-images.githubusercontent.com/29760613/66052785-2b8d8880-e4ff-11e9-9ae2-c5ce56be9960.jpg)

## Steps to reproduce the behavior
- [1 ] sign in
- [2 ] go to the homepage, the boxes do not show up

## This issue is done when:
- [ ] Any time I log in

**Comment by gbinal** [comment]
I agree that’s a bug, but that site is not operated by 18F and this repo isn’t related to it.

Unfortunately, it doesn’t appear to have a public repo associated with it.   The only means of contact I see on the site is dotgovdashboard@gsa.gov.    Sorry not to be more help, but if you’re game, it looks like emailing this bug to that address is the best way to report it.

**Comment by sbeliew** [comment]
Thank you,  I have already sent an email and haven't gotten a response.

I will try again.

Shannon

___________________________________________
Shannon Beliew
Biologist
USGS - Patuxent Wildlife Research Center
12100 Beech Forest Road
Laurel, MD 20708-4039
w <http://www.pwrc.usgs.gov>ww.usgs.gov/pwrc <http://www.usgs.gov/pwrc>
Office: 301-497-5506
Fax: 301-497-5505
sbeliew@usgs.gov
https://www.usgs.gov/staff-profiles/shannon-beliew
Visit our Facebook page at https://www.facebook.com/USGSPatuxent/

"Those who dwell, as scientists or laymen, among the beauties and mysteries
of the earth are never alone or weary of life."  Rachel Carson

**Comment by gbinal** [comment]
I'm sorry, Shannon.  That's very frustrating.  

Thanks for filing issues when you see problems!  I wish we could be more help.
