### ISSUE TITLE
Word file attached to "Agile Solicitation Guide" contains errors

### ISSUE THREAD

**Issue by waldoj** [18F/18f.gsa.gov#3068]
## Expected Behavior
When downloading the DOCX file linked to from within [An Agile Software Development Solicitation Guide](https://18f.gsa.gov/2019/08/20/an-agile-software-development-solicitation-guide/), one would expect it not to have in-progress editorial suggestions.

## Actual Behavior
There are, in fact, in-progress editorial suggestions, in the form of comments.

## Steps to reproduce the behavior
- [x] download [the file](https://18f.gsa.gov/assets/presentations/agile-software-development-solicitation-template.docx.docx)
- [x] open it and read it

## This issue is done when:
- [x] the comments are gone
- [x] the filename no longer contains an extra `.docx` suffix

**Comment by bryanweast** [comment]
Do you believe this repository is open to all to commit and contribute?

**Comment by Dahianna** [comment]
> Do you believe this repository is open to all to commit and contribute?

Hi @bryanweast the 18F site repo is open for users to report any bugs or other issues with the site content.

**Comment by Dahianna** [comment]
This issue has been fixed by #3069
