### ISSUE TITLE
Test suite fails without a clear error message if a blog post has no tags

### ISSUE THREAD

**Issue by alexsoble** [18F/18f.gsa.gov#3088]
## Expected Behavior

Print a friendly error message or warning from the test suite that a blog post has no tags. This would be a simple `print` statement / warning if we're OK with blog posts having no tags, or a CI fail if we want to insist that every blog post have 1 or more tags.

## Actual Behavior

Test suite fails cryptically if a blog post is missing tags. Example: 

https://github.com/18F/18f.gsa.gov/pull/3086

## Steps to reproduce the behavior
- [ ] Create a new blog post wtih content but no tags
- [ ] Run the test suite and/or the CI

## This issue is done when:
- [ ] Expected behavior is implemented

**Comment by lsgitter** [comment]
This test is supposed to fail because we need blog posts to be searchable and have tags. This prevents folks from posting without tags.

**Comment by alexsoble** [comment]
@lsgitter — That makes sense to me, but as I wrote under "Expectated Behavior" above: "Print a friendly error message or warning from the test suite." Right now the test suite fails silently under this scenario.
