### ISSUE TITLE
Update What we Deliver content

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3100]
## Steps
- [x] Draft content with 18F SMT
- [ ] Obtain approval from 18F Director
- [ ] Obtain approval from TTS leadership
- [ ] Publish to site

**Comment by Dahianna** [comment]
Draft is here: https://docs.google.com/document/d/1TCPZp6S7Cbxs5qj0O6zgQZBS7bHeH-YppFLiWmSvMb4/edit#

**Comment by apburnes** [comment]
Closing do to rethinking site content structure
