### ISSUE TITLE
Update how we work content

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3101]
## Steps
- [x] Draft content with 18F SMT
- [x] Obtain approval from 18F Director
- [x] Obtain approval from TTS leadership
- [x] Publish to site

**Comment by Dahianna** [comment]
Draft is here: https://docs.google.com/document/d/16RHE1vOc5pDAmkFlS67Pm56WJeMfygraeOCsmKg-Hes/edit#heading=h.9ewvmwvq5cux

**Comment by apburnes** [comment]
Added acquisitions section and refined language #3108
