### ISSUE TITLE
Update homepage content

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3102]
## Steps
- [x] Draft content with 18F SMT
- [ ] Obtain approval from 18F Director
- [ ] Obtain approval from TTS leadership
- [ ] Publish to site

**Comment by Dahianna** [comment]
Draft: https://docs.google.com/document/d/1uEiw_j8rYgZeToO6gQ1PQrsdJ_aZl9_jzIW32mKexNY/edit#heading=h.xlhpbzhi69ua

**Comment by Dahianna** [comment]
Met with 18F BD team and they'll review content and provide input

**Comment by lauraGgit** [comment]
Merged in!
