### ISSUE TITLE
Possibly add Netlify CMS 

### ISSUE THREAD

**Issue by apburnes** [18F/18f.gsa.gov#3112]
## Description

Federalist is releasing the ability to integrate the Netlify CMS GUI with their sites. Adding the GUI to 18f.gsa.gov site may improve contributors experience when adding new blog posts or other content.

## Background

Federalist documentation https://federalist.18f.gov/documentation/getting-started-with-netlify-cms/

**Comment by Dahianna** [comment]
Done!
