### ISSUE TITLE
21st Century IDEA Baseline Compliance Criteria - Accessible

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3121]
**Criteria**

- [x] Routine review of all site content (both pages and files) for conformance to the most current 508 Standards
- [x] Quick remediation of all accessibility issues when they are discovered
- [ ] Incorporation of accessibility testing into the publication process

**Comment by Dahianna** [comment]
More info in Section 8 of the Guidelines for GSA's Digital Presence: https://docs.google.com/document/d/1E0K_LDlDqEgHKESTqHKlKN50OJAxCcl_FcKB-qLL13A/edit

**Comment by Dahianna** [comment]
@apburnes here's more information about[ P@11y](https://github.com/GSA/digitalgov.gov/pull/1936))
1. Install - [Pa11y documentation](https://github.com/pa11y/pa11y-ci#requirements)
2. Configure - Add a .[pa11y configuration file ](https://github.com/pa11y/pa11y-ci#requirements)and set it to scan your sitemap
3. Automate - Create [test scripts](https://github.com/GSA/code-gov-front-end/blob/master/package.json#L22) and [add scanning to continuous integration](https://github.com/GSA/code-gov-front-end/blob/master/.circleci/config.yml#L15)
4. Document - Add instructions to run the tests to your README.md

**Comment by Dahianna** [comment]
Also look at issue #3188

**Comment by Dahianna** [comment]
Pa11y works on site. We'll run after USWDS update and @Artahlil will demonstrate how to use it

**Comment by Dahianna** [comment]
@Dahianna will do some research on options for an accessibility test

**Comment by apburnes** [comment]
To test accessibility, we need to add a step in CircleCI to run pa11y test against the rendered '_site' directory. See https://github.com/18F/federalist.18f.gov/blob/main/.circleci/config.yml#L10 for inspiration.
