### ISSUE TITLE
Meet GSA modernization criteria

### ISSUE THREAD

**Issue by lsgitter** [18F/18f.gsa.gov#3130]
Finalized GSA IT site modernization docs by 3/30/20

**Comment by Dahianna** [comment]
https://docs.google.com/spreadsheets/d/1fdv8sYV9EkIO3-5xhWxDPnVIouq9yAuae-OHKzXkkHk/edit#gid=1163132370

**Comment by Dahianna** [comment]
Close after solving #3132 and #3121

**Comment by Sgtpluck** [comment]
@Dahianna can this be closed? #3132 and #3121 have both been closed, but it's been a long time so I wanted to check in before mashing the button.

**Comment by Dahianna** [comment]
Yep, you can go ahead and close. Thanks @Sgtpluck !

**Comment by Sgtpluck** [comment]
Completed with #3132 and #3132
