### ISSUE TITLE
21st Century IDEA Baseline Compliance Criteria - Consistent

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3131]
**Criteria**

- [x] Adoption of the US Web Design System as part of any site refresh
- [x] Following GSA design and branding guidelines for specific types of sites

[Section 11 of the Guidelines for GSA's Digital Presence](https://docs.google.com/document/d/1E0K_LDlDqEgHKESTqHKlKN50OJAxCcl_FcKB-qLL13A/edit)

**Comment by Dahianna** [comment]
Currently working on updating USWDS, should be ready to go by the end of FY20

**Comment by Dahianna** [comment]
Add the following links to the footer:
- usa.gov
-  GSA FOIA page
- gsa.gov

Fix the accordion and footer for mobile site (will fix with USWDS update)

**Comment by annepetersen** [comment]
Just had a member of the public flag the problem with the mobile footer to me, so fixing this would be great!

**Comment by Dahianna** [comment]
Should be fixed after #3097 update
