### ISSUE TITLE
Update site for improved indexing for Search.gov

### ISSUE THREAD

**Issue by apburnes** [18F/18f.gsa.gov#3142]
## Expected Behavior
When going to the [sitemap](https://18f.gsa.gov/sitemap.xml), the url's generated for the sitemap are using the `federalist.18f.gov`, not `18f.gsa.gov`.

## Actual Behavior
Expect the urls in the sitemap to use `https://18f.gsa.gov`

## Steps to reproduce the behavior
- [x] Update logic in the [sitemap.xml](https://github.com/18F/18f.gsa.gov/blob/master/sitemap.xml) to use the correct site url (`https://18f.gsa.gov`)

## This issue is done when:
- [x] The `sitemap.xml` generates all the urls with `https://18f.gsa.gov`
- [x] Update tile page first on metadata then the site
- [x] Open graph block (publish time and date time of posts)
- [x] `<main>` tag around the content
- [x] Verify header, footer, and nav tags

**Comment by Dahianna** [comment]
Check after #3097 merged

**Comment by Dahianna** [comment]
Fixed with #3097

**Comment by Dahianna** [comment]
Fixed with #3212
