### ISSUE TITLE
18f homepage elements don't render correctly in IE

### ISSUE THREAD

**Issue by SelenaJV** [18F/18f.gsa.gov#3181]
## Expected Behavior
18F homepage should look good in most browsers

## Actual Behavior
In IE 11 (and maybe other versions) some sort of element collision makes the big quote on the top center look off. Perhaps this is scaling issue too? 

![image (3)](https://user-images.githubusercontent.com/1444077/84957415-28581e00-b0c9-11ea-8f97-a9e3fbf19e8d.png)

![image (2)](https://user-images.githubusercontent.com/1444077/84957419-29894b00-b0c9-11ea-9461-6e96d8760041.png)

## Steps to reproduce the behavior
- View https://18f.gsa.gov/ in Internet Explorer 11 
- [ ]
- [ ]

## This issue is done when:
- Elements render correctly in IE or we decided we don't care about IE 😉 
- [ ]
- [ ]

**Comment by nate-io** [comment]
@SelenaJV, @apburnes It looks like the `em` values are being misapplied in IE11. I have a proposed fix using `rem` on my local but am unable to create a PR for review. How should I proceed?

**Comment by apburnes** [comment]
Hi @nate-io, you can create a fork the repository and create a PR with comments relating to this issue. Thanks again.

**Comment by nate-io** [comment]
@apburnes Sure thing - [as requested](https://github.com/18F/18f.gsa.gov/pull/3272) let me know what you think and I'll change as required.

**Comment by Dahianna** [comment]
Solved with #3272
