### ISSUE TITLE
Create documentation for USWDS update

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3205]
Create a section on the wiki on how to update the USWDS library on the 18F site

## This issue is done when:
- [ ] Updating the USWDS library guide is created on the wiki page

**Comment by Dahianna** [comment]
Draft: https://docs.google.com/document/d/11BSjhHZkYk-sFPeCRSvZiytJ7x4hM_P8-U_aXetZj8I/edit?ts=5f2c06f5

**Comment by lauraGgit** [comment]
Since we migrated to `uswds-jekyll` do you think that this section of the README covers this? https://github.com/18F/18f.gsa.gov#style-and-style-guide

**Comment by Sgtpluck** [comment]
This seems done -- please reopen if something is missing!
