### ISSUE TITLE
Fix typo in footer

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3224]
## Expected Behavior
List item should say "View accessibility statement"

## Actual Behavior
"View accessiblity statement"

## Steps to reproduce the behavior
- [x] Click `learn more` at the bottom of the footer

## This issue is done when:
- [x] Accessibility is spelled as such

![image](https://user-images.githubusercontent.com/52677065/90659909-40583500-e213-11ea-9afa-e62924fc63b5.png)

**Comment by Dahianna** [comment]
Thanks Igor! Fixed with #3225
