### ISSUE TITLE
Adjust size of UX Guide Icon to match others

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3245]
## Expected Behavior
The icon for the UX Guide should be the same size as the other icons for consistency, and to prevent misalignment. 

## Actual Behavior
The icon is just a bit smaller 
![image](https://user-images.githubusercontent.com/52677065/93514541-54b44e00-f8f5-11ea-8cb1-a40cd29adb24.png)

Vs.

![image](https://user-images.githubusercontent.com/52677065/93514688-80cfcf00-f8f5-11ea-9eca-24a7d7205f2d.png)
![image](https://user-images.githubusercontent.com/52677065/93514714-87f6dd00-f8f5-11ea-85fa-3b13fbce344d.png)

I believe this is because the icon is smaller than the max-width so that the sizing rules don't kick in. 

## Steps to reproduce the behavior
- [ ] Visit 18f.gsa.gov/guides/
- [ ] Inspect icon size

## This issue is done when:
- [ ] The UX guide icon is the same size as all the other icons.

**Comment by Dahianna** [comment]
@jstrothman could you take a look?

**Comment by igorkorenfeld** [comment]
Over-communicating a bit, but wanted to note that I adjust it in #3246

**Comment by jstrothman** [comment]
Thank you @igorkorenfeld for fixing this up!
