### ISSUE TITLE
Update wiki page

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3261]

**Comment by Sgtpluck** [comment]
@Dahianna Can you please clarify what needs to be updated? What's specifically the ask, and what does done look like?

**Comment by Dahianna** [comment]
To my knowledge the wiki page hasn't been updated in 5 years. Some of the processes might be outdated. For example the how we built a blog post section. I recommend doing a review of all the sections and ensure content and guidelines are up to date.
