### ISSUE TITLE
redirect to Code of Conduct in Handbook

### ISSUE THREAD

**Issue by afeld** [18F/18f.gsa.gov#3270]
The Code of Conduct applies TTS-wide, so I suggest we point to the copy in the Handbook instead of keeping it on the 18F site.

## Expected Behavior

Visiting `/code-of-conduct/` redirects to https://handbook.tts.gsa.gov/code-of-conduct/.

## Actual Behavior

There's a page in both places.

## Steps to reproduce the behavior

- [ ] Visit `/code-of-conduct/`

## This issue is done when:

- [ ] There is a canonical source for the Code of Conduct

**Comment by Dahianna** [comment]
That works for me! @apburnes let's make this change during planning this week

**Comment by Dahianna** [comment]
https://github.com/18F/18f.gsa.gov/pull/3282
