### ISSUE TITLE
Update how we work content FY21

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3281]
## Steps
- [ ] [Draft content](https://docs.google.com/document/d/1NOfxHfT4MLSLW4yzmlcV2vWkKeH0TUrM8GvBvlkjbBk/edit) with 18F SMT
- [ ] Obtain approval from 18F Director
- [ ] Obtain approval from TTS leadership
- [ ] Publish to site

**Comment by Dahianna** [comment]
Met with @anjunainaustin and they'll work with 18F Leadership to provide content by January 29th

**Comment by Sgtpluck** [comment]
@Dahianna is this still relevant?

**Comment by Dahianna** [comment]
It probably still needs an update, but you can close this ticket.  If there's a need the new Outreach liaison for 18F can create the issue.
