### ISSUE TITLE
Broken icon on official gov site banner 

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3290]
## Expected Behavior
The banner should display a down chevron 
![image](https://user-images.githubusercontent.com/52677065/102254730-e2d0ae00-3ebd-11eb-8245-cf2de557d422.png)

## Actual Behavior
Displaying a horizontal bar
![image](https://user-images.githubusercontent.com/52677065/102254794-f8de6e80-3ebd-11eb-9230-0eeb8125e41b.png)

I am guessing it has to do with this `mask` property
![image](https://user-images.githubusercontent.com/52677065/102254983-3d6a0a00-3ebe-11eb-9c9f-992277d0009c.png)

**Comment by Dahianna** [comment]
Thanks Igor! @apburnes is OOO until 2021. Feel free to create a pull request to fix the icon and I can review it.

**Comment by igorkorenfeld** [comment]
Looking into it a little further, it seems like the `mask` property is missing the `webkit-` prefix. I haven't figured out why that's happening yet.
