### ISSUE TITLE
Link/ add portfolios page to the site

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3299]
- Identify best way to introduce the portfolios page to the site: https://portfolios.18f.gov/
- Implement solution

**Comment by lauraponce** [comment]
@Dahianna what are your thoughts on adding a link to the portfolios from the main nav at the top of the page? I feel like it works well there, and if it was just a section on another page, it might get lost in the other content.

![Screen Shot 2020-12-29 at 3 23 08 PM](https://user-images.githubusercontent.com/21222704/103320350-d71ad680-49e9-11eb-8360-f3b3a5265ec0.png)

It feels important enough to put up in a prominent place like that, but I'm curious to hear what you think! If that makes sense to you, I'm picturing the link would go to a page that has the information from https://portfolios.18f.gov/ but in the style of the rest of the 18F site.

**Comment by Dahianna** [comment]
As I understand them, Portfolios are part of our process (how we work), so my first thought was to add them to that section; but as you mentioned they might get lost in all that content. Let's as BD what they think. @anjunainaustin do you see Portfolios be separate from our process/services? 

Also, having a section named "Portfolios" might make users think it's a portfolio of our work and not a field we specialize in.

**Comment by anjunainaustin** [comment]
Hmm, you know [I've been thinking about this a lot ](https://docs.google.com/document/d/1diyh7CsG5rgpQyJZotDb_bcwPEy1c-Gl3P18VgwIkvI/edit#heading=h.yrp8gybx89k5) lately actually. I've outlined in that doc the distinct components of our sales pitch: mission areas, knowledge areas, offerings, and proof (project examples). Yes I think they're distinct from our services. I think adding a small section for mission areas could work on the How We Work page given the scope of content that title suggests, but I'll defer to y'all on placement. It seems to me that portfolios are mission areas that we specialize in. Now internally we know that these include portfolios and domains but portfolios to date are the only ones that get their own site. So I wonder, what if we had a section on our mission areas, and then link to the portfolio sites there? FWIW, I think there's some other things we can add to the site at a later date to give more representation to the other components of our sales pitch...but for now to stay focused I've just answered your question on the portfolio sites. Hope this helps!

**Comment by anjunainaustin** [comment]
I've thought of this further @Dahianna @lauraponce . I think How We Work could use another look. Here are some thoughts:

1. How We Work sounds like methods not what we sell or what our specializations are. I'd like to propose remaining that page to Offerings.
2. I like your idea @lauraponce to link to the portfolios in the main nav. I'll note that I've created [this issue](https://github.com/18F/18f.gsa.gov/projects/8#card-58142241) and [this issue](https://github.com/18F/18f.gsa.gov/projects/8#card-58143025) to add pages for the remainder of our business Verticals and I think they should go under the same main nav link, so naming it Portfolio doesn't work, but Portfolios & Domains sounds confusing and Verticals means nothing...so idk a good name!

**Comment by adunkman** [comment]
Closing; as per https://github.com/18F/dns/issues/599 the portfolio website is being decommissioned.
