### ISSUE TITLE
Remove jekyll_pages_api_search from Gemfile dependencies

### ISSUE THREAD

**Issue by apburnes** [18F/18f.gsa.gov#3311]
With the transition to using Search.gov, its capabilities to search just the blog content collection of the site, and the dependency no longer being maintained, we need to remove the `jekyll_pages_api_search` and any references to it.

Acceptance Criteria:
- [x] Dependency removed from Gemfile and FederalistGemfile
- [x] Remove any related js or html files referencing the jekyll plugin

**Comment by Dahianna** [comment]
Fixed with #3316
