### ISSUE TITLE
Add autoprefixer to jekyll-assets

### ISSUE THREAD

**Issue by apburnes** [18F/18f.gsa.gov#3317]
## Expected Behavior

Building the SCSS will autoprefix the CSS styles when building with `jekyll-assets`.

## Actual Behavior
Will add the vendor specific prefixes to css styles that apply to better support multiple browsers. Should fix #3290

## This issue is done when:
- [x] Install autoprefix gem and configure based on [`jekyll-assets` docs](https://github.com/envygeeks/jekyll-assets#css-auto-prefixing)
- [x] Output css is being autoprefixed

**Comment by Dahianna** [comment]
Fixed by #3302
