### ISSUE TITLE
Netlify posts collection sort by doesn't show latest posts

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3347]
https://18f.gsa.gov/admin/#/collections/posts when sorting posts by newest-oldest the posts shown are not in the right order

To Do:
- [ ] Parse all of the blog posts' frontmatter data to find discrepancies in page metadata
- [ ] Fix and standardize blog bost metadata structure

**Comment by peterrowland** [comment]
Getting up to speed

- many entries missing date fields
- `date: 'YYYY-MM-DD'` is valid with or without quotes 
- so are dates with timestamps `date: 'YYYY-MM-DDT12:00:00-04:00'`
- `date: Month DD, YYYY` is not valid - but this is how it is created in the editor. Changing the config to 'YYYY-MM-DD' instead works, but will not sort correctly for two entries on the same day.

We can solve going forward by changing the date config to something that netlify can sort on - it doesn't appear to change the way dates are displayed on the blog.

Going backward, we could update and insert date fields based on the file slugs with an automated script, or by hand if necessary.

**Comment by Sgtpluck** [comment]
Can this be broken up into two different tickets? One for creating a new data standard and one for updating older dates?

**Comment by Dahianna** [comment]
Sure, I no longer work at 18F, so do what you think is best.

**Comment by mgwalker** [comment]
There are also questions here about whether we want to be using Netlify CMS. It's being picked up by another vendor and is supposedly going to be maintained again, but for now... maybe not?

**Comment by juliaklindpaintner** [comment]
Closing for now as we are not actively using Netlify to maintain the 18F blog.
