### ISSUE TITLE
Footer Update Review

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3368]
![image](https://user-images.githubusercontent.com/52677065/110024357-30f69000-7cfc-11eb-9935-d85816d82739.png)

- The headers are just slightly smaller than the link text. They should be `lg` to be more differentiated. 
- The headers have an underline and a click pointer on hover, but they are not a link so there shouldn't be any interaction effect
- Links are `#00547a` and should be `#046B99`. (`#00547a` is not a brand color) 

## Summary Checklist
- [x] Headers are size `lg`
- [x] Headers are static text with no interaction effects. 
- [ ] Links are `#046B99`

**Comment by divyanshdahiya** [comment]
i have the solution to this problem and i can fix it easily .
