### ISSUE TITLE
Contact page Review

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3375]
## Intro Header
See #3374 

## Main content 
Link color is `#00547a` should be `#046B99` ( `#00547a` is not a brand color)

## Sign up

- Sign up button is slightly larger than the search box, making it look misaligned 
![image](https://user-images.githubusercontent.com/52677065/110390190-9b2c6f00-8033-11eb-8ace-6d1ef850ed36.png)

- Left side of the sign up button should not have rounded corners so it appears connected to the input, like the search button on a search box

![image](https://user-images.githubusercontent.com/52677065/110390800-87353d00-8034-11eb-815d-2745d3f75923.png)

I am wondering if this section should be a call to action like on the Guides page. Here is a mockup, would love to hear your feedback @Dahianna, @lauraponce, @lauraGgit 

![111_18FSite_Signup](https://user-images.githubusercontent.com/52677065/110390546-260d6980-8034-11eb-877b-057006d7eecc.png)

If not, separator line should be `gray-cool-10` (`#dfe1e2`), and should only be as wide as the text content like the rules on current [What we deliver](https://18f.gsa.gov/what-we-deliver/) page

## Summary Checklist
**Intro Hero**
- [ ] Changed based on #3374

**Link text**
- [ ] Link color is `#046B99`

**Signup**
Direction A
- [ ] Styled as in mockup, matching Call to Actions on other pages
 
Direction B
- [ ] Rule is `gray-cool-10` (`#dfe1e2`)
- [ ] Rule is only as wide as the grid

**Comment by lauraGgit** [comment]
@igorkorenfeld would it be ok to use the existing grid layout of the banner that is on the guides banner cta?

**Comment by igorkorenfeld** [comment]
I find that using the `media-block` container with a `.usa-media-block__body` and `.usa-media-block__img` works better for creating a visual relationship between the text and the image. So ideally I would switch both to that. _But_ if that isn't possible to use here,  or if there is another reason not to use it, then I think using columns and the grid is a good alternative.

**Comment by lauraGgit** [comment]
happy to port it over to media block - do you know where in the uswds docs I can learn about that?

**Comment by igorkorenfeld** [comment]
Awesome! I'm not having luck finding documentation for it. I see it being used on the example page template for the [landing page](https://designsystem.digital.gov/page-templates/landing-page/)
