### ISSUE TITLE
Header/Nav review

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3377]
- 18F logo is too small. On the existing site it’s 48px, but on the branch it’s only 24px.
![image](https://user-images.githubusercontent.com/52677065/110519111-efd6f500-80da-11eb-943a-e9dd285bafcc.png)

- Nav link hover and underline (bottom-border) color is `#005ea2` but should be `#046B99`,  (`#005ea2`)
![image](https://user-images.githubusercontent.com/52677065/110518739-7b9c5180-80da-11eb-8d60-2d8c4e03fd87.png)

- Search bar is a bit too small. USWDS recommends having space for at least 27 characters, on the branch can only fit 20, while on the existing site can fit 29. Note the extra white space on the right is taken up by a clear button when typing, so it might appear like there is more space than there is. 

Existing site:
![image](https://user-images.githubusercontent.com/52677065/110519298-244ab100-80db-11eb-95ad-aa3e4f241b13.png)

Current branch: 
![image](https://user-images.githubusercontent.com/52677065/110519245-1301a480-80db-11eb-8a54-5d5519065ca5.png)

- Color of the search button background color should be `#046B99`

- Blog page isn't underlined when a user is on the blog page

## Summary Checklist
- [x] Logo is ~48px
- [x] Nav link and bottom border/line color is`#046B99` on hover
- [x] Search bar is wide enough to fit 27 characters 
- [x] Search button background color is `#046B99`
- [x] Blog page is underlined when user is on the blog page

**Comment by peterrowland** [comment]
to add: blog nav link doesn't appear underlined when on that page.
