### ISSUE TITLE
Update agencies logo/shield on full list

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3412]
Update the agencies logos here too: https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/agency-home-list/what-we-deliver/

Update the following logos:
- [ ] Dept of ED, https://www2.ed.gov/web-guidance/styleguide/branding.html
- [ ] HHS, https://www.hhs.gov/web/policies-and-standards/web-policies/logo-seal-and-symbol-policies/index.html
- [ ] OPM, looks rebranded but did not find any branding guidance https://www.opm.gov/
- [ ] SBA, https://www.sba.gov/brand/

**Comment by Sgtpluck** [comment]
Can you give more details about what needs to be updated? Have those agencies logos been updated? Are there new agencies we need to include?

**Comment by Dahianna** [comment]
I believe it was a combination of both. Update it to include new ones and also make sure those are the official logos/shields for the agency/departments

**Comment by a-chappelear** [comment]
I can go through the logos to check if they are current (and if not, track down the new ones.) This will likely need a front-end ticket to implement.

**Comment by a-chappelear** [comment]
I went through all of the logos and these are the ones that should be updated _(based on the link in the ticket)_

- Dept of ED, https://www2.ed.gov/web-guidance/styleguide/branding.html
- HHS, https://www.hhs.gov/web/policies-and-standards/web-policies/logo-seal-and-symbol-policies/index.html
- OPM, _looks rebranded but did not find any branding guidance_ https://www.opm.gov/
- SBA, https://www.sba.gov/brand/

Next steps - this may need to be converted to a front-end ticket to implement those updates in the footers.

**Comment by colinmurphy01** [comment]
Moving this ticket to our backlog and updating the ticket.

**Comment by colinmurphy01** [comment]
@mgwalker who might be the best person to review this?
