### ISSUE TITLE
Add external link identifier

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#3416]
During the update, we lost the external link identifier (it lets folks know when a link is not a gov site) and it is a GSA policy requirement. You can find the original PR here: https://github.com/18F/18f.gsa.gov/pull/3292

**Comment by Dahianna** [comment]
@lauraGgit or @peterrowland have you been able to take a look at this?

**Comment by Sgtpluck** [comment]
@lauraGgit you have an open PR for this -- are you working on it, or is it available to be reassigned?

**Comment by colinmurphy01** [comment]
@mgwalker who might be the best person to review this?

**Comment by mgwalker** [comment]
We can ask @cannandev tomorrow. It needs dev eyes IMO.
