### ISSUE TITLE
Add domain pages to the site

### ISSUE THREAD

**Issue by anjunainaustin** [18F/18f.gsa.gov#3426]
Add a page for each of the 18F Domains.

Names for now:
1. State & Local Domain (@arouault @ayushi-roy will need to sign off before production)
2. GSA Domain (@rrefoy will need to sign off before production)
3. Natural Resources & Land Management Domain (@tram @MelissaBraxton will need to sign off before production)

I'll have content for each page in the next couple weeks after aligning with the Domain Champions on a sales pitch for their domain, but in terms of general content elements, I'd like us to keep it very basic to start to include:

1. Domain Title
2. Tagline
3. Main Point - [see here to get an idea of the length of this content](https://docs.google.com/document/d/19uE3XHLZkuM74K36ZMrIxfXFNnre6ObKksnNsfTEhnY/edit)
4. Case Study - there's 1 relevant case study for each domain already on the site, we'd just need to copy them to the page
5. Contact us

**Comment by Dahianna** [comment]
I am already working with State and local and Natural resources to add content for their domains to the portfolios page. Happy to meet with Rebecca to discuss GSA content. Strategy wise is probably best to keep portfolios/domains together. I'll close this issue and open one on the portfolios page

**Comment by anjunainaustin** [comment]
@Dahianna I didn't see this covered in an issue when I looked, also looked at open portfolios page issue. When you say portfolios page, are you talking about a landing page for all portfolios and domains and then you can click to a page on each one? If so, that's fine. We'll want to call it something else besides portfolios page still.

**Comment by Dahianna** [comment]
Here's the page: https://portfolios.18f.gov/

**Comment by Dahianna** [comment]
Moved issue to portfolio repo: https://github.com/18F/portfolios/issues/34
