### ISSUE TITLE
Add Justice Portfolio page to the site

### ISSUE THREAD

**Issue by anjunainaustin** [18F/18f.gsa.gov#3427]
Name for now is Justice & Courts Portfolio

I'll have content for each page in the next couple weeks after aligning with the forthcoming new Justice Director on a sales pitch, but in terms of general content elements, I'd like us to keep it very basic to start to include:

Portfolio Title
Tagline
Main Point - see here to get an idea of the length of this content
Case Study - there's 1 relevant case study already on the site, we'd just need to copy it to the page
Contact us

**Comment by Dahianna** [comment]
Same as #3426 we can talk about adding this content to the portfolios page

**Comment by Dahianna** [comment]
This is an issue for the portfolios site. Feel free to move there when ready
