### ISSUE TITLE
Make the whole card clickable (including the image) for featured projects

### ISSUE THREAD

**Issue by lauraponce** [18F/18f.gsa.gov#3457]
## Feature suggestion

The featured projects cards on the [home page](https://18f.gsa.gov/) are only clickable from the text header (e.g. "Easy-to-use campaign data") and the "Read more >" link. Most of the time, people expect the image and entire card to be clickable to take them to the link. It'd be great if we could update these so that you can select anywhere on the card to go to the link.

![Screen Shot 2021-04-28 at 11 52 18 AM](https://user-images.githubusercontent.com/21222704/116457672-8b9dfb00-a818-11eb-9654-7ddd9bfb4704.png)

## User story

As a user, I want to be able to click on the image so I can get to where I need to go.

**Comment by jstrothman** [comment]
Bumping this one for accessibility reasons as well. 

> [WCAG Success Criterion 2.4.4 Link Purpose (In Context)](https://www.w3.org/TR/WCAG22/#link-purpose-in-context): The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.

As a screen reader user, when I listen to a list of links, I want to be able to tell where the link will take me. 
Currently, I'd hear "Read more. Read more. Read more. etc."

I recommend:
1. Eliminate the 'Read more' links
2. Make the h3 card title a link
3. Make the h3 link the same color blue as the current Read more links #046b99
4. On hover of the whole card, make the h3 the darker blue like with the current Read more links #1c304a and raise the card shadow from shadow-2 to shadow-5

**Comment by echappen** [comment]
I can work on making the whole card a link. 

I'm removing the Bug label, as currently there is more explanatory screen reader only text for the "Read More" links. 

<img width="710" alt="Screen Shot 2022-11-16 at 12 53 04 PM" src="https://user-images.githubusercontent.com/4267629/202270831-fb749266-9dad-4a7f-9d9c-7df6e112622a.png">

**Comment by jstrothman** [comment]
Ah--thank you!
That's great. As we chatted about, I still recommend removing the `read more` links, as it's added unnecessary burden when you're listening with a screen reader and call up a list of links so you hear each card's links read twice.

To test in VoiceOver:
Launch the voiceover rotor (cmd+option + U): for me it defaults to list of links, but you can right or left-arrow to move between rotor functions (say, if yours defaults to lists of headings or form fields)
