### ISSUE TITLE
USWDS banner bar loads in "expanded" then "retracts"

### ISSUE THREAD

**Issue by wslack** [18F/18f.gsa.gov#3460]
## Expected Behavior

The site loads in in a way for users that causes information to smoothly fill the screen.

## Actual Behavior

When loading the site, the USWDS menu bar loads in as open before closing. This doesn't look professional.

## Steps to reproduce the behavior

- [ ] Load the site on a new browser window.
- [ ] Observe how the menu bar "flashes"

## This issue is done when

- [ ] The menu bar loads in as closed.

First seen at https://azangru.livejournal.com/1410446.html

```[tasklist]
- [ ] #3658
- [ ] 18F/uswds-jekyll#257
```

**Comment by mgwalker** [comment]
Currently blocked by #3658 because I can't get the site to build on my machine. 😬

**Comment by mgwalker** [comment]
Now blocked awaiting 18F/uswds-jekyll#257

**Comment by mgwalker** [comment]
18F/uswds-jekyll#257 is done. Back to being blocked by #3658. More details in that issue about what's blocking.
