### ISSUE TITLE
UI glitch on home page

### ISSUE THREAD

**Issue by CerebralAdvantage** [18F/18f.gsa.gov#3466]
Dell Latitude Laptop (very old), 3.7G mem
64bit Ubuntu 18.04.5LTS, Gnome 3.28.2 
Firefox 87.0 64bit

Issue:
The content overran (and overlapped) the page footer, rendering both unreadable.

Attaching screenshot.
![Screenshot from 2021-05-11 10-07-59](https://user-images.githubusercontent.com/36646858/117831138-4af3a800-b242-11eb-8e6b-fc3fceb00ffa.png)

**Comment by neilmb** [comment]
I'm trying to reproduce this behavior now. I tried it with Firefox 87.0 on MacOS X 11.6.8 and I didn't see any overlap between the content and the page footer:

<img width="1351" alt="Screen Shot 2022-08-18 at 09 42 44" src="https://user-images.githubusercontent.com/443389/185409884-c1c299bd-2c0c-4f4d-a006-ebf17936aa11.png">

I am going to look for a way to try reproducing it on a virtual machine using the old Ubuntu version.

**Comment by neilmb** [comment]
I made a virtual machine with Ubuntu 18.04.5 and installed Firefox 87.0. I wasn't able to reproduce the layout error inside of VirtualBox.

![VirtualBox_Ubuntu 18_19_08_2022_10_38_51](https://user-images.githubusercontent.com/443389/185656634-2bea9cc7-88b9-4b53-994a-a045787733b0.png)

@CerebralAdvantage Can you offer any more information that might help with reproducing the error?

**Comment by Sgtpluck** [comment]
Closed -- will reopen if the issue comes up again or additional information comes to light.
