### ISSUE TITLE
fraud

### ISSUE THREAD

**Issue by LisaDorsey** [18F/18f.gsa.gov#3571]
somebody create an account without my permission with login.gov, also I reported near a month ago that my backup codes was stolen

**Comment by geekygirlsarah** [comment]
Hi @LisaDorsey! We're the government organization that made Login.gov, but we're not the ones that can help you need support as we don't have that access.

You can go to https://login.gov/contact/ to contact them. FOr the fields, I might try something like:
Topic: Verifying your identity
Issue: Other
Partner Agency:  If you know what site the person signed up through, choose that. If not, choose "Other"
Email: put in your email

Then in the larger text box, put in the information you said about someone made an account without your permission and that your backup codes were stolen. Don't include any personally identifying information in there side from your email in that field. Hopefully they can help you out!

I'll close this issue soon as it's not something I can help with but reach out to Login.gov's support as they should be able to help you.
