### ISSUE TITLE
BUG: Docker installation fails

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3588]
## Expected Behavior
Building and serving the site with Docker should work.

## Actual Behavior
The `bundle install` line results in:

```
#9 255.0 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...
#9 255.0 `setup_python!': libv8 requires python 2 to be installed in order to build, but
#9 255.0 it is currently not available (RuntimeError)
...
#9 255.0  from extconf.rb:7:in `<main>'
#9 255.0 extconf failed, exit code 1
...
#9 255.0 An error occurred while installing libv8 (8.4.255.0), and Bundler cannot
#9 255.0 continue.
#9 255.0
#9 255.0 In Gemfile:
#9 255.0   uswds-jekyll was resolved to 5.3.0, which depends on
#9 255.0     mini_racer was resolved to 0.3.1, which depends on
#9 255.0       libv8
```

## Steps to reproduce the behavior

1. `git clone https://github.com/18F/18f.gsa.gov.git && cd 18f.gsa.gov/ && docker-compose up`
2. End of list

## This issue is done when

- [ ] A fresh Docker installation works and serves the site

## Attempted solutions

Solutions from StackOverflow and elsewhere] suggest setting the Docker build platform to linux/amd64](https://github.com/rubyjs/libv8/issues/315) and [setting build config to use system v8](https://stackoverflow.com/questions/19673714/error-installing-libv8-error-failed-to-build-gem-native-extension). I attempted to implement both of these and they didn't have any effect, but I'm not convinced I did this perfectly or didn't have something cached.

**Comment by Sgtpluck** [comment]
Closed with #3606
