### ISSUE TITLE
Add privacy link to footer 

### ISSUE THREAD

**Issue by jstrothman** [18F/18f.gsa.gov#3601]
## As part of compliance with GSA website requirements, due 8/31, we need to add a privacy statement to the footer of our website. 
Link text: GSA privacy policy
URL: https://www.gsa.gov/website-information/website-policies#privacy

## This issue is done when

- [ ] 18f.gsa.gov has a footer link to https://www.gsa.gov/website-information/website-policies#privacy
- [ ] Update the other links to match the wording and links in the footer of https://derisking-guide.18f.gov/

**Comment by neilmb** [comment]
@jstrothman Almost done, but one clarification: The Derisking Guide uses the link text "Privacy Policy" for this. Would you like me to match that as I will for the rest of the items, or use "GSA Privacy Policy" as you asked in the original ticket?

**Comment by neilmb** [comment]
Yes, @jstrothman, my plan is to make the footer match entirely (including adding a few new links that weren't there already).
