### ISSUE TITLE
Some anchor elements have empty href attributes

### ISSUE THREAD

**Issue by mgwalker** [18F/18f.gsa.gov#3661]
## Expected Behavior

All anchor elements with `href` attributes have a value in that attribute.

## Actual Behavior

Some anchor elements have `href=""`. htmlproofer is catching those now in automated tests.

## Steps to reproduce the behavior

- build the site

## This issue is done when

- [ ] htmlproofer tests show 0 errors for empty `href` attributes

**Comment by colinmurphy01** [comment]
@mgwalker who might be the best person to review this?

**Comment by mgwalker** [comment]
Anyone, I guess.

**Comment by colinmurphy01** [comment]
Do you want someone to run a build or review the logs from a recent build?

**Comment by mgwalker** [comment]
Oh. I reckon we need to talk about how this goes in general. In this case, PR #3664 has the changes to fix the build errors, so if you click through there, you should be able to see there aren't any failing tests.
