### ISSUE TITLE
BUG: Width for some blog posts

### ISSUE THREAD

**Issue by cmajel** [18F/18f.gsa.gov#3666]
## Expected Behavior
I expect that all blog posts would have the same content width. 

Here's a post that shows expected behavior, and a screenshot:
https://18f.gsa.gov/2023/02/13/looking-back-and-forward/
<img width="1580" alt="Screen Shot 2023-03-07 at 3 02 00 PM" src="https://user-images.githubusercontent.com/2374206/223540850-d323d711-230a-4344-a7d3-11745cd0e7e1.png">

## Actual Behavior
There are some posts that have narrower content widths. It seems like it starts with `.usa-section`, but I am not sure where the issue is coming from

Here are posts that show the narrower view, and a screenshot:
https://18f.gsa.gov/2020/08/04/introducing-the-ux-guide/
https://18f.gsa.gov/2020/03/05/readmes-for-you-and-me/
<img width="1580" alt="Screen Shot 2023-03-07 at 3 01 38 PM" src="https://user-images.githubusercontent.com/2374206/223541255-69938cc6-9dfe-4763-91fc-e19e884670c9.png">

Noting [this wayback machine view of the Readme post from Feb 2023](https://web.archive.org/web/20230220090314/https://18f.gsa.gov/2020/03/05/readmes-for-you-and-me/) where things looked more consistent - maybe a change was introduced recently?

## Steps to reproduce the behavior

- View this post on Readme's and compare it to more recent posts, like this one on [2023 design team learning](https://18f.gsa.gov/2023/02/13/looking-back-and-forward/)
- [ ]
- [ ]

## This issue is done when

- Blog posts have a consistent width
- [ ]
- [ ]

**Comment by danbrady** [comment]
I'd like to help with this issue. Adding text to any header tags (including `h2`, `h3` within the content) to a narrow page on prod and watch the column grow like magic!
 
![Animation of column resizing as text is added to the header.](https://user-images.githubusercontent.com/381190/233797358-42c4fe70-c857-4a0e-9336-538850ca8b5d.gif)

I suspicion it might be related to the flex grid layout. I'll keep looking into it.

(Unrelated but there is an errant quote in the `post.html` template as well. I removed it locally but it didn't have any effect on the rendering.)

![Code snippet of extra quote](https://user-images.githubusercontent.com/381190/233797761-ce1480c3-f4b0-4407-a8ca-0242de320448.png)

**Comment by geekygirlsarah** [comment]
> Adding text to any header tags (including `h2` and `h3` within the content) to a narrow page on prod and watch the column grow like magic!

Interesting catch!

> I suspect it might be related to the flex grid layout. I'll keep looking into it.

If you wanted to, that'd be nice. I'll probably also check it out soon too to see if I can find it.

> (Unrelated but there is an errant quote in the `post.html` template as well. I removed it locally but it didn't have any effect on the rendering.)

Also good catch! You're welcome to PR it, or I can do it soon and I'll add you as a co-author.

**Comment by danbrady** [comment]
Thanks, @geekygirlsarah!

> If you wanted to, that'd be nice. I'll probably also check it out soon too to see if I can find it.

FWIW: It appears that the measure utility / max-width set on the paragraphs might be related as well.

> > (Unrelated but there is an errant quote in the `post.html` template as well. I removed it locally but it didn't have any effect on the rendering.)
> 
> Also good catch! You're welcome to PR it, or I can do it soon and I'll add you as a co-author.

Submitted PR #3678 - It's nominated for PR of the year! 🤞

**Comment by MelissaBraxton** [comment]
Thanks so much, @danbrady!
