### ISSUE TITLE
Investigate removing 18F style guide

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/18f.gsa.gov#3700]
## Feature suggestion

The 18F Style Guide, located at https://18f.gsa.gov/styleguide/ , seems like an outdated and old relic from a time past. The layout doesn't work. My search across files can't find anywhere it's linked. I imagine anything useful is already in the UX guide or Brand guide. I think this could be removed (both the `_styleguide` directory as well as `layout/styleguide.html`).

## User story

As a developer/user of this repo, I want to remove the old 18F Style Guide so I can have a simpler repo with less old material.

**Comment by annepetersen** [comment]
We do use this and it gets a decent amount of traffic; in 2022, in fact, more traffic than the Engineering Hiring Guide. 

Tagging them in to make sure @igorkorenfeld, @cmajel and @quarterback are aware of this proposal to remove the Brand Guide.

**Comment by alexbielen** [comment]
@annepetersen are we talking about the same guide? 

It looks like this is about https://18f.gsa.gov/styleguide/ and not https://brand.18f.gov/

**Comment by cmajel** [comment]
[brand.18f.gov/](https://brand.18f.gov/) is well loved and used, so keep her!  ❤️ 

https://18f.gsa.gov/styleguide/ is less so. Originally, [it looked like this](https://web.archive.org/web/20170430104054/https://18f.gsa.gov/styleguide/layout/), and documented UI patterns and guidance for the 18F website. 

My two cents are this isn't serving us in it's current form. But, having pattern guidance and consistency across 18F sites is useful for faster builds and brand experience.

**Comment by geekygirlsarah** [comment]
Yes, definitely referring to the broken style guide (the latter), not the brand guide (the former). (We're definitely integrating that into the replatforming project.)

If we (18F) feel like it needs to still exist in some form, then perhaps a ticket should be put on one of the guides to try to write up the latest patterns we use. But this should probably still get removed from here.

**Comment by igorkorenfeld** [comment]
I'm wondering if we might repurpose [styleguide](https://18f.gsa.gov/styleguide/) for the re-platforming effort? Might that be a helpful visual guide? Realizing, of course, that keeping it would be another site to maintain.
