### ISSUE TITLE
18f site style guide page—footer displaying over the content

### ISSUE THREAD

**Issue by austinhernandez** [18F/18f.gsa.gov#3709]
on the [18f site style guide](https://18f.gsa.gov/styleguide/) page the footer displaying over the content for some reason (image attached)

![image](https://github.com/18F/18f.gsa.gov/assets/23194720/f78bd369-9f2c-4c5b-985d-8aaa68714f40)

**Comment by AnitaYCheng** [comment]
I took a look and it looks like the footer's order was unset in `_uswds-theme-custom-styles.css`. I can tackle this when I do the accessibility tickets next week. There's a comment in the CSS that says the order was unset for a11y reasons but I'm not familiar with that - I'd need to look more into it.
