### ISSUE TITLE
Pull quotes not showing on blog

### ISSUE THREAD

**Issue by cmajel** [18F/18f.gsa.gov#3759]
## Expected Behavior
To see a styled pull quote on blog posts when indicated. We had these on the older version of the site. 

## Actual Behavior

Things that were pull quotes in the past are now styled like regular text; see last paragraph in the screenshot of [this blog:](https://18f.gsa.gov/2023/09/07/catching-up-with-the-tanf-data-portal-project/)

![Screen Shot 2023-09-22 at 3 17 22 PM](https://github.com/18F/18f.gsa.gov/assets/2374206/f8ce4f39-1bca-4451-939a-8a42d043fb67)

Another example on [this post:](https://18f.gsa.gov/2023/04/25/18f-checks-in-with-the-dawson-project-at-the-us-tax-court/); see last paragraph in the screenshot:
![Screen Shot 2023-09-22 at 3 19 22 PM](https://github.com/18F/18f.gsa.gov/assets/2374206/0cb4fccd-f918-4f8d-9014-cfc5f3104a2b)

## Steps to reproduce the behavior

- [ ] 
- [ ]
- [ ]

## This issue is done when

- [ ] Pull quotes from past blogs don't appear as extra text
- [ ]
- [ ]

**Comment by igorkorenfeld** [comment]
Noting to self or future maintainer:

The current css targets `blockquote` elements but the quotes in the blog posts here are `div`s with a `"testimonial-blockquote"` class. 

Ideas for resolving:
1. Change the quote within the post to a blockquote. In theory this should be doable by placing a ">" in front of the quote. This may be more semantic and would have the styling automatically applied. However, it would mean we would need to edit any post that has "the testimonial-blocquote" in it to resolve all of them.  
2. Add `.testimonial-blockquote` as a target to the existing `blockquote` styles declarations in the `blog.scss` style component. This should then apply to all existing blog posts that have that class.
