### ISSUE TITLE
BUG Social link in the footer opening in the same tab

### ISSUE THREAD

**Issue by tmsagarofficial** [18F/18f.gsa.gov#3775]
## Expected Behavior
The social links in the footer should open in new tabs upon clicking them for the best user experience 
## Actual Behavior
But here these social links in the footer open in the same tab as the current tab making it a hindrance for the user experience as the user has to go back to the site and then proceed after using each social link.
## Steps to reproduce the behavior
1) Go to https://18f.gsa.gov
2) Scroll till you see the footer of the website
3) Observe that clicking on any of the social links makes it open in the same tab as the current tab.
Image ref below: 
![image](https://github.com/18F/18f.gsa.gov/assets/110724849/257ba4f8-31e5-4c54-9956-283496adb6bb)

## This issue is done when

This issue does not have any special triggering event.

PS: I would love to work on a fix for this issue and am open for discussion about the same too.

**Comment by peterrowland** [comment]
Our accessibility experts have weighed in:

- Its generally discouraged to open new windows or tabs.
- The cases where it's recommended are for additional context information or if following the link would take the user away from a logged in session
- If you are going to do it, there should be advanced warning (with alt text and an icon)
- see: https://www.w3.org/TR/WCAG20-TECHS/G200.html

Neither of the cases where it is recommended for accessibility apply to these links, so we should probably leave it as it is.

**Comment by tmsagarofficial** [comment]
Okay , thanks for responding.
Yeah maybe leaving it as it is feels right .
