### ISSUE TITLE
Have Github automatically delete merged branches

### ISSUE THREAD

**Issue by echappen** [18F/18f.gsa.gov#3781]
## Suggestion

I don't see a reason to keep merged branches around, and this would make finding current/relevant branches less confusing. 

Github has a per-repo [configuration](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) for enabling this.

## User story

As a developer, I want to automatically delete merged branches so I can easily find more relevant branches.

**Comment by juliaklindpaintner** [comment]
@cantsin took care of this!
