### ISSUE TITLE
issue with "how we work" topic tag

### ISSUE THREAD

**Issue by claireb-gsa** [18F/18f.gsa.gov#3815]
https://18f.gsa.gov/tags/how-we-work/

Clicking the topic in the right sidebar only shows one post, using ` how-we-work`

All the other posts are tagged with  `how we work`

https://gsa.enterprise.slack.com/files/U04AVTNMASC/F06RP7BBQ1G/screenshot_2024-03-27_at_4.33.35_pm.png

**Comment by juliaklindpaintner** [comment]
Addressed
