### ISSUE TITLE
Code blocks don't wrap

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3823]
## Expected Behavior

When I encounter a code block in the blog, it should wrap like a text editor would, or scroll horizontally so you can see all the code.

## Actual Behavior

When I encounter a code block in the blog, if it's long enough, it runs off-screen. However, the horizontal scroll settings prevent me from scrolling to see the full block.

Inserting line breaks isn't necessarily the right solution — in this case, I would expect the database client to error if line breaks were inserted here. We want people to be able to copy and paste the code.

![Screenshot 2024-04-12 at 11 08 47 AM](https://github.com/18F/18f.gsa.gov/assets/1887182/e2df56ac-2427-412f-98af-01a347bf8086)

## Steps to reproduce the behavior

- [ ] Include a long code block in a blog post, may we suggest:

```
grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE to { username 2 };
```

## This issue is done when

- [ ] Code blocks wrap or scroll internally (like the code block in this very issue! ☝🏼)

**Comment by peterrowland** [comment]
Tested adding `overflow-x: auto` to the code css, and it has the desired effect.

**Comment by peterrowland** [comment]
[PR](https://github.com/18F/18f.gsa.gov/pull/3851) for changes.

**Comment by bpdesigns** [comment]
@cantsin can you look at this today before @peterrowland is out of the office?

**Comment by cantsin** [comment]
LGTM but I am unsure how this ongoing work on 18f.gsa.gov impacts migration. @beechnut can you chime in here? OK to merge?

**Comment by beechnut** [comment]
@cantsin @peterrowland Ok to merge!
