### ISSUE TITLE
Differentiate code block styling

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3824]
Code blocks would ideally look meaningfully different from body text. At the moment, body text (`.env` and `docker-compose.yml`) look almost the same as the code blocks, differing only in font face.

![Screenshot 2024-04-12 at 11 09 10 AM](https://github.com/18F/18f.gsa.gov/assets/1887182/eba88e4e-c86c-4b9f-9db6-6d740540ee2b)

I'd expect something more visually offset, [like this block from USWDS](https://designsystem.digital.gov/design-tokens/typesetting/overview/#example-settings-and-typesetting).

**Definition of done**

- [ ] Code appears meaningfully offset, whether through color, border, etc.
- [ ] Shows line numbers along left side ([see #5 here](https://www.sitepoint.com/best-practice-for-code-examples/))

**Comment by peterrowland** [comment]
![before](https://github.com/18F/18f.gsa.gov/assets/1530932/7d4b7695-5939-4c6c-916a-7c66dbf5e7fe)
[link](https://18f.gsa.gov/2015/01/13/an-open-source-tool-for-easier-database-testing/)
![after](https://github.com/18F/18f.gsa.gov/assets/1530932/45709a95-9e65-4462-b2f9-b8320d3072ee)
[link](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/add-code-highlighting/2015/01/13/an-open-source-tool-for-easier-database-testing/)

**Comment by peterrowland** [comment]
[PR](https://github.com/18F/18f.gsa.gov/pull/3851) for changes.

**Comment by bpdesigns** [comment]
@cantsin can you look at this today before @peterrowland is out of the office?
