### ISSUE TITLE
Add CM to the site

### ISSUE THREAD

**Issue by jackiekazil** [18F/18f.gsa.gov#384]
@cmc333333, please add yourself to the [team yml](https://github.com/18F/18f.gsa.gov/blob/staging/_data/team.yml).

##### Example ways of adding yourself

If you want to be visible via photo: https://github.com/18F/18f.gsa.gov/commit/b151886d1e6bb5f9e3

If you don't want to be visible via photo: https://github.com/18F/18f.gsa.gov/commit/9ad68dd8fac2001e3

**Comment by cmc333333** [comment]
Resolved with #464
Live at https://18f.gsa.gov
