### ISSUE TITLE
Get a "hello production" (empty site) deployed through CI and running in Cloud.gov Pages

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3843]
Acceptance criteria

- [x] Ensure we can deploy 18f.gsa.gov to Cloud.gov pages production
- [x] Ensure we can deploy 18f.gsa.gov to Cloud.gov non-production env for testing

**Comment by cantsin** [comment]
I've fixed access to pages. Not sure what `Cloud.gov non-production env` means here.

**Comment by cantsin** [comment]
See https://github.com/18F/18f.gsa.gov/pull/3871 for some associated work on this -- sorry, the CI failures were driving me up the wall

**Comment by jasnakai** [comment]
The 18f.gsa.gov repo is running on Pages. Double checked that the replatform-main branch builds: https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/replatform-main/.
Closing this out as Done.
