### ISSUE TITLE
Correct the blog post and blog page layouts

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3849]
Blog posts and pages (listing multiple posts) aren't rendering right. The blog post titles and taglines aren't rendering, links aren't showing the right icons to indicate external links, and some layouts use `page` variables where it's not clear if that's correct practice.

```[tasklist]
### Acceptance criteria
- [x] Smoke test: [FBOpen post](https://18f.gsa.gov/2014/05/11/18f-shows-what-is-possible-in-government-with-fbopen/) shows the right tagline/intro
- [x] And shows external link icon appropriately (are all dot govs considered internal? — yes)
- [x] No remaining questions about whether `page.` is part of template tags
- [x] For blog pages: blog title and tagline render
- [x] Blog header images and their alt text render
```

**Comment by bpdesigns** [comment]
@cantsin thoughts on this? what skills are needed?

**Comment by beechnut** [comment]
@bpdesigns I'll chime in: this will involve looking through HTML layouts and understanding the cascade of data and variables in a static site generator. Any engineer or designer who can do HTML and has worked in SSGs or more complex applications should be able to take this on.

**Comment by bpdesigns** [comment]
@beechnut to double check link and work with @sam-couch-18f if there are questions
