### ISSUE TITLE
Ensure that analytics are working as expected

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3861]
This work includes:

- Ensuring that the analytics scripts are loading every page
- Deciding whether to load the `analytics` include or the `scripts` include and making sure nothing gets lost in the process. We used ther 18F guides for 11ty code and some old templates for Jekly there are well and determining which template to use 
- Identify whether `base` or `default` layouts can be deleted
- Figuring out what we need to do to the `searchgov` properties in _data/site
-

**Comment by bpdesigns** [comment]
@cantsin has the context needed to take this on

**Comment by beechnut** [comment]
@cantsin We can close this, correct? I think it was left open because automatic closes only work when merging to `main`.
