### ISSUE TITLE
Fix inaccessible images

### ISSUE THREAD

**Issue by SSPJ** [18F/18f.gsa.gov#3862]
## Expected Behavior

While working on #3855, I discovered that some pages need better `alt` text.

## Actual Behavior

In some cases, alt text is empty. Screenreader software will ignore images with empty alt text. In a few cases, alt text is present but is wrong (copy/paste errors). In one memorable case, the alt text is a long random string of characters.

## Steps to reproduce the behavior

- [ ] Use a screenreader to test what a page reads aloud.

## This issue is done when

- [ ] All non-decorative images have descriptive `alt` attributes which describe what information a sighted user would gain from viewing the image
   - [ ] This includes images in `figures` -- **if the `alt` attribute is missing or empty, some screenreaders will not read the `figcaption`!**
   - [ ] Avoid using redundant words like "image of", "photo of", "picture of". The screenreader software already tells the user that it is an image.
- [ ] All decorative images (images which are not intended to convey a meaning) have an empty `alt` attribute
   - [ ] Best practice for images which perform functions is to describe the function. Example: "Go back" not "Blue arrow pointing to the left". In many such cases, text already exists on the screen to describe the function, so the image is redundant. In that case, use empty `alt` text.
- [ ] (optional) Alt text should be brief and describe only essential information. Shorten long `alt` attributes and move additional interpretations/explanations into a `figcaption` where both blind and sighted users will benefit.

**Comment by SSPJ** [comment]
As an aside, I implemented a few changes on this commit: https://github.com/18F/18f.gsa.gov/pull/3863/commits/f0e4726ffae346b1b7a22e1abcb566bf2e137524. (Not a full audit/remediation, just a few spots fixed up.) Feel free to use those, if they are helpful.

**Comment by nicoleslaw** [comment]
Sharing a few updates:

- Given the state of the site migration, I am starting with an audit and writing alt text in a spreadsheet rather than starting a branch or being blocked altogether.
- I reviewed the [accessibility guide](https://guides.18f.gov/accessibility/images/) and @jasnakai shared this excellent how-to for [writing descriptive alt text](https://www.cooperhewitt.org/cooper-hewitt-guidelines-for-image-description/). He offered to be a reviewer of the alt text as an accessibility guild lead.
- I will summarize my approach in a later comment and hope we can align on a style for the blog in particular, since the rest of the site changes less frequently.

**Comment by nicoleslaw** [comment]
I have about 700 images left to audit. Still working through this each day.

**Comment by nicoleslaw** [comment]
I'm still trucking away on this but have been juggling other priorities this week. I will be staffed to a project next week, but am comfortable keeping this as a lower-pri task on my plate if that's okay with everyone else.

**Comment by mel-keene-gsa** [comment]
updated spreadsheet with conditional formatting to indicate doneness

**Comment by mel-keene-gsa** [comment]
some blog posts have slightly different dates in the URL in the new site -- just an fyi to whoever takes this ticket next, it's helpful to find the file by the name of the post, as opposed to the specific date

**Comment by mel-keene-gsa** [comment]
fyi that the above pull request should NOT close the issue, this is an interim pull request of all the alt tags i've fixed so far! still more to go!

**Comment by mel-keene-gsa** [comment]
This has been split into a [Content Audit](https://github.com/orgs/18F/projects/41/views/13?pane=issue&itemId=81073355) ticket and a Front-end Dev ticket
