### ISSUE TITLE
Migrate navigation

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3866]
There are a number of includes/layouts that handle navigation, and we should migrate those as-needed.

A few of the filters in the Ruby files, like `matches_url` and `hash_link`, support the navigation and would need to come over.

```[tasklist]
### Tasks
- [ ] Assess whether nav layouts need to come over
- [ ] Migrate or delete utility filters
```

**Comment by bpdesigns** [comment]
@beechnut to add a tasklist to this
