### ISSUE TITLE
18F Guides are not searchable from main 18F site 

### ISSUE THREAD

**Issue by sam-couch-18f** [18F/18f.gsa.gov#3873]
## Expected Behavior
Entering a search query from the main 18F site and filtering the search to "18F Guides" should return results. 

## Actual Behavior
[Entering a search query](https://search.usa.gov/search/docs?affiliate=18f-site&dc=8985&query=backlog) from the main 18F site and filtering the search to "18F Guides" does not return any results.

[Entering a search query](https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=18f-guides&query=backlog) from the Guides site directly, however, does return results as expected. 

## Steps to reproduce the behavior

- [ ] Navigate to https://18f.gsa.gov/ and click the search icon in the upper right corner
- [ ] On the search results page, filter to "18F Guides" in the secondary navigation
- [ ] Note that there are 0 results returned regardless of the search query

## This issue is done when

- [ ] Searching for 18F Guides content from the main 18F search functionality returns results as expected

**Comment by bpdesigns** [comment]
@sam-couch-18f I'll bring this up with Andrew on Monday.

**Comment by cantsin** [comment]
The `affiliate` query parameter tells search.gov which site to "search". Looks like it's incorrectly set for guides. I'm not sure how to fix this, however. Agree that this seems like a priority fix -- we should either change the guides `affiliate` query to `18f-guides` or remove the tab entirely from search.gov 18f.gsa.gov results.

**Comment by caleywoods** [comment]
This seems resolved. @jimkreft dropped this knowledge on me in the Search.gov support ticket that I opened.

> It looks like this is tied to the migration of the guides to https://18f.gsa.gov/guides/  and https://guides.18f.gov/ The guides collection is managed here:  https://search.usa.gov/sites/7744/collections/8985/edit and I updated it to remove all the old guide subdomains and added the new path and consolidated subdomain. 

> You may also want to add the guides subdomain to the 18f config here: https://search.usa.gov/sites/7744/domains

With the changes Jim made I am able to see search results now when selecting "18 Guides" and searching for something such as "derisking".

**Comment by caleywoods** [comment]
While the main issue is resolved, I am waiting on access to be able to look at some of the configuration to see if I can fix the fact that I don't see the derisking guide when searching "derisking" under the "Everything" selection. Jim Kreft replied back to me about this so I have an idea of what to do to fix it.

**Comment by caleywoods** [comment]
guides.18f.gov was also added as a subdomain to the [config inside Search.gov](https://search.usa.gov/sites/7744/domains). That seems to have resolved the last issue of the actual guides not appearing when searched for with "Everything" selected, I now see the derisking guide listed in the results with either "Everything" or "18F guides" selected.
