### ISSUE TITLE
18F Blog - Nixon reference shows the wrong image

### ISSUE THREAD

**Issue by nicoleslaw** [18F/18f.gsa.gov#3950]
## Expected Behavior

Blog post about [privacy dashboard](https://18f.gsa.gov/2020/12/15/a-dashboard-for-privacy-offices/) mentions a Nixon-era newspaper clipping in the alt text but shows a slide excerpt about devops.

Similarly, the third image shows a slide from a devops blog post rather than a relevant image.

## Actual Behavior

Blog post has an images showing devops testing

![Devops testing protocol](https://18f.gsa.gov/assets/blog/image1.png)
![Devops unit tests](https://18f.gsa.gov/assets/blog/image3.png)

## Steps to reproduce the behavior

- [ ] Visit [this post](https://18f.gsa.gov/2020/12/15/a-dashboard-for-privacy-offices/)
- [ ] Inspect the first and third images
- [ ] See alt text referencing Watergate era newspaper clipping and Google Sheet

## This issue is done when

- [ ] Image URLs are updated appropriately per authors? @ondrae @igorkorenfeld @peterrowland 
- [ ] Images are live

**Comment by igorkorenfeld** [comment]
Thanks for catching this @nicoleslaw, looks like the original images were overwritten by another post, I'll try to get a fix in this week.
