### ISSUE TITLE
Investigate and maybe migrate admin

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3960]
The admin folder has a config and index file for Netlify CMS.

First: do we use Netlify for the 18F site? If we do, we should migrate it to maintain functionality. If not, we should add it to #3864.

To the `replatform-main` branch, we copied the 18f/guides settings, so we should start by diffing that and `main`'s config/index. It seems like `index` has Jekyll-style settings (e.g. `site.baseurl`), so we should replace those as necessary.

Also, it looks like the config file defines settings and YAML fields — we've renamed some of them (like `image_accessibility` is now `image_alt`).

```[tasklist]
### Tasks
- [ ] Admin works equivalently to how it did in the Jekyll framework
```

**Comment by bpdesigns** [comment]
Is this getting used? Or have netlify or cloud.gov pages exp

**Comment by caleywoods** [comment]
When I visit https://18f.gsa.gov/admin and try to sign in with GitHub the Cloud.gov pages window just seems to sit there and not do anything. I know we submit new blog entries through GitHub so it seems like the NetlifyCMS is unused. Netlify also stopped developing/supporting it some time ago and transitioned it to[ DecapCMS](https://decapcms.org/docs/intro/) so if this effort continues we should start with looking at Decap and potentially other headless CMS solutions.

**Comment by beechnut** [comment]
The starting question I have with this ticket is: what is happening with this CMS admin config stuff in 18F/guides? Because it's in that repo. If it's getting used, we should keep parity; if not, we can delete it and move on.

**Comment by jasnakai** [comment]
@beechnut This is my thinking. I am looking into that right now.

**Comment by beechnut** [comment]
I got some history from @igorkorenfeld, who was the last person to touch the 18F/guides admin files. In short, we don't presently use Netlify CMS, so these files are safe to delete.
