### ISSUE TITLE
Re-set up Atom feed (XML)

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3962]
We provide an XML-based Atom feed with latest posts. This came for free with a Jekyll plugin; we'll have to replicate in 11ty.

These articles should help figure out how to set this up:
https://conr.dev/posts/2022/07/rss-for-11ty/
https://www.11ty.dev/docs/plugins/rss/

```[tasklist]
### Acceptance criteria
- [x] Atom feed looks equivalent to production 18F Atom feed
```

**Comment by jasnakai** [comment]
Paired with @19mderose to look into this. Got stuff setup but the current version of the 11ty RSS plugin requires 11ty version 3.0.0 or higher.  The current stable version of 11ty is 2.0.1. Going to look into using an older version of the RSS plugin to get it running.

**Comment by beechnut** [comment]
@jasnakai Can I encourage you to consider solutions that don't require a plugin? I'd suggest taking a look [here](https://www.11ty.dev/docs/plugins/rss/#sample-feed-templates) and at the first blog post listed in the issue — this may be a quicker means to the same end.
