### ISSUE TITLE
Don't make GitHub a requirement to report an issue

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#4032]
The "report a bug" link in the footer forces people to sign up for a GitHub account. [Example](https://github.com/18F/18f.gsa.gov/issues/4031)

This is, for obvious reasons, not ideal. Members of the public should be able to report an issue without a GitHub account.

Proposed solution: Link to a page that has options, first an email option and THEN MAYBE a GitHub option.

**Comment by adunkman** [comment]
Implementation for this should likely be Touchpoints; let’s see how https://github.com/18F/tlc-crew/issues/885 goes.

**Comment by edwintorres** [comment]
This is done by the #885 https://github.com/18F/TLC-crew/issues/885
