### ISSUE TITLE
replatform: title segments are swapped

### ISSUE THREAD

**Issue by cantsin** [18F/18f.gsa.gov#4040]
Example:
```
--- original/work-with-us/index.html	2024-08-06 07:18:37.098383129 -0700
+++ changed/work-with-us/index.html	2024-08-06 07:50:12.862404538 -0700
```

```diff
   <title>
-   18F: Digital service delivery | Work with us
+   Work with us | 18F
   </title>
```

Also, of course, the first title segment should be "18F: Digital service delivery"

**Comment by beechnut** [comment]
I suspect I did this intentionally at the beginning to differentiate between a bunch of open tabs and committed it at some point.
