### ISSUE TITLE
replatform: /contact is missing social media box

### ISSUE THREAD

**Issue by cantsin** [18F/18f.gsa.gov#4054]
local

![20240812_10h41m52s_grim](https://github.com/user-attachments/assets/b64a630d-50c0-4f9d-b41b-ffab37e67b96)

on 18f.gsa.gov

![20240812_10h41m59s_grim](https://github.com/user-attachments/assets/524c6853-f7e6-4832-8b67-865f19ba2863)

**Comment by beechnut** [comment]
Investigating: /contact is the one page that uses a `social_media` boolean to show social media. That doesn't work in 11ty's framework.
