### ISSUE TITLE
replatform: emails should not have external link? 

### ISSUE THREAD

**Issue by cantsin** [18F/18f.gsa.gov#4055]
this one may be up to debate but bringing it up because it is an oddity: the email links have `usa-link--external` tagged on them.

![20240812_10h41m52s_grim](https://github.com/user-attachments/assets/b64a630d-50c0-4f9d-b41b-ffab37e67b96)

**Comment by beechnut** [comment]
No debate from me: this is weird and I don't understand why it's happening, but I have a suspicion about who's (= which software module) is responsible.

**Comment by beechnut** [comment]
Ok, the culprit here is the markdown renderer override `markdownLibrary.renderer.rules.link_open`. It's handling `mailto` links incorrectly, checking its hostname when it doesn't have a hostname.
