### ISSUE TITLE
add mirage api to /developer 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#407]
Any reason we can't go ahead and add https://mirage.gsa.gov/docs/ to 18F's [developer hub](https://18f.gsa.gov/developer/)?  

cc @kaitlin, @jroo

**Comment by gbinal** [comment]
https://discovery.gsa.gov/docs/

**Comment by gboone** [comment]
Good with me if it's good with @kaitlin, @jroo. Are you the only three that need to approve? If so, let's get some language going around this. Glad to help.

**Comment by kaitlin** [comment]
Let's wait until the end of this sprint. @shawnbot is actively working on the look and function of our api docs this sprint.

**Comment by gboone** [comment]
Fell off my radar, but assuming the sprint in question ended someone should issue a pull request to add the api to the developer page.

**Comment by gbinal** [comment]
Finally getting to this as part of #1014.  

https://github.com/18F/18f.gsa.gov/commit/75cf407e6a86b25a557d52980b9c23f83036cb83

Will plan to merge this week barring any concerns.
