### ISSUE TITLE
Remove CircleCI

### ISSUE THREAD

**Issue by caleywoods** [18F/18f.gsa.gov#4080]
## Feature suggestion

The 18F website was recently migrated from Jekyll to 11ty and with that we're now using GitHub actions to [validate HTML, check links, and do linting](https://github.com/18F/18f.gsa.gov/blob/main/.github/workflows/pull-request.yml) on pull requests instead of CircleCI. I'm proposing that we should remove CircleCI.

I wanted to open this issue for discussion before I just go deleting things.

## Work required

From what I can tell, the work is:

* Delete the CircleCI webhook from the [repo webhook settings page](https://github.com/18F/18f.gsa.gov/settings/hooks)
* [Remove the CircleCI deploy key](https://github.com/18F/18f.gsa.gov/settings/keys)
* Tell CircleCI we'd like them to stop building the project by clicking "Stop Building" [at the bottom of the settings page](https://app.circleci.com/settings/project/github/18F/18f.gsa.gov) for the 18f.gsa.gov project on CircleCI
* Remove `.circleci/config.yml` and delete the `.circleci` directory

## Who is going to do this work?

I'm happy to take this on, it seems like a quick thing to do.

### References

* [Stop building a project on CircleCI](https://circleci.com/docs/stop-building-a-project-on-circleci/)
* [How to stop building by manually removing the CircleCI webhook and deploy key from your GitHub repository](https://support.circleci.com/hc/en-us/articles/360021666393-How-to-stop-building-by-manually-removing-the-CircleCI-webhook-and-deploy-key-from-your-GitHub-repository)

**Comment by caleywoods** [comment]
@beechnut @cantsin Tagging you two for visibility of this since. I wasn't sure who else may have context, please add them to the discussion.

**Comment by cantsin** [comment]
I think this makes a lot of sense.  Let's just do it. I don't think this needs a lot of discussion -- I don't think anyone else will complain, as long as tests run _somewhere_ and the test results are shown in pull requests/merges/etc.

**Comment by caleywoods** [comment]
> I think this makes a lot of sense. Let's just do it. I don't think this needs a lot of discussion -- I don't think anyone else will complain, as long as tests run _somewhere_ and the test results are shown in pull requests/merges/etc.

I agree, I was just hoping not to pull the rug out from under someone in case I had overlooked something still being done on CircleCI.
