### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#4117]
[In this post](https://18f.gsa.gov/2021/07/27/the_tts_handbook_a_21st-century_approach_to_internal_documentation/), there's a broken image tag:

```
<img src="/assets/blog/image4.gif" alt="Animated GIF of the TTS Handbook homepage and the "Mission, history, and values" page" />
```

My guess is that the parser can't handle this because the quotes aren't escaped correctly.

**Comment by michelle-rago** [comment]
[PR for review](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/mr/blog-fix-broken-image-link/2021/07/27/the_tts_handbook_a_21st-century_approach_to_internal_documentation/)
