### ISSUE TITLE
Analyze user research to inform 18f site next steps

### ISSUE THREAD

**Issue by meiqimichelle** [18F/18f.gsa.gov#424]
@gboone , @elainekamlley , @kategarklavs and @esgoodman have been working on user interviews to inform next steps on our 18F site.

Analysis will inform next steps on what are currently disparate projects/repos that should likely be together (at the very least in terms of content and visual design):
- 18f.gsa.gov
- 18f.github.io
- hub (+ data sub-modules)
- dashboard
- 18F consulting

**Comment by gboone** [comment]
We're working off of that research now :smiley:
