### ISSUE TITLE
create a tag index page? 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#430]
https://18f.gsa.gov/tags/ doesn't resolve but was where I went to look to try and find a listing of what tags there are.

**Comment by gboone** [comment]
Bumping this. Would like to see not only a list of tags but context around what they are (example posts? descriptions in a `_data` file? Maybe don't include all tags but most used?

**Comment by gboone** [comment]
inspiration: http://alistapart.com/topics

**Comment by melodykramer** [comment]
love the List Apart example.

**Comment by elainekamlley** [comment]
Closes with #875, https://18f.gsa.gov/tags/
