### ISSUE TITLE
Author in blog snippet does not display nicely

### ISSUE THREAD

**Issue by meiqimichelle** [18F/18f.gsa.gov#441]
Author information is pushed into blog snippet text, ie:
![screenshot 2014-12-24 14 14 38](https://cloud.githubusercontent.com/assets/4827522/5551079/42788eb4-8b77-11e4-8abf-9399e6248086.png)

This is because we are using Jekyll's `excerpt` filter that pulls everything from a post up until `<!-- more -->` (in our case). We need to see if there's a way for `excerpt` to **start** after a given point (ie, after the author info), or devise a different solution for making this not look so terrible.

**Comment by gboone** [comment]
The exact issue detailed here is resolved but we need a better way to display authors around here. I'm going to open a separate issue to spell that out and close this one.

(Oh, and I gave it a shot, `markdownify` doesn't work on the `excerpt` field. Bummer.)
