### ISSUE TITLE
Bring sub-features into one repo

### ISSUE THREAD

**Issue by meiqimichelle** [18F/18f.gsa.gov#455]
For discussion:

There are now several repos that are actually a part of 18f.gsa.gov and it is getting more and more difficult to keep assets in sync across them (basically a copy-and-paste job at the moment).

@mbland and @afeld and I started thinking about how to solve this, and then realized that we might have moved past the need for those projects to be in separate repos at all.

Can we put them all under the same roof and treat them as they are -- one cohesive offering?

@mbland also suggested that we can still maintain a template-style, forkable /dashboard or hub (or any other part) as separate repos. The 18f.gsa.gov implementation would then serve as the living example of the templates.

**Comment by konklone** [comment]
> Can we put them all under the same roof and treat them as they are -- one cohesive offering?

It's a lot easier operationally, in most ways. One way where it's not is that it'll be quite a busy issue tracker. The 18f.gsa.gov repo so far has had 160 issues and almost 300 pull requests, just for the landing page and blog -- and it's about to undergo major surgery as part of the redesign effort. That's something to plan for if we merged them.

> @mbland also suggested that we can still maintain a template-style, forkable /dashboard or hub (or any other part) as separate repos. The 18f.gsa.gov implementation would then serve as the living example of the templates.

If I'm understanding that right, there'd be 4 repos? One is just the template, and then 18f.gsa.gov, hub, and dashboard would all pull from it?

**Comment by mbland** [comment]
@konklone Three repos, the other way around: Dashboard and Hub repos would be templates, perhaps.

**Comment by mbland** [comment]
@konklone Another thing to think about: Most of the data will be sourced form data-private, and most of the Hub logic will hopefully be extracted into gems, living in their own repos (like https://github.com/18F/hash-joiner and https://github.com/18F/weekly_snippets). That may cut down on the issue/PR load for 18f.gsa.gov itself. (I think. I hope.)

**Comment by afeld** [comment]
Laid out some of the technical considerations here: https://github.com/18F/18f.gsa.gov/issues/456

**Comment by gboone** [comment]
I added some initial thoughts on keeping them independent on #456 but I'm getting to the point where it feels like it'll be more work to maintain Hub, Dashboard and the rest of 18f.gsa.gov each as separate repos in the long run. I think it's completely possible and maybe easiest if we have this be the repo that handles the blog and display of content. I know we'll still need the `hash-joiner` to run to keep the data in sync and `data-private` and `weekly_snippets` for collecting data for a total of four repos required to run everything, down from the current six. But when someone needs to add a project they should only have to do it once. Styles that we change on 18f.gsa.gov should transfer to dashboard and hub easily. There has been too much duplicated work keeping styles, layouts, etc. in sync for these three repos.

At least with Dashboard, when you take out the data it's basically a template, some pages, and a JavaScript file. We're currently deploying that (and Hub) as an entire second (and third) Jekyll site. Seems like a lot of extra work when we could just put a `dashboard` directory into 18f.gsa.gov and drop the js file in with the other assets. (I'm struggling to remember why we didn't do that in the first place. I remember we thought about it, I think it had to do with the `_data` directory and wanting GitHub pages as a staging space.) 

It's particularly appealing when I think about having three jekyll sites each with three `_data` directories running `hash-joiner` to parse out the public information in `data-private`. When @mbland and I were talking about that earlier this week it seemed doable but also felt like there was a simpler solution.

I like that right now you can get a copy of the bulk of 18f.gsa.gov running locally by cloning only this repo and following the installation instructions. I'd like it even more if you could get all of 18f.gsa.gov.
