### ISSUE TITLE
bring the sites together?

### ISSUE THREAD

**Issue by afeld** [18F/18f.gsa.gov#456]
@meiqimichelle brought up the issue that she would like to share styles/assets across the homepage, the dashboard, and the Hub – a.k.a. https://18f.gsa.gov and everything under it. We started talking about how to share the assets, but then took a step back and asked ourselves: does it still make sense for all of these to be separate repositories/projects? There's something to be said for keeping each of the sections separate:

* the repositories stay smaller
* easier to reason about
* less potential for inadvertently breaking something on a different page
* less mixing of issues/PRs for unrelated things

That being said, keeping separate repositories might be more hassle than it's worth, especially if @meiqimichelle is planning some degree of visual convergence. If we *do* want to keep the repositories separate, we can share+version the assets via:

* a submodule
* a Bower package
* a shared CDN (i.e. https://static.18f.us/assets/N.N/shared.css or something)

Thoughts? CCing top/recent contributors from all of the repos because I'm not sure who works on what, but please add people if I missed anyone.

/cc @leahbannon @mbland @gbinal @konklone @gboone

**Comment by gbinal** [comment]
I'm neutral.

**Comment by afeld** [comment]
Derp, @meiqimichelle beat me to it: https://github.com/18F/18f.gsa.gov/issues/455

**Comment by gboone** [comment]
If we want to keep the three projects as separate repos, I like the submodule idea. I imagine it would work like:

1. Package the templates in one (probably a fourth) repo containing only `_includes`, `assets/js`, `assets/css` and `_layouts` we use across the three projects.
1. install it as a git submodule

Thinking about it more, I like the idea of a bower package, too. I haven't worked with it much but it seems like it could simplify our current webhook situation involving six `forever` jobs down to maybe one hook that can deploy each thing.

The shared CDN is appealing, too.

**Comment by afeld** [comment]
Yeah, let's decide whether or not to combine the sites in https://github.com/18F/18f.gsa.gov/issues/455, but we can pick up this discussion if we do end up needing to share things.

**Comment by konklone** [comment]
From the perspective of developer experience, the shared CDN seems the lightest lift. This could just be its own repo, which is automatically synced in its entirety to S3/CloudFront.

Others seem to be more comfortable with git submodules than me, but I've always found them rather hostile and kludgey to work with.
