### ISSUE TITLE
Support oEmbed for various third party services

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#487]
As a blog editor, I want an simpler way to embed content so that I can spend less time properly embedding tweets, YouTube videos and other resources blog authors might include in their posts.

Sketch of what we might want:

```
The following code will embed the video below the current paragraph:
{% oembed https://www.youtube.com/watch?v=5l-7vmArLJY %}
```

Regardless of whether oEmbed is the ultimate solution, we should support:
- [ ] YouTube videos
- [ ] Instagram photos
- [ ] Tweets
- [ ] IFTTT recipes
- [ ] GitHub Gists
- Embedding should be done over https
- Embedding should be done without cookies
- Embedding should be done without introducing new embedded third-party applications

[oEmbed supports almost all these](http://oembed.com/#section7) except, perhaps, GitHub Gists

**Comment by gboone** [comment]
It looks like there's a jekyll plugin we could use to accomplish this. We'd want to make sure the embedded elements fit within the expected space across different devices.

**Comment by gemfarmer** [comment]
@micahtaylor have you looked into the oEmbed jekyll plugin, or is this something I should tinker with?

**Comment by gemfarmer** [comment]
Some potential resources:
- [Jekyll plugin ruby code](https://gist.github.com/vanto/1455726)
- [`jekyll-oembed` gem](https://github.com/stereobooster/jekyll_oembed)

On first glance, it looks like `jekyll-oembed` isn't executed quite as well as the ruby plugin code. We could use either, but a contribution could be to create a `jekyll-18f-oembed` gem that creates a gem from the plugin.

**Comment by gemfarmer** [comment]
Look what I made! 

https://github.com/18F/jekyll-oembed

**Comment by coreycaitlin** [comment]
Is this good to close, @gemfarmer?
