### ISSUE TITLE
Memorialize how/when to add APIs to /developer page 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#509]
E.g., need to add https://18f.gsa.gov/api/v1/pages.json, but also memorialize when/how to add, too.

**Comment by gboone** [comment]
How: branch -> pull request (see CONTRIBUTING.md)
When: As you find new APIs, feel free to add them if they're [worthy of inclusion per the /developer program](http://18f.github.io/API-All-the-X/)
