### ISSUE TITLE
Migrate from pygments to rouge for syntax highlighting

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#511]
[`rouge`](https://github.com/jneen/rouge/) is a Pygments-compatible pure-Ruby library for syntax highlighting.

Using this instead of `pygments.rb` will remove the Python dependency from this app entirely and improving rendering stability and speed.

**Comment by gboone** [comment]
:+1: Is this as simple as replacing the `pygments` with `rouge` in the `_config.yml`?

**Comment by konklone** [comment]
It could be! I'm excited to find out.
