### ISSUE TITLE
add technical architect to join-us page...

### ISSUE THREAD

**Issue by cscairns** [18F/18f.gsa.gov#547]
See: 

https://docs.google.com/a/gsa.gov/document/d/1eyXfiLUO3AbjICEJetiIMrQI5cwkMHPJpOun5HBdJxY/edit

**Comment by NoahKunin** [comment]
Which page?

**Comment by gboone** [comment]
Want to hear from HR as part of other HR content strategy discussions already in progress.

**Comment by afeld** [comment]
It lives!

https://pages.18f.gov/agile-labor-categories/positions/technical-architect/

**Comment by afeld** [comment]
I only seem to have read-only access to that doc...would someone mind deleting the contents and linking to [the repo](https://github.com/18F/agile-labor-categories), so that we have a canonical place for the text? Thanks!

**Comment by gboone** [comment]
All those positions are on page.18f.gov now right? Should we ask @cscairns to delete the doc?
