### ISSUE TITLE
Moving to Jekyll 3

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#591]
The Hub just [moved to Jekyll 3 beta 2](https://github.com/18F/hub/pull/206), and if it doesn't break, maybe we should do that too. It at least lets us ditch the Node and Python dependencies.

**Comment by gboone** [comment]
Great idea, I've been playing around with it on a side project and don't anticipate any issues. Hoping to get some time to make the switch this week.

**Comment by gboone** [comment]
We're on Jekyll 3 without problems as of last week but lets leave this open until Jekyll 3 is a full release.
