### ISSUE TITLE
My method of using Git

### ISSUE THREAD

**Issue by jcgallaher** [18F/18f.gsa.gov#600]
In reply to your article: https://18f.gsa.gov/2015/03/03/how-to-use-github-and-the-terminal-a-guide/

I use Linux and Vim 7.x. or Windows Git terminal. Server wise it's nice that Vim runs on the Linux server as well so you can port your customized Vim settings in both ends.

**Comment by melodykramer** [comment]
Thanks @jcgallaher - adding @gboone to this conversation as well.

**Comment by melodykramer** [comment]
Could you add this comment to this ongoing thread? https://github.com/18F/18f.gsa.gov/issues/542 We're pointing people who want to know more there, and it would be helpful to have all of the information together.

**Comment by jcgallaher** [comment]
No problem. All done!
