### ISSUE TITLE
Create team landing page

### ISSUE THREAD

**Issue by juliaelman** [18F/18f.gsa.gov#610]
See @mkhandekar comments below in regards to the goals and objectives for this page.

**Comment by mkhandekar** [comment]
Content guidelines for Team Landing

**Goals:**

Exhibit the diverse skills and backgrounds, and geographically distributed nature of team. First two audience groups are agencies who are and/or are thinking of working with us, and potential hires who want to work with us. We want to present ourselves in a professional and accessible way. 

**Content:**

- Intro
- We’re a team of x, experience in x things, around the US, meet us (this is to be written)
- Pictures + Name

**Possible ways to filter:**

- What projects are they / have they worked on?
	- Information will be pulled from the Hub, so we’ll have access to:
		- Project title
		- Short description
		- Team members
- What team are they part of? 
- Teams from Org Chart
	- Delivery
	- Experience Design
	- PIFs
	- DevOps 
	- Infrastructure
	- Business operations & Personnel
	- Consulting
	- Hiring operations
- Where are they?
	- A more generalized way to show location: GSA regions
		- Northwest / Arctic
		- Pacific Rim
		- Rocky Mountain
		- Greater Southwest
		- The Heartland
		- Great Lakes
		- Southeast Sunbelt 
		- Mid-Atlantic
		- Northeast & Caribbean 
		- New England

**Comment by juliaelman** [comment]
Closing this issue in favor for #644
