### ISSUE TITLE
Create team profile page

### ISSUE THREAD

**Issue by juliaelman** [18F/18f.gsa.gov#611]
See @mkhandekar comments below in regards to the goals and objectives for this page.

**Comment by meiqimichelle** [comment]
_excited, excited, excited_ :D

**Comment by mkhandekar** [comment]
Content guidelines for Profile 

**Goals:**

To shine a light on each team member’s (as much as they want to make public) background and contributions to 18F. 

**Content:**

- Picture
- Bio 
	- narrative about themselves
	- bios are currently in two forms:
		- Raw answers
		- Starting to be re-written / polished with this rough format:
			- Section 1: Elevator bio: Name*, role*, key duties
			- Section 2: Previous work experience* and educational background 
			- Section 3: Personal vision statement* and what drew person to 18F 
- Projects
	- same as above (information will be pulled from the Hub)
		- Project title
		- Short description
		- Team members

- Skills
	- these will be a mix of: 1) being pulled from the bios they have written, and 2) from the Hub
		- Language
		- Speciality
		- Technology
- Blog posts
	- Blog titles and URLS to blog posts they have written
- External links
	- with a note / disclaimer that this is not for personal gain, but for transparency. Let’s make this flexible so if not allowed, we're able to take links out
		- github
		- twitter

**Comment by meiqimichelle** [comment]
Note: the current separation of skills into those three categories (language, specialty and technology) does not need to stay (and I hope it doesn't). I'm sure you/we can come up with clearer words and structure :)

**Comment by juliaelman** [comment]
@meiqimichelle :+1: thanks for the feedback! We'll be posting some high fidelity wireframes shortly.

**Comment by juliaelman** [comment]
Closing this issue in favor of #644
