### ISSUE TITLE
Create new team landing and individual bio pages

### ISSUE THREAD

**Issue by juliaelman** [18F/18f.gsa.gov#644]
Originally, we created two different issues for this work. As we have been moving forward it makes more sense to merge these into a singular issue.

Here are the notes that @mkhandekar originally posted on #610 and #611:

### Goals

Exhibit the diverse skills and backgrounds, and geographically distributed nature of team. First two audience groups are agencies who are and/or are thinking of working with us, and potential hires who want to work with us. We want to present ourselves in a professional and accessible way. 

### Content

- Intro
- We’re a team of x, experience in x things, around the US, meet us (this is to be written)
- Pictures + Name

### Possible ways to filter

- What projects are they / have they worked on?
	- Information will be pulled from the Hub, so we’ll have access to:
		- Project title
		- Short description
		- Team members
- What team are they part of? 
	- Teams from [Org Chart](https://docs.google.com/a/gsa.gov/presentation/d/1YxmCzPrJXWGZU8Z-WlGA-qoI-CLXuQvqMkr5nk8eJiA/edit#slide=id.g56199479b_0249)
		- Delivery
		- Experience Design
		- PIFs
		- DevOps 
		- Infrastructure
		- Business operations & Personnel
		- Consulting
		- Hiring operations
- Where are they?
	- A more generalized way to show location: [GSA regions](http://www.gsa.gov/portal/category/22227)
		- Northwest / Arctic
		- Pacific Rim
		- Rocky Mountain
		- Greater Southwest
		- The Heartland
		- Great Lakes
		- Southeast Sunbelt 
		- Mid-Atlantic
		- Northeast & Caribbean 
		- New England

### Goals

To shine a light on each team member’s (as much as they want to make public) background and contributions to 18F. 

### Content

- Picture
- Bio 
	- narrative about themselves
	- bios are currently in two forms:
		- [Raw answers](https://docs.google.com/a/gsa.gov/spreadsheets/d/17ywBmqaejFhgri2EkFQTcY_s7BIOzHJD6D12HpZSCeA/edit#gid=0)
		- [Starting to be re-written / polished with this rough format:](https://docs.google.com/a/gsa.gov/document/d/1TQfYbGpLhABpnVaytvugJbhq0wLef09oGBgQR0svbTk/edit)
			- Section 1: Elevator bio: Name, role, key duties
			- Section 2: Previous work experience* and educational background 
			- Section 3: Personal vision statement* and what drew person to 18F 
- Projects
	- same as above (information will be pulled from [the Hub](https://hub.18f.us/projects/))
		- Project title
		- Short description
		- Team members

- Skills
	- these will be a mix of: 1) being pulled from the bios they have written, and 2) from [the Hub](https://hub.18f.us/projects/)
		- Language
		- Speciality
		- Technology
- Blog posts
	- Blog titles and URLS to blog posts they have written
- External links
	- with a note / disclaimer that this is not for personal gain, but for transparency. Let’s make this flexible so if not allowed, we're able to take links out
		- github
		- twitter

**Comment by gboone** [comment]
Closing this in favor of #698
