### ISSUE TITLE
Making Twitter Images More Accessible

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#648]
Opening a thread for suggestions on how to make Twitter images more accessible on 18F's blog, related to an upcoming blog post.

**Comment by konklone** [comment]
If possible, I think this would be a great opportunity (before publishing) to reach out to Twitter for any ideas or upcoming features they have about accessibility of media on Twitter.

**Comment by kategarklavs** [comment]
@konklone +1 to this idea ^^

**Comment by melodykramer** [comment]
Emailing Twitter. Stay tuned.

**Comment by susanica** [comment]
I remember when accessibletwitter.com launched in Beta in about 2010. Looks like it is now easychirp.com  Do you guys at 18F work with initiatives like that to try to make a more accessible experience for all. Kudos on the fantastic attention to sec 508 of the Rehabilitation Act!

**Comment by melodykramer** [comment]
@susanica We haven't worked with [EasyChirp](http://www.easychirp.com/), which looks like it has alt text built into its features. I wrote to Twitter earlier and asked if "alt text" was coming down the pipeline. Will post when they respond.

**Comment by susanica** [comment]
Cool. Thx.

On Tue, Mar 24, 2015 at 4:41 PM, Melody Kramer <notifications@github.com>
wrote:

> @susanica <https://github.com/susanica> We haven't worked with EasyChirp
> <http://www.easychirp.com/>, which looks like it has alt text built into
> its features. I wrote to Twitter earlier and asked if "alt text" was coming
> down the pipeline. Will post when they respond.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.gsa.gov/issues/648#issuecomment-85684615>.
>



-- 
Monica Fitzgerald, PMP
GSA IT
(c) 202.441.3371
(w) 202.219.0723

*"Don't ask what the world needs. Ask what makes you come alive and go do
it, because what the world needs is people who have come alive."* -Howard
Thurman

**Comment by poorgeek** [comment]
A brief explanation of [how EasyChirp provides alt text, and even longdesc support, for images](http://www.easychirp.com/img_help).

**Comment by HobokenMartha** [comment]
Also ask folks *via* Twitter, use #a11y to ask.

**Comment by HobokenMartha** [comment]
I was following this group for a while (sadly gotten overwhelmed):  eyes-free@googlegroups.com

**Comment by dsmorgan77** [comment]
You should totally check out and link to this: http://www.digitalgov.gov/resources/improving-the-accessibility-of-social-media-in-government/

**Comment by melodykramer** [comment]
will do @dsmorgan77 - thanks for the link.

**Comment by weboverhauls** [comment]
You can tweet a link to an image with a short description (title) and a long description with the Easy Chirp web application. Details: http://www.webaxe.org/easy-chirp-now-provides-accessible-images-for-your-tweets/

**Comment by SteveBuell** [comment]
There is this as well, Notes on providing alt text for twitter images: http://www.paciellogroup.com/blog/2015/01/notes-on-providing-alt-text-for-twitter-images/

**Comment by aardrian** [comment]
As some have noted, if you ask on Twitter please use the #a11y hashtag. People who work as professional accessibility consultants and builders (and consumers of accessible media) follow it.

That being said, feedback from random folks on Twitter won't be too helpful (and can quickly devolve into a popularity contest, not a valid discussion). Links to researched and thought-out pieces from people who live and breathe this every day will be more valuable. The link to the Paciello Group is a great resource, and written by Steve Faulkner, one of the editors of HTML5 and also ARIA and many other accessibility techniques/technologies on the web.

It's also a bit brief and doesn't provide a quick hit list of options. He does, kindly enough, link to the list I made (http://blog.adrianroselli.com/2014/12/dont-tweet-pictures-of-text.html) which I reproduce here:

— Link to the full text of the source. Many tweets are screenshots from web pages, so link to them.
— Use Tumblr or a similar platform. Twitter Cards will embed the image into the tweet (it won't do that for Instagram).
— Tweet your own text version or abstract in a follow-up tweet (as a reply to the original tweet so they stay connected in the Twitter stream).
— When you are retweeting someone else's image, include an abstract or link to the source. Ask the original tweeter for the text or the URL of the source.
— Use a tool meant for this purpose, like Easy Chirp (Dennis Lembrée is a good guy, he can answer your questions on how to make the most of it). An example: https://twitter.com/aardrian/status/524294234833051650
— Write less. Get to the point, focus on the message, write for the medium.

I'd also like to reiterate why you shouldn't *rely* on images, which goes well beyond just accessibility:

— Maybe the user is on a tiny device and whilst the font here is readable the text in a small JPG with artifacts is less so.
— Maybe the user is on an unreliable connection and the image hasn’t loaded yet.
— Maybe the user has a mis-configured ad-blocker that is overzealous with its blocking.
— Maybe the tweet isn't in the reader's native language and he/she wants to translate it.
— Maybe the text contrast is too low for a small screen or sunlit screen.
— Maybe the user is bumping against data caps and has to pay for each extra byte.
— Maybe the user is on a feature phone (think of citizen travelers outside of North America and Europe).
— Maybe the user relies on searching the text to find relevant tweets. There is an opportunity cost to not using text.

**Comment by melodykramer** [comment]
Thank you @SteveBuell and @aardrian.

**Comment by dagreatemly** [comment]
I'm not a heavy Twitter user, but could there be some way to embed some html-type text "behind" the image, the way images have images in traditional html has a text attribute in case a browser doesn't render the image...Typically, the text in those cases is along the lines of "Media not supported."  But there's no reason why the html text could represent the image for accessibility purposes?

**Comment by aardrian** [comment]
@dagreatemly, while what you ask fits best practices for web development, there is no affordance for that feature provided by Twitter.

So far, Twitter does not provide any interface for a user to add any alternative text for an image, video, or other media. Many have asked for this over the years, and its absence has spawned the techniques I outlined above, as well as tools like Easy Chirp.

Until Twitter steps up and builds accessibility features into its platform, this has to be another community-driven solution (much as the RT, or @-messaging someone)

**Comment by weboverhauls** [comment]
I hear Twitter is working on this issue. In the meantime, Easy Chirp is the only Twitter app that provides this "feature".

**Comment by aardrian** [comment]
Fun fact, Twitter's new tweet quoting feature can help make images more accessible, though it has some caveats. I wrote up some details at http://blog.adrianroselli.com/2015/04/twitter-accidentally-takes-step-toward.html, but the quick hit list:

— Twitter's (current) prohibition on retweeting oneself means that users cannot easily quote their own tweets to add alternative text — at least not in the Android app nor on the web. TweetDeck allows it, so perhaps we'll see it in the app or web site.
— Because a quoted tweet is not a reply, it doesn't show up in the list of replies when viewing the original image tweet. This means a missed opportunity to be associated with the alternative text when viewed on its own.
— When viewing the tweet providing the alternative text (as a standalone tweet, not in the timeline) in the Android app, the image within the quoted tweet is not displayed.
— Embedding a tweet that acts as alternative text doesn't show the original quoted tweet (nor its image). There isn't an option to embed media, so web page authors will likely embed the original image tweet instead of the alternative text tweet.
— Twitter is missing an opportunity to provide an interface that prompts users to provide alternative text. This might help stem the inconsistent efforts from those who want to provide accessibility.

**Comment by makevuy** [comment]
Hello everyone!,

Just one simple, maybe reiterative question (I am sorry if that is the case)

If I add the ALT text to the image before be tweeted, twitter platform conserve that ALT text? It would be  accessible in that case? 

Thank you very much in advance!

**Comment by awfrancisco** [comment]
One year to the week of when this issue was opened [Twitter adds alt text field to mobile apps](https://blog.twitter.com/2016/accessible-images-for-everyone)

**Comment by aardrian** [comment]
Sadly no timeline on web support and it requires the tweet author to enable the feature to even see the option in the interface, but yay! Progress!
