### ISSUE TITLE
How You Can Welcome New Coders To The National Civic Day of Hacking

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#668]
At 18F, we open source our projects, and nothing makes us happier than getting contributions from people who don’t work here. That’s why we published a [contributor’s guide to our code](https://18f.gsa.gov/2014/08/12/the-contributors-guide-to-18f-code-for-the-common/).

Now with the National Day of Civic Hacking fast approaching, we’ve been thinking about how to make our projects as accessible as possible for anyone who would like to adapt them and/or help us improve them. 

We’re passing along the ideas we’ve batted around, with the hopes that it will help anything you’re planning for the National Day of Civic Hacking on June 6, 2015. We’re also really interested in throwing these ideas to the wider community for thoughts and feedback on how to further improve them. Please leave a comment on this GitHub issue to share any ideas you have.

[full post is here](https://18f.gsa.gov/2015/04/03/how-to-welcome-new-coders-to-a-civic-hackathon/)

**Comment by shaunagm** [comment]
Here are some things I've written about making sprints, hackathons, etc, friendlier and more welcoming to newcomers:

http://opensource-events.com/
http://www.shaunagm.net/blog/2013/10/hacking-the-hackathon/
http://blog.openhatch.org/2015/preparing-for-the-pycon-sprints/

**Comment by Nolski** [comment]
The two biggest things that I have seen that have hooked new comers has either been:
1. Offer lots of prizes. 
2. Keep them small and target a specific group of people.

**Comment by Nolski** [comment]
@decause could offer some valuable input on this as well

**Comment by phildini** [comment]
There's a bit on the blog post @melodykramer linked that I think is really crucial, and I would love to see more of the orgs participating in National Day publicize: Making the team available to non-team members. 

There are some things that a potential contributor may not want to discuss through GitHub issues, or for which they feel an issue is the wrong medium. Having well publicized mailing lists and/or chat rooms for (at least) each org and (ideally) each large project cluster would be amazing. 

Some benefits:
- New contributors have an immediate place they can go for help.
- Mailing lists (or chat channels with saved history/scrollback) build shareable documentation about decisions and processes automatically

As an aside, when I was working on some pull requests to various 18f repos, I desperately wished for a mailing list or chat channel I could ping ideas off of, or raise questions about the systems architecture.

Thanks for listening to my mini-rant, looking forward to the NDCH!

(Also, hi @shaunagm!)

**Comment by melodykramer** [comment]
@phildini We're trying to figure out the best chat/listserv method for outside contributors at the moment. Thanks for your ideas!

**Comment by decause** [comment]
In the past, many local event organizers have had agencies reach out to them directly and offer to partner on specific projects and initiatives (our local events in Rochester have featured challenges and speakers from the EPA, for example.) I would recommend reaching out to the national organizers, and seeing if you can get a list of cities/events that are not already partnered with a federal agency, or see if they will put your projects out on blast during the next organizer's call.

Either way, the most important thing for getting new contributions, IMHO, is to be sure you have *clear* action items, that are surmountable in the time of the event, with *dedicated* upstream mentors ready to synchronously provide feedback. That sounded kinda buzzword-y, so:
 - Clear action item(s) (FIX #1337: CSS Bug on http://github.com/18f/18f.gsa.gov/issues/668)
 - Clear documentation (README with instructions for getting stack up and running, styleguides, etc...)
 - Person in IRC/Chat actively answering questions from contributors, and ideally hacking with them.

SecondMuse historically does a great job vetting the "problems" that agencies come up with, so working with them will likely help with that first bullet point. 

There is *nothing* worse than spending an entire hackathon trying to get "to the starting blocks" and failing to get a stack just up and running. It is demoralizing, and makes new contributors very discouraged. Be sure that whatever contributions you are looking to garner have stacks that can be trivially installed on Linux/Mac/Windows. (i.e. - shipping a <code>requirements.txt</code> or <code>setup.py</code> with your python project, or even better, distributing to http://pypi.python.org for easy installation.)

Having that mentor available to kick down blockers and vgrep tracebacks is the difference between a new contributor spending 3 hours hunting down an error, or a mentor providing that 'obvious-to-them-seen-it-a-million-times-one-liner-fix' in 3 minutes. If you can get mentor that can commit to the *entire* event, that is a super amazing morale boost for new contributors. There is a certain magic in looking in channel or around room and seeing upstream hacking right alongside you in the trenches deep into the wee hours of the morning.

Hope this helps, and if I can be a resource for you folks, please reach out.
--RemyD.

Fedora Community Lead & Council Member
<decause@redhat.com>
http://whatcanidoforfedora.org

**Comment by dezzie** [comment]
I've gotten laughed at for suggesting this at other hackathons in DC, but I still stand by it: 

Offer food other than pizza and alcohol. Some people have food allergies/issues or wish to be sober–a hackathon is exhausting, and having food that makes you feel sick doesn't help.

**Comment by bsweger** [comment]
Two years ago, when working on the inaugural Hack for Western Mass, the most common question we got was "do I have to be a programmer?" Someone at Transparency Camp that year (unfortunately, I can't remember who) had a great movie analogy to answer this question.

You can't have a hackathon with just programmers any  more than you could make a movie with just actors.

We blogged the expanded version of this here: http://hackforwesternmass.org/2013/have-to-be-a-programmer

**Comment by bsweger** [comment]
It's really heartening to see that large, established open source projects are also getting better at welcoming new contributors. 

Pandas (a widely-used, data-oriented Python library) has a [getting started guide](https://github.com/pydata/pandas/issues/9811) for new folks. And they've opened a GitHub thread for people who want to hack on Pandas during PyCon: https://github.com/pydata/pandas/issues/9811

Their audience might not be new coders, but their approach represents an excellent trend.

**Comment by JoshData** [comment]
Shamelessly plugging https://hackathon.guide.

Welcoming new people is an impossibly hard problem. I generally now assume that projects will be unprepared to onboard newcomers (if I'm wrong, great!) and structure the hackathon around that, i.e. with activities targeted at welcoming (workshops etc).

:+1: to the :-1: on pizza and alcohol. I also am :-1: on prizes.
