### ISSUE TITLE
Perform Usability Testing for Team/Individual Bio Mock Up

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#692]
Based on user researched design mandates, mock ups of the new template have been created in InVision: http://invis.io/T62M63D7C

- [x] Schedule Interviews
- [x] Conduct Interviews 
- [x] Compile Results

**Comment by elainekamlley** [comment]
Tagging myself to be assigned this issue @elainekamlley

**Comment by melodykramer** [comment]
Also tagging @andrewmaier

**Comment by elainekamlley** [comment]
Here are the complied results for this round of user testing: https://mural.ly/t/gsa6/m/gsa6/1430147006067

We interviewed 6 individuals, 2 outside of government who fit the criteria of candidates 18F looks for as potential employees and 4 inside government at various agencies.
