### ISSUE TITLE
Small bios for each team member

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#694]
Here's a link to the (barebones) template for team member bios: https://docs.google.com/a/gsa.gov/document/d/1TQfYbGpLhABpnVaytvugJbhq0wLef09oGBgQR0svbTk/edit?usp=sharing

**Comment by gboone** [comment]
Drop the photos and bios into the markdown files in #645

**Comment by elainekamlley** [comment]
We have collected the majority of staff bios during the LifeTouch sprint and now have a process of collecting new hire bios.
