### ISSUE TITLE
Getting PRA clearance for Ethnio research participant recruiting

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#699]
PIA submitted April 3. Now waiting for outcome.

**Comment by esgoodman** [comment]
Note that the official determination was that Ethnio does not require PRA clearance but does need to get approval of a Privacy Impact Assessment (PIA) for the personally identifiable information we are collecting.

**Comment by gboone** [comment]
This is so rad. Thank you and @onezerojeremy for pushing forward with this. It'd be great if we could blog about how we got through this process once we're further into it.
