### ISSUE TITLE
Discuss improvement(s) for /dashboard page and whether /projects page is needed in addition to /dashboard page

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#703]
do we have a /projects in addition to /dashboard? If we do have both, why and how are they different?

Need to get better descriptions for the Dashboard: "how do you describe this project to people at a dinner party?"

Clarify what the stages mean on Dashboard (they're stolen from GDS now)

could this task be reworded "Make Dashboard Better"

**Comment by mattlangan** [comment]
Is this still an open issue with 18F? What are you looking for from the community? A design proposal? Feedback? Personal preferences? Happy to contribute in whatever way I can.

**Comment by gboone** [comment]
We don't have `/projects` in addition to `/dashboard` and we're currently working on "Make Dashboard Better," though it is a slow process. We're getting some ideas going in the @18F/Dashboard repo, .
