### ISSUE TITLE
Determine structure and content of /consulting page

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#705]
To what extent does 18f.gsa.gov need a /consulting page and to what extent is the content on 18f.github.io/consulting fixed content we need to use?

How can we better pull in the blog posts? Watch for a tag?

Different sections for presentations, tools, and blog posts?

**Comment by jtag** [comment]
Temp fix is the page was moved to https://18f.gsa.gov/consulting/ with old content. Consulting team aiming to update this page as another temporary fix in the next two weeks. @vzvenyach @blacktm @jtag best consulting contacts for questions.

**Comment by awfrancisco** [comment]
Working draft of /consulting content here. 
https://docs.google.com/document/d/1Pmd8LNdKxMOfdCCuO63PmXf1GasL3UqhdmYpBWcwzpg/edit#

**Comment by elainekamlley** [comment]
This issue will be addressed as apart this content sprint. At the end of this sprint the goal is to have a finalized version of `/consulting` subpage and 150 word intro paragraph that will be on the home page. @awfrancisco @blacktm

**Comment by elainekamlley** [comment]
This is now live. https://18f.gsa.gov/consulting/
