### ISSUE TITLE
Create a press kit

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#706]
Should include things commonly requested by the press or artifacts the press might need were they to need basic information about our organization. Possibly in a static HTML and downloadable format.
- [ ] contact info
- [ ] Relationship with USDS
- [ ] Relationship within GSA
- [ ] How we operate (budget, structure, leadership, etc.)
- [ ] High resultion logos
- [ ] Style guidance for the 18F mark and name (it's always capitalized, don't mess with the logo, etc.)

**Comment by melodykramer** [comment]
I am happy to take this on. I can put it all in one place on Drive so when we're ready to go forward with design, the content is all there.

**Comment by quepol** [comment]
Ping @jehlers or @ericronne re branding guidelines. I'm sure both have been involved in creating them, and we could just fork CFPB's :)

Let me know what kind of language you need re. USDS and GSA. We need to make the USDS stuff succinct but clear. I'm happy to write up our current spiel, or tell it to someone, with the understanding it will likely need to be edited down.

Logos: 
- [18F stuff](https://drive.google.com/drive/u/0/#folders/0B84F26FpUP0lR1B2VVNGSi1MMVk/0B-y3CqI2T1nnYjdMaFhCNEtQdjQ)
- [PIF stuff](https://github.com/18F/PIF-logo-v2)

**Comment by melodykramer** [comment]
@quepol Anything you currently have would be great. I like the CFPB site:

http://www.consumerfinance.gov/newsroom/

but think it might be more than what we need at the moment, because I don't see us issuing press releases as frequently as they do. Other good press sites:

http://www.rdio.com/press/

https://instagram.com/press/

https://www.kickstarter.com/press?ref=footer <-- start here

https://www.etsy.com/press

**Comment by melodykramer** [comment]
Created folder here: https://drive.google.com/a/gsa.gov/folderview?id=0By2N7o0ZndaMfjRXOHlZWFdjUUZFeDBoSWhHZEtvN1ZrcEo2UUNMaXZFVVZlWWR2S0k1VEE&usp=sharing

**Comment by melodykramer** [comment]
@quepol took a stab at first draft for press page: https://docs.google.com/a/gsa.gov/document/d/1UBRyQfQ9vBuOrVe8nnpQp2Sz21H9262DtF0FkHZZock/edit?usp=sharing 

based it on https://www.kickstarter.com/press?ref=footer

**Comment by quepol** [comment]
This is awesome. I'll have time to go through this on my flight home.
