### ISSUE TITLE
Figure out how to publish better

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#710]
Use Hubot to schedule builds without pushing a commit to GitHub. A bot command like bot build 18f-site at 9AM tomorrow would allow us to queue posts for future publishing. We could have other commands that show scheduled builds and also have the bot report back when the site built successfully (or not).

**Comment by melodykramer** [comment]
https://github.com/benbalter/comment-card

**Comment by melodykramer** [comment]
https://github.com/blog/1939-how-github-uses-github-to-document-github

**Comment by melodykramer** [comment]
https://18f.slack.com/archives/18f-site/p1420581238000057

**Comment by melodykramer** [comment]
https://github.com/18F/18f.gsa.gov/issues/240

**Comment by gboone** [comment]
The description is a snapshot of my thought _not_ necessarily the right or best way to go about it. @dlapiduz have chatted about a few different options that don't involve hubot.
