### ISSUE TITLE
Revisit photo composition

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#716]
Give some good examples and provide some advice for people taking photos.

**Comment by ericronne** [comment]
Draft...
https://docs.google.com/a/gsa.gov/document/d/1xEFRPtJBrsJH-0ZhL9Wq1T8iILGydM-7R11iPTVWJVg/edit?usp=sharing

**Comment by elainekamlley** [comment]
This looks good to me @ericronne! @gboone what should be the due date for people to submit photos?

**Comment by ericronne** [comment]
Revised the doc, please add comments, thx!
https://docs.google.com/document/d/1xEFRPtJBrsJH-0ZhL9Wq1T8iILGydM-7R11iPTVWJVg/edit

**Comment by elainekamlley** [comment]
This looks great @ericronne, love the examples. I added the link to the google doc for people to upload directly to the folder. Also, what should be our naming convention? first and last name, all lowercase?

**Comment by ericronne** [comment]
@elainekamlley i defer to @gboone for thoughts on file naming

**Comment by gboone** [comment]
They have to be consistent once we get them into the site. It'd definitely be easiest if we named them ahead of time. The convention for the site is: the name of the file needs to match the "slug" for you page on the hub. So, for example, @ericronne's photo needs to be named `ericronne` because his page is at: https://hub.18f.us/team/ericronne/

In _some_ cases that name matches github profiles, but not always.
