### ISSUE TITLE
remove jane from team.json

### ISSUE THREAD

**Issue by janearc** [18F/18f.gsa.gov#734]
i haven't done it myself because i'm not sure how to properly remove myself or whether this is a machine-generated file. see #733 and [devops #312](https://github.com/18F/DevOps/issues/312).

**Comment by gboone** [comment]
It's machine-generated by the hub. Once you're removed from 18F/data-private you'll also be removed from 18f.gsa.gov. I'll update 18F/DevOps#312 to reflect this. (Closes #733)
