### ISSUE TITLE
blog RSS feed is broken 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#756]
Linked from https://18f.gsa.gov/news/, the RSS feed (https://18f.gsa.gov/feed/) is broken.  

![screen shot 2015-04-23 at 3 18 21 pm](https://cloud.githubusercontent.com/assets/633088/7305482/12a17012-e9cc-11e4-8bca-fb4deb003a65.png)

**Comment by konklone** [comment]
Locally it looks like this:

![image](https://cloud.githubusercontent.com/assets/4592/7305751/2e1f0118-e9ce-11e4-90c4-6e200a4a8ab6.png)

I wonder if it's a regression based on how Jekyll 3 treats things?

**Comment by gboone** [comment]
It's possible. They do have this ominous warning about using the beta software in production. :shrug: @mbland did you run into any problems like this moving the hub to 3.0?

**Comment by mbland** [comment]
@gboone I didn't hit _that_ issue. There isn't a feed for the Hub.

**Comment by gboone** [comment]
Did you hit any issues with non-html files not generating properly? In old jekyll that file was called index.xml, now it's being called index.html.xml, did that ever happen with, like, the json files we're generating?

**Comment by mbland** [comment]
Not that I'm aware of. `find _site -name '*.html.*'` inside a newly-generated Hub returns nothing.
