### ISSUE TITLE
For Review  Content  Needs Approval

### ISSUE THREAD

**Issue by ericdwain** [18F/18f.gsa.gov#795]
 18F / 18f.gsa.gov 

@ericdwain

 
 Open  
create a Code of Conduct document #111 

@ultrasaurus ultrasaurus opened this issue 
 10 months ago 

 3 - For Review  Content  Needs Approval  

It is becoming common for open source projects and there are people who won't participate in events unless there is one.

Where will this be used? if human, then this applies 
•events, slack, mailing lists, github issues
•applies to everyone (18F team, GSA, other feds, private sector people who interact with us or in our communities)

This should be published on the website for easy access.

I'd like the follow the Bridge Foundry model where the Code of Conduct is more than an anti-harrassment policy (which is what most conferences do) and instead describe a higher bar of acceptable conduct. 

Examples:
• Bridge Foundry Code of Conduct used for RailsBridge, and other related workshops and opens source projects
•https://openhatch.org/wiki/Project_codes_of_conduct
•http://yesandyesyes.com/code-of-conduct
•http://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/
•http://geekfeminism.wikia.com/wiki/Code_of_conduct
•http://www.pyladies.com/CodeOfConduct/
•https://www.hackerschool.com/manual#sec-environment

More links added: 
•http://geekfeminism.org/about/code-of-conduct/
•https://www.python.org/psf/codeofconduct/

Proposed Outline
•Diversity Statement 
•Our values?
•What does it mean to be welcoming (examples?)
•Links to other stuff (anti-harrassment, ethics?, open source policy)

Diversity Statement

18F welcomes and encourages participation by everyone. We work for the America people, and welcome participation from anyone in the world with a desire to improve our projects.

No matter how you identify yourself or how others perceive you: we welcome you. We welcome contributions from everyone as long as they interact constructively with our community. 

We are responsible for technical implementation, but most of our work is not technical in nature. We value and encourage contributions from those with expertise in policy, private sector or public service, writing, design, usability, as well as code, and welcome them into our community.

@quepol quepol 
10 months ago
 

:+1: 
•https://openhatch.org/wiki/Project_codes_of_conduct
•http://yesandyesyes.com/code-of-conduct
•http://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/
•http://geekfeminism.wikia.com/wiki/Code_of_conduct

@jackiekazil jackiekazil 
10 months ago
 

:+1: 
 There are a bunch of different styles out there. Here is another...
•http://www.pyladies.com/CodeOfConduct/

I think we should have identify the exact purpose to make sure that we are focused in our style. 

@jpyuda jpyuda 
10 months ago
 

+1 to @jackiekazil - a code of conduct for employees has a different tone, voice, and backing authorities (gsa policy, the law) than one that covers events we host. And both would likely differ from one covering open-source projects. 

I feel like the need is strongest for open source - aren't we covered to a certain extent in the other cases by existing policy?

@ultrasaurus ultrasaurus 
10 months ago
 

Great point @jpyuda and @jackiekazil on audience and purpose.

I think it is important to have guidelines for our whole community, not just us. I can imagine a (not too distant) future where we could have a volunteer contributor (with commit rights) who is not a federal employee and we should be clear what behavior we expect from them. 

Also, my guess is that online guidance about open source project behavior will be a superset of in-person, and it is likely simpler to have a single document (even though it might link to others).

@ultrasaurus ultrasaurus 
10 months ago
 

I added everyone's examples, plus a draft outline and some text starting with a diversity statement. What do other people want to see in this? If folks are into it, we could schedule a group editing session to quickly come up with a first draft, maybe sometime next week after people have a chance to comment on goals. 

@quepol quepol 
9 months ago
 

@18F/18f does this tag a team? #testing 

@NoahKunin NoahKunin 
9 months ago
 

yup

@NoahKunin NoahKunin 
9 months ago
 

If you hover over the tag, you can see who gets a notification

@quepol quepol 
9 months ago
 

awesome. sorry to temporarily hijack the thread. for a good cause. :)

@gbinal gbinal 
9 months ago
 

Joining the conversation late but would love to help drive this. Did I miss anything last week or is there something coming up? 

I'm a fan of group editing a pull request to iron out what we want and where. Perhaps we begin with a pull request to create 18f.gsa.gov/code_of_conduct? 

@ultrasaurus ultrasaurus 
9 months ago
 

yeah, @jackiekazil and I were going to kick off a first draft. Thanks for waking up the thread!

Assigned ultrasaurus was assigned by NoahKunin 9 months ago 

@NoahKunin NoahKunin 
9 months ago
 

Putting down assignees personally helps me query and visualize what ppl are working on across the repo and overall helps with "who's on first". It will also helps once we start rocking the GitHub API to create dashboards. 

@ultrasaurus ultrasaurus 
9 months ago
 

Thanks @NoahKunin -- happy to take responsibility to shepherding this!

@gbinal gbinal 
8 months ago
 

Any updates? 

@konklone konklone 
8 months ago
 

@ultrasaurus @jackiekazil I'm loathe to close this one, since it seems like work has been done -- is this still something we want to get on the site?

@jackiekazil jackiekazil 
8 months ago
 
We are in the process to putting together a draft to submit to the group in the near future.

@ultrasaurus ultrasaurus 
about 1 month ago
 

this moved to its own repo here: https://github.com/18F/code-of-conduct

Closed konklone closed this issue about 1 month ago 

@ultrasaurus ultrasaurus 
about 1 month ago
 

@gboone wanted to leave this open, since he's considering that it may be appropropriate to be displayed as a page on 18F site in the future

Reopened ultrasaurus reopened this issue about 1 month ago 

Content gboone added this label 20 days ago 

Needs Approval gboone added this label 20 days ago 

2 - For Review elainekamlley added this label 20 days ago 

@gboone gboone 
20 days ago
 

Wondering if we've made any in-roads to approval from the appropriate parties on this? If I'm remembering correctly, this is all that's blocking us from publishing:
 HR approval
 General Counsel approval

 
 Leave a comment 
Comment 

 You're not receiving notifications from this thread. 

     
 Subscribe 

    Desktop version

**Comment by konklone** [comment]
Closing until there's evidence of context for this.
