### ISSUE TITLE
Front Page Scroll Indicator

### ISSUE THREAD

**Issue by PeterSP** [18F/18f.gsa.gov#804]
The front page currently might want a scroll arrow/indicator to make it more obvious that there's more to it than the beautiful photograph, logo, and header.

This is the most obvious idea that comes to mind, there may be better ways to eliminate front-page frustration.

**Comment by gboone** [comment]
Thanks for the suggestion, @peterSP, we've heard this feedback from several users (though you're the first to express it here :smiley:) and are working on some different approaches to a solution. We'll let you know if we make any progress, and let us know if you have any other thoughts. Thanks again!

**Comment by neilmartis** [comment]
I was thinking of adding a floating down button and up button which would float on the entire page towards the margin like a floating scroll bar which would enable to user to navigate easily up and down.Do let me know greg what you think
