### ISSUE TITLE
On the team page, clicking on the photo/name doesn't take me to the profile

### ISSUE THREAD

**Issue by khandelwal** [18F/18f.gsa.gov#814]
https://staging.18f.us/team/ 

Clicking on the name shows me the link, but doesn't take me there. If this is intentional, the user experience is confusing. If it isn't intentional, I'm assuming I win some bounty by having found a bug.

**Comment by gboone** [comment]
Got a patch coming in for this later today. The issue is we're not ready with the design on those pages but wanted to ship `/team`. The solution was to disable the links and patch it with a better solution shortly after.

**Comment by khandelwal** [comment]
Looks like we should just close this then, yeah?

**Comment by gboone** [comment]
I'll keep it open till it ships. Keeps me honest.

**Comment by khandelwal** [comment]
+1
