### ISSUE TITLE
Mime type for RSS feed is HTML

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#828]
I feel like it used to be a proper XML mime type? But even though the RSS feed is back to normal content [on staging](https://staging.18f.us/feed/), the mime type is `text/html`. This might inhibit compatibility with some clients. I don't know what to do about it while keeping the `/feed/` URL, except to add an exception rule in the nginx vhost.

**Comment by gboone** [comment]
I think that's the only way.

**Comment by gboone** [comment]
I wonder if it ever was getting the correct content type. With #829 my browsers are rendering the content as XML but Jekyll is generating an HTML file.

I'm going to continue playing around with this but as long as browsers are picking up on it as a feed again I'm good with rolling #829 to production.

**Comment by gboone** [comment]
Okay. I've tried a couple things:
1.Override the "default" layout to `false`: Jekyll generates an xml file with an html extension
2. Move feed.xml to `feed/index.xml`: same as 1
3. Move feed.xml into the root directory: `feed.xml` is generated and served with the correct content-type
4. Add `permalink: /feed/`to the frontmatter: same as 1
5. Add `permalink: /feed/index.xml` to the frontmatter: same as 3

I think our solution is 5 and make sure `index.html` is an acceptable index document in our nginx config

**Comment by konklone** [comment]
Nice, totally agree.

**Comment by gboone** [comment]
I'm getting a syntax error with 5 now, working that out and I'll issue a PR when I get it sorted.

**Comment by gboone** [comment]
PR open at #831
