### ISSUE TITLE
Sort/order on team page isn't intuitive to the public

### ISSUE THREAD

**Issue by wslack** [18F/18f.gsa.gov#845]
I think we are currently sorting by the name of the person in data-private, but the impact is that the page shows "Will Slack" and then "John Yuda" at the end. There's not a clear sorting heuristic.

**Comment by gbinal** [comment]
+1 - Def. recommend switching to something that makes sense right off, like alphabetical by first or last name.

**Comment by jenniferthibault** [comment]
Hmmm, by design it's supposed to be alphabetical by first name, but there seems to be some bugs. @gboone i'm not sure if you know why?

**Comment by wslack** [comment]
I bet its sorting by the name in https://github.com/18F/data-private/tree/master/team (see Mike B and Meghana)

**Comment by gboone** [comment]
Will is correct. We didn't have time for sorting by last name for this iteration and haven't had time to get back to it. Pull requests welcome.

**Comment by gboone** [comment]
It's alphabetical as of #882
