### ISSUE TITLE
optimize images on /team 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#854]
To help the page load faster, optimize all those images.   

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2F18f.gsa.gov%2Fteam%2F&tab=desktop

**Comment by gboone** [comment]
This should be done with #856

**Comment by gboone** [comment]
Actually, I'm wrong about that. These images are as optimized as I can get them with ImageOptim. When I drop the /images/team folder into that application they are shown as already optimized. AFAIK they are also all as small (in pixels) as they can be to render properly on the site.

**Comment by gboone** [comment]
We can reopen if there are other options or tools available we can use to optimize these images.

**Comment by gbinal** [comment]
Odd.  Google's Pagespeed Insights (linked above) seemed to think that it might still be possible.  For the desktop view, that page is getting a significantly lower score (38/100) than the other pages on the site.

**Comment by gboone** [comment]
I totally agree it's odd and noticed the pagespeed score, too. I'm just not sure what more we can do about it. @konklone do you know any other strategies for optimizing images.

**Comment by konklone** [comment]
Google used to have a PageSpeed Chrome extension that would convert the images for you. They seem to have deprecated it. We can mess around with other open source tools, but not sure offhand.

**Comment by konklone** [comment]
Here's Google's guide on the subject: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization
