### ISSUE TITLE
align tops of pages 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#855]
Each of the pages linked from the menu at the top of the site have a different layout and look/feel. In some cases, the logo in the top left are close but in slightly different positions;  in others, the page titles and intro text is a bit varied from each other.  It'd be great to begin aligning those.

**Comment by gboone** [comment]
More texture on this issue: the issue is the new styles we applied to `team` haven't been ported back to 18F/dashboard or the existing page and blog post templates. The plan is to adopt the same positioning and styles seen on `/team` across the board.
