### ISSUE TITLE
getting a 404 when clicking on "how we work" tag in der blog

### ISSUE THREAD

**Issue by jtag** [18F/18f.gsa.gov#917]
https://18f.gsa.gov/tags/how%20we%20work

**Comment by jackiekazil** [comment]
Where are clicking on that tag?
Because from here: https://18f.gsa.gov/tags/, it seems to work and takes
you here: https://18f.gsa.gov/tags/how-we-work/

**Comment by gboone** [comment]
Yes, @jtag can you tell us where you clicked a link took you to `/tags/how%20we%20work`? All links on our site should be updated to `tags/how-we-work/` but I definitely need to know where to fix them if they're not. #921 will resolve this by redirecting `how we work` to `how-we-work` but I'd like to be putting the correct link wherever possible.

**Comment by elainekamlley** [comment]
It happens on https://site.18f.gov/blog/ when you click on the tag from the preview. 
![screen shot 2015-06-11 at 10 29 49 am](https://cloud.githubusercontent.com/assets/7362915/8109460/c8dc6c5a-1024-11e5-9ee4-4f23a099e21d.png)

**Comment by gboone** [comment]
thanks, @elainekamlley
