### ISSUE TITLE
Hard to find past blog posts that are really valuable

### ISSUE THREAD

**Issue by jtag** [18F/18f.gsa.gov#918]
1. As a reader I only know the tags exist either by seeing the ones that happen to be on recent posts. How will I know there are design blgo posts unless a recent post contains that tag. How might I view all tags to better browse content.

2. As an 18Fer writing reports, recommendation to clients, I often want to know if someone has written a great blog post (ne "whitepaper") on a certain topic. In tonight's instance, on developing software in the open, something that I could link to to add color and authority to my statement. How can I find it w/o search or clear tags? Or a canonical top 10 list or something like that? Or a page with our main principles flushed out and links embedded in there? Or, or or...

Delete, merge, whatever you need to do if this is covered somewhere else.

**Comment by gboone** [comment]
There's https://18f.gsa.gov/tags/ which might help with no. 1

As for no. 2, the tags page might help, but there's also a possibility of mining some we analytics to surface popular posts. Thanks @jtag.

**Comment by elainekamlley** [comment]
@jtag we also have a search feature in the wings at #881. We're looking to make the entire site more searchable especially the blog posts.

**Comment by melodykramer** [comment]
The WBUR CommonHealth site has a [bar](http://commonhealth.wbur.org/) across the top that says "Don't Miss" which points to archival pieces that WBUR wants to surface.

We could also create a Start Here page ([Example](http://erickimphotography.com/blog/start-here/)) page for newcomers. I like the way that photographer has his set up and would be happy to work on this. It seems like it would be useful for multiple audiences (internal, external.)

**Comment by jtag** [comment]
Cool!
Also some of our blog posts serve as white papers, or may. So helping our
audience access those will be valuable.



Jesse Taggert
Director Product Strategy, User Experience & Design Practices
18F Consulting Services | GSA
cell: 415-730-4965
18F.gsa.gov <http://18f.gsa.gov/>


On Jul 20, 2015, at 10:51 AM, Melody Kramer <notifications@github.com>
wrote:

The WBUR CommonHealth site has a bar <http://commonhealth.wbur.org/> across
the top that says "Don't Miss" which points to archival pieces that WBUR
wants to surface.

We could also create a Start Here page (Example
<http://erickimphotography.com/blog/start-here/>) page for newcomers. I
like the way that photographer has his set up and would be happy to work on
this. It seems like it would be useful for multiple audiences (internal,
external.)

—
Reply to this email directly or view it on GitHub
<https://github.com/18F/18f.gsa.gov/issues/918#issuecomment-122966780>.

**Comment by neilmartis** [comment]
I was thinking of add an elastic search to the blog's page in that we can search the related blog post pretty quickly based on the tags which are already there in place or by the author or title of the required blog post
