### ISSUE TITLE
Feedback: Newsletter Sign Up Experience

### ISSUE THREAD

**Issue by jenniferthibault** [18F/18f.gsa.gov#977]
Observations on signing up for 18F's newsletter. I put my "first time someone is interacting with 18F" hat on when going through this, so comments are mostly from that perspective:

* When looking for where to sign up for the newsletter, I went to several other pages before realizing that it was a sign up through the "Contact" form on the home page. The current language makes it seem like you're signing up for someone at 18F to contact you about a business inquiry, rather than a newsletter. I didn't expect "Sign Up for More Information" to mean "Sign up for our newsletter." This looks like it is being addressed in #952 
* The Sender and Subject line of the confirmation email upon signing up definitely looks like a spam email. I was expecting to see "18F" somewhere in the mail preview, ideally the sender. (Not sure that people will make the GSA connection right off the bat.) Here it is in my inbox list:
![screen shot 2015-07-01 at 12 29 20 pm](https://cloud.githubusercontent.com/assets/11636908/8459688/f05200f6-1fec-11e5-849b-2ee2e03cca3d.png)

And here it is opened:

![screen shot 2015-07-01 at 12 15 42 pm](https://cloud.githubusercontent.com/assets/11636908/8459697/0079be38-1fed-11e5-8a5e-ec947d779c91.png)
* At this point, it didn't feel like a positive interaction with 18F. I was skeptical because it was so "undesigned" and spammy-looking. I think this is a great opportunity to improve peoples' first interaction with 18F to whatever degree we can control: A warmer, friendlier invite, with more of a human tone than computer, perhaps even something that had our logo or basic elements of a design.
* The email I received for confirming was an improvement! I could see it was 18F related.
![screen shot 2015-07-01 at 12 35 15 pm](https://cloud.githubusercontent.com/assets/11636908/8459821/c6e1818c-1fed-11e5-9776-6e2a7638bccf.png)

cc @elainekamlley & @awfrancisco

**Comment by melodykramer** [comment]
I just signed up for the newsletter and received a different email that looks like this: 
![screen shot 2015-07-20 at 12 30 11 pm](https://cloud.githubusercontent.com/assets/5784474/8781077/1fde7b4a-2edb-11e5-9e82-49f3ab28064e.png)

* This looks Iike I'm subscribing to a listserv and not a newsletter
* It appears like you can't subscribe with only a first name (?)

**Comment by awfrancisco** [comment]
Looks like that is an error message since you didn't fill in both name
fields. But we are going to be replacing that sign up form so it directs to
Mailchimp, so all these ugly messages will go away.

On Mon, Jul 20, 2015 at 12:32 PM, Melody Kramer <notifications@github.com>
wrote:

> I just signed up for the newsletter and received a different email that
> looks like this:
> [image: screen shot 2015-07-20 at 12 30 11 pm]
> <https://cloud.githubusercontent.com/assets/5784474/8781077/1fde7b4a-2edb-11e5-9e82-49f3ab28064e.png>
>
>    - This looks Iike I'm subscribing to a listserv and not a newsletter
>    - It appears like you can't subscribe with only a first name (?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.gsa.gov/issues/977#issuecomment-122941580>.
>



-- 
Andre Francisco
Content Designer
andre.francisco@gsa.gov
202-286-5049

**Comment by melodykramer** [comment]
Great! :+1:

**Comment by melodykramer** [comment]
@awfrancisco Can I close this issue? I think these changes were made.

**Comment by awfrancisco** [comment]
Yup. Thanks for circling back on this.
