### ISSUE TITLE
text is slightly off on bio pages 

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#992]
![screenshot 2015-07-02 at 4 03 08 pm](https://cloud.githubusercontent.com/assets/633088/8486634/e846bd06-20d3-11e5-94e8-0d41aec44faa.png)

**Comment by konklone** [comment]
Browser/OS?

**Comment by gboone** [comment]
That would be helpful, rough guess of screen size, too. Looks like a smaller screen.

**Comment by gbinal** [comment]
chrome on chromeos laptop, screen is 13.3 inches (1920 x 1080 resolution)

**Comment by gboone** [comment]
Thanks @gbinal, I'll look into this before we deploy these to production.
