### ISSUE TITLE
Team/Title for Will Slack and Team for Stephanie Rivera

### ISSUE THREAD

**Issue by wslack** [18F/18f.gsa.gov#997]
@StephanieRivera and I are on the strategy team (vs operations).

Also, while we are listed together on the org chart, a better title for me is "Business Strategy Lead."

https://github.com/18F/18f.gsa.gov/blob/staging/_team/will.md
https://github.com/18F/18f.gsa.gov/blob/staging/_team/stephanierivera.md

**Comment by elainekamlley** [comment]
Thanks @wslack! I'll fix that up.

**Comment by elainekamlley** [comment]
Closes with #1024
